/**
 * Created by tovan on 2/20/2017.
 */
import {Word} from '../models/word';
//id 0 là tiêu đề và nội dung chính
//id 1 trở đi là nội dung từng câu
//text là nội dung text, nội dung trong file mp3
//file name là tên file dùng option để lấy rõ địa chỉ file
export const ACTION_WORDS_1: Word[] = [
  {id:0,text:"Từ Chỉ Hành Động",filename:"action-words-title"},
  {id:1,text:"vỗ",filename:"clap"},
  {id:2,text:"vẫy",filename:"wave"},
  {id:3,text:"đá",filename:"kick"},
  {id:4,text:"chỉ",filename:"point"},
  {id:5,text:"cười",filename:"smile"},
  {id:6,text:"ăn",filename:"eat"},
  {id:7,text:"đứng",filename:"stand"},
  {id:8,text:"ngồi",filename:"sit"},
  {id:9,text:"uống",filename:"drink"}
];
export const ACTION_WORDS_2: Word[] = [
  {id:0,text:"Từ Chỉ Hành Động",filename:"action-words-title"},
  {id:1,text:"hôn",filename:"kiss"},
  {id:2,text:"khócc",filename:"cry"},
  {id:3,text:"nhảy",filename:"jump"},
  {id:4,text:"bò",filename:"crawl"},
  {id:5,text:"gật",filename:"nod"},
  {id:6,text:"đọc",filename:"read"},
  {id:7,text:"ngủ",filename:"sleep"},
  {id:8,text:"ôm",filename:"hug"},
  {id:9,text:"múa",filename:"dance"},
  {id:10,text:"thổi",filename:"blow"}
];
export const ACTION_WORDS_3: Word[] = [
  {id:0,text:"Từ Chỉ Hành Động",filename:"action-words-title"},
  {id:1,text:"chạy",filename:"run"},
  {id:2,text:"đi",filename:"walk"},
  {id:3,text:"quỳ",filename:"kneel"},
  {id:4,text:"ngồi xổm",filename:"squat"},
  {id:5,text:"nhảy qua",filename:"leap"},
  {id:6,text:"nhảy lò cò",filename:"skip"},
  {id:7,text:"đi nhóm chân",filename:"tiptoe"},
  {id:8,text:"xoay tròn",filename:"spin"},
  {id:9,text:"dừng lại",filename:"stop"}
];
export const ANIMALS_AND_BODY_PARTS: Word[] = [
  {id: 0, text:"Động Vật và Bộ Phận Cơ Thể",filename:"animals-and-parts-of-body-title"},
  {id: 1, text:"chân chim",filename:"bird-leg"},
  {id: 2, text:"lưỡi chó",filename:"dog-tongue"},
  {id: 3, text:"đầu vịt",filename:"duck-head"},
  {id: 4, text:"miệng cá",filename:"fish-mouth"},
  {id: 5, text:"răng ngựa",filename:"horse-teeth"},
  {id: 6, text:"tai thỏ",filename:"rabbit-ear"},
];
export const BABY_THINGS: Word[] = [
  {id: 0, text:"Đồ Vật Của Em Bé",filename:"baby-things-title"},
  {id: 1, text:"nôi ",filename:"crib"},
  {id: 2, text:"xe đẩy",filename:"stroller"},
  {id: 3, text:"tã",filename:"diaper"},
  {id: 4, text:"núm vú giả",filename:"pacifier"},
  {id: 5, text:"bình sữa",filename:"bottle"},
  {id: 6, text:"ghế ăn",filename:"high-chair"},
  {id: 7, text:"ghế ngồi xe hơi",filename:"carseat"},
  {id: 8, text:"cũi",filename:"playpen"},
  {id: 9, text:"yếm",filename:"bib"},
  {id: 10, text:"lục lạc",filename:"rattle"},
  {id: 11, text:"khăn ướt",filename:"wipes"},
];
export const COLORS_1: Word[] = [
  {id: 0, text:"Màu Sắc",filename:"colour-title"},
  {id: 1, text:"đỏ",filename:"red"},
  {id: 2, text:"xanh lá",filename:"green"},
  {id: 3, text:"xanh dương",filename:"blue"},
  {id: 4, text:"vàng",filename:"yellow"},
  {id: 5, text:"cam",filename:"orange"},
  {id: 6, text:"nâu",filename:"brown"},
  {id: 7, text:"hồng",filename:"pink"},
  {id: 8, text:"tím",filename:"purple"},
  {id: 9, text:"đen",filename:"black"},
  {id: 10, text:"trắng",filename:"white"},
];
export const COLORS_AND_SHAPES: Word[] = [
  {id: 0, text:"Màu Sắc và Hình Dạng",filename:"shapes-title"},
  {id: 1, text:"sao vàng",filename:"star"},
  {id: 2, text:"hình vuông xanh",filename:"square"},
  {id: 3, text:"hình chữ nhật đen",filename:"rectangle"},
  {id: 4, text:"hình tròn hồng",filename:"circle"},
  {id: 5, text:"hình tam giác nâu",filename:"triangle"},
  {id: 6, text:"sao xanh lá",filename:"star"},
  {id: 7, text:"hình vuông trắng",filename:"square"},
  {id: 8, text:"hình chữ nhật đỏ",filename:"rectangle"},
  {id: 9, text:"hình tròn xanh dương",filename:"circle"},
  {id: 10, text:"hình tam giác tím",filename:"triangle"},
];
export const COMMON_ANIMALS_1: Word[] = [
  {id: 0, text:"Động Vật Thông Thường",filename:"common-animals-title"},
  {id: 1, text:"chó",filename:"dog"},
  {id: 2, text:"mèo",filename:"cat"},
  {id: 3, text:"ngựa",filename:"horse"},
  {id: 4, text:"lợn",filename:"pig"},
  {id: 5, text:"chim",filename:"bird"},
  {id: 6, text:"vịt",filename:"duck"},
  {id: 7, text:"ếch",filename:"frog"},
  {id: 8, text:"lừa",filename:"donkey"},
  {id: 9, text:"cá",filename:"fish"},
];
export const COMMON_ANIMAL_2: Word[] = [
  {id: 0, text:"Động Vật Thông Thường",filename:"common-animals-title"},
  {id: 1, text:"gà",filename:"chicken"},
  {id: 2, text:"bò",filename:"cow"},
  {id: 3, text:"chuột",filename:"mouse"},
  {id: 4, text:"thỏ",filename:"rabbit"},
  {id: 5, text:"dê",filename:"goat"},
  {id: 6, text:"cừu",filename:"sheep"},
  {id: 7, text:"thằn lằn",filename:"lizard"},
  {id: 8, text:"trâu",filename:"water-buffalo"},
];
export const FOOD_1: Word[] = [
  {id: 0, text:"Thức Ăn",filename:"food-title"},
  {id: 1, text:"ngũ cốc",filename:"cereal"},
  {id: 2, text:"bánh quy",filename:"cookies"},
  {id: 3, text:"bánh mì",filename:"bread"},
  {id: 4, text:"trứng",filename:"egg"},
  {id: 5, text:"cơm",filename:"rice"},
  {id: 6, text:"khoai tây",filename:"potato"},
  {id: 7, text:"rau trộn",filename:"salad"},
  {id: 8, text:"súp",filename:"soup"},
  {id: 9, text:"sữa chua",filename:"yogurt"},
];
export const FRUITS_1: Word[] = [
  {id: 0, text:"Trái Cây",filename:"fruits-title"},
  {id: 1, text:"táo",filename:"apple"},
  {id: 2, text:"cam",filename:"orange"},
  {id: 3, text:"chuối",filename:"banana"},
  {id: 4, text:"dâu",filename:"strawberry"},
  {id: 5, text:"chanh",filename:"lemon"},
  {id: 6, text:"nho",filename:"grape"},
  {id: 7, text:"lê",filename:"pear"},
  {id: 8, text:"thơm",filename:"pineapple"},
  {id: 9, text:"dưa hấu",filename:"watermelon"},
];
export const HAND_ACTIONS_1: Word[] = [
  {id: 0, text:"Hành Động Tay",filename:"hand-actions-title"},
  {id: 1, text:"lấy",filename:"take"},
  {id: 2, text:"đưa",filename:"give"},
  {id: 3, text:"nắm",filename:"hold"},
  {id: 4, text:"nhặt",filename:"pick"},
  {id: 5, text:"cầm",filename:"grab"},
  {id: 6, text:"đặt",filename:"put"},
  {id: 7, text:"thả",filename:"drop"},
  {id: 8, text:"nâng",filename:"lift"},
  {id: 9, text:"ném",filename:"throw"},
  {id: 10, text:"bắt",filename:"catch"},
];
export const HAND_ACTIONS_2: Word[] = [
  {id: 0, text:"Hành Động Tay",filename:"hand-actions-title"},
  {id: 1, text:"kéo",filename:"pull"},
  {id: 2, text:"đẩy",filename:"push"},
  {id: 3, text:"gãi",filename:"scratch"},
  {id: 4, text:"với",filename:"reach"},
  {id: 5, text:"lắc",filename:"shake"},
  {id: 6, text:"tâng",filename:"bounce"},
  {id: 7, text:"mang",filename:"carry"},
  {id: 8, text:"đánh",filename:"hit"},
  {id: 9, text:"chạm",filename:"touch"},
  {id: 10, text:"cảm nhận",filename:"feel"},
];
export const KIDS_THINGS: Word[] = [
  {id: 0, text:"Đồ Vật Trẻ Em",filename:"kids-things-title-"},
  {id: 1, text:"đồ chơi",filename:"toy"},
  {id: 2, text:"gấu bông",filename:"teddy-bear"},
  {id: 3, text:"búp bê",filename:"doll"},
  {id: 4, text:"màu sáp",filename:"crayon"},
  {id: 5, text:"bóng",filename:"ball"},
  {id: 6, text:"bóng bay",filename:"balloon"},
  {id: 7, text:"bong bóng xà phòng",filename:"bubble"},
  {id: 8, text:"hình khối",filename:"blocks"},
  {id: 9, text:"xếp hình",filename:"puzzle"},
  {id: 10, text:"xếp gạch",filename:"bricks"},
  {id: 11, text:"sách",filename:"book"},
];
export const NATURE_1: Word[] = [
  {id: 0, text:"Thiên nhiên",filename:"nature-title"},
  {id: 1, text:"mặt trời",filename:"sun"},
  {id: 2, text:"mặt trăng",filename:"moon"},
  {id: 3, text:"sao",filename:"star"},
  {id: 4, text:"bầu trời",filename:"sky"},
  {id: 5, text:"mây",filename:"cloud"},
  {id: 6, text:"cầu vồng",filename:"rainbow"},
  {id: 7, text:"tuyết",filename:"snow"},
  {id: 8, text:"mưa",filename:"rain "},
  {id: 9, text:"sấm chớp",filename:"thunder-and-lightening"},
  {id: 10, text:"lửa",filename:"fire"},
  {id: 11, text:"gió",filename:"wind"},
];
export const NATURE_2: Word[] = [
  {id: 0, text:"Thiên nhiên",filename:"nature-title"},
  {id: 1, text:"núi",filename:"mountain"},
  {id: 2, text:"cây",filename:"tree"},
  {id: 3, text:"cỏ",filename:"grass"},
  {id: 4, text:"rừng",filename:"forest"},
  {id: 5, text:"hoa",filename:"flower"},
  {id: 6, text:"đất",filename:"soil"},
  {id: 7, text:"đồi",filename:"hill"},
  {id: 8, text:"bụi rậm",filename:"bush"},
  {id: 9, text:"thác",filename:"waterfall"},
];
export const PARTS_OF_THE_BODY_HEAD: Word[] = [
  {id: 0, text:"Bộ Phận Cơ Thể - Đầu",filename:"parts-body-head-title"},
  {id: 1, text:"tóc",filename:"hair"},
  {id: 2, text:"mắt",filename:"eye"},
  {id: 3, text:"mũi",filename:"nose"},
  {id: 4, text:"tai",filename:"ear"},
  {id: 5, text:"miệng",filename:"mouth"},
  {id: 6, text:"cằm",filename:"chin"},
  {id: 7, text:"môi",filename:"lip"},
  {id: 8, text:"răng",filename:"tooth"},
  {id: 9, text:"lưỡi",filename:"tongue"},
];
export const PART_OF_THE_BODY_1: Word[] = [
  {id: 0, text:"Bộ Phận Cơ Thể",filename:"parts-body-title"},
  {id: 1, text:"cổ",filename:"neck"},
  {id: 2, text:"đầu",filename:"head"},
  {id: 3, text:"bàn tay",filename:"hand"},
  {id: 4, text:"chân",filename:"leg"},
  {id: 5, text:"rốn",filename:"belly-button"},
  {id: 6, text:"tay",filename:"arm"},
  {id: 7, text:"ngón tay",filename:"finger"},
  {id: 8, text:"bàn chân",filename:"foot"},
  {id: 9, text:"vai",filename:"shoulder"},
  {id: 10, text:"ngón chân",filename:"toe"},
];
export const PART_OF_THE_BODY_2: Word[] = [
  {id: 0, text:"Bộ Phận Cơ Thể",filename:"parts-body-title"},
  {id: 1, text:"hông",filename:"hips"},
  {id: 2, text:"eo",filename:"waist"},
  {id: 3, text:"đùi",filename:"thigh"},
  {id: 4, text:"đầu gối",filename:"knee"},
  {id: 5, text:"cổ chân",filename:"ankle"},
  {id: 6, text:"gót chân",filename:"heel"},
  {id: 7, text:"trán",filename:"forehead"},
  {id: 8, text:"cổ tay",filename:"wrist"},
  {id: 9, text:"bụng",filename:"belly"},
];
export const PEOPLE: Word[] = [
  {id: 0, text:"Con Người",filename:"people-title"},
  {id: 1, text:"đàn ông",filename:"man"},
  {id: 2, text:"phụ nữ",filename:"woman"},
  {id: 3, text:"ông lão",filename:"old-man"},
  {id: 4, text:"bà lão",filename:"old-woman"},
  {id: 5, text:"con trai",filename:"boy"},
  {id: 6, text:"con gái",filename:"girl"},
  {id: 7, text:"bé trai",filename:"baby-boy"},
  {id: 8, text:"bé gái",filename:"baby-girl"},
  {id: 9, text:"em bé",filename:"baby"},
];
export const SHAPES: Word[] = [
  {id: 0, text:"Hình Dạng",filename:"shapes-title"},
  {id: 1, text:"hình tròn",filename:"circle"},
  {id: 2, text:"hình vuông",filename:"square"},
  {id: 3, text:"hình chữ nhật",filename:"rectangle"},
  {id: 4, text:"hình tam giác",filename:"triangle"},
  {id: 5, text:"hình bầu dục",filename:"oval"},
  {id: 6, text:"hình sao",filename:"star"},
  {id: 7, text:"hình thoi",filename:"diamond"},
  {id: 8, text:"hình trái tim",filename:"heart"},
];
export const THE_SOLAR_SYSTEM: Word[] = [
  {id: 0, text:"Hệ Mặt Trời",filename:"solar-system-title"},
  {id: 1, text:"Mặt trời",filename:"sun"},
  {id: 2, text:"Sao thủy",filename:"mercury"},
  {id: 3, text:"Sao kim",filename:"venus"},
  {id: 4, text:"Trái đất",filename:"earth"},
  {id: 5, text:"Sao hỏa",filename:"mars"},
  {id: 6, text:"Sao mộc",filename:"jupiter"},
  {id: 7, text:"Sao thổ",filename:"saturn"},
  {id: 8, text:"Sao thiên vương",filename:"uranus"},
  {id: 9, text:"Sao hải vương",filename:"neptune"},
];
export const THINGS_AT_HOME_MEALTIME: Word[] = [
  {id: 0, text:"Đồ Vật Ở Nhà - Giờ Ăn",filename:"things-at-home-meal-title"},
  {id: 1, text:"chai",filename:"bottle"},
  {id: 2, text:"ly",filename:"glass"},
  {id: 3, text:"dao",filename:"knife"},
  {id: 4, text:"khăn",filename:"napkin"},
  {id: 5, text:"bát",filename:"bowl"},
  {id: 6, text:"đĩa",filename:"plate"},
  {id: 7, text:"dĩa",filename:"fork"},
  {id: 8, text:"tách",filename:"cup"},
  {id: 9, text:"thìa",filename:"spoon"},
  {id: 10, text:"đũa",filename:"chopstick"},
];
export const THINGS_AT_HOME_1: Word[] = [
  {id: 0, text:"Đồ Vật Ở Nhà",filename:"things-at-home-title"},
  {id: 1, text:"giường",filename:"bed"},
  {id: 2, text:"bàn",filename:"table"},
  {id: 3, text:"ghế tựa",filename:"chair"},
  {id: 4, text:"ghế đẩu",filename:"stool"},
  {id: 5, text:"tủ",filename:"wardrobe"},
  {id: 6, text:"chổi",filename:"broom"},
  {id: 7, text:"gương",filename:"mirror"},
  {id: 8, text:"thảm",filename:"rug"},
  {id: 9, text:"bàn làm việc",filename:"desk"},
];
export const THINGS_AT_HOME_2: Word[] = [
  {id: 0, text:"Đồ Vật Ở Nhà",filename:"things-at-home-title"},
  {id: 1, text:"gối",filename:"pillow"},
  {id: 2, text:"gối tựa",filename:"cushion"},
  {id: 3, text:"chăn",filename:"blanket"},
  {id: 4, text:"rèm",filename:"curtains"},
  {id: 5, text:"bình",filename:"vase"},
  {id: 6, text:"ảnh",filename:"photo"},
  {id: 7, text:"khung ảnh",filename:"picture-frame"},
  {id: 8, text:"kệ giày",filename:"shoe-shelf"},
  {id: 9, text:"kệ sách",filename:"bookcase"},
];
export const THINGS_AT_HOME_3: Word[] = [
  {id: 0, text:"Đồ Vật Ở Nhà",filename:"things-at-home-title"},
  {id: 1, text:"nến",filename:"candle"},
  {id: 2, text:"hộp",filename:"box"},
  {id: 3, text:"túi",filename:"bag"},
  {id: 4, text:"móc",filename:"wall-hook"},
  {id: 5, text:"đồng hồ",filename:"clock"},
  {id: 6, text:"khăn giấy",filename:"tissue"},
  {id: 7, text:"ô",filename:"umbrella"},
  {id: 8, text:"chìa khóa",filename:"key"},
  {id: 9, text:"móc quần áo",filename:"hanger"},
  {id: 10, text:"đĩa hát",filename:"disc"},
];
export const THINGS_WE_WEAR_1: Word[] = [
  {id: 0, text:"Những Thứ Chúng Ta Mặc",filename:"things-we-wear-title"},
  {id: 1, text:"dép",filename:"slippers"},
  {id: 2, text:"chân váy",filename:"skirt"},
  {id: 3, text:"tất",filename:"socks"},
  {id: 4, text:"giày",filename:"shoes"},
  {id: 5, text:"áo khoác",filename:"coat"},
  {id: 6, text:"váy",filename:"dress"},
  {id: 7, text:"thắt lưng",filename:"belt"},
  {id: 8, text:"quần dài",filename:"pants"},
  {id: 9, text:"áo sơ mi",filename:"shirt"},
  {id: 10, text:"quần áo",filename:"clothes"},
];
export const TRADITIONAL_COSTUMES: Word[] = [
  {id: 0, text:"Trang phục và phụ kiện truyền thống",filename:"traditional-vietnamese-costume-title"},
  {id: 1, text:"Áo dài",filename:"ao-dai"},
  {id: 2, text:"Áo bà ba",filename:"ao-ba-ba"},
  {id: 3, text:"Khăn rằn",filename:"khan-ran"},
  {id: 4, text:"Nón lá",filename:"non-la"},
  {id: 5, text:"Guốc gỗ",filename:"guoc-go"},
]
export const TRADITIONAL_FOOD: Word[] = [
  {id: 0, text:"Món ăn truyền thống Việt Nam",filename:"traditional-vietnamese-food-title"},
  {id: 1, text:"Phở",filename:"pho(1)"},
  {id: 2, text:"Bún chả",filename:"bbq-noodles"},
  {id: 3, text:"Giò lụa",filename:"vietnamese-pork-sausage"},
  {id: 4, text:"Bún thang",filename:"thang-noodles"},
  {id: 5, text:"Bún bò Huế",filename:"hue3s-beef-noodles"},
  {id: 6, text:"Bún mắm",filename:"fish-sauce-noodles"},
  {id: 7, text:"Bánh xèo",filename:"vietnamese-pancake"},
  {id: 8, text:"Nước mắm",filename:"fish-sauce"},
  {id: 9, text:"Bún riêu cua",filename:"crab-noodles"},
  {id: 10, text:"Xôi",filename:"sticky-rice"},
  {id: 11, text:"Cơm lam",filename:"bamboo-rice"},
  {id: 12, text:"Chả giò",filename:"spring-roll"},
  {id: 13, text:"Cơm tấm",filename:"broken-rice"},
  {id: 14, text:"Gỏi cuốn",filename:"goi-cuon"},
  {id: 15, text:"Bánh chưng",filename:"banh-chung"},
  {id: 16, text:"Cơm tấm",filename:"com-tam"},
];
export const TRADITIONAL_HOLIDAYS: Word[] = [
  {id: 0, text:"Lễ hội truyền thống",filename:"traditional-holidays-title"},
  {id: 1, text:"Tết Nguyên đán",filename:"tet-nguyen-dan"},
  {id: 2, text:"Tết Trung thu",filename:"tet-trung-thu"},
  {id: 3, text:"Tết hàn thực",filename:"tet-han-thuc"},
  {id: 4, text:"Lễ hội chùa Hương",filename:"le-hoi-chua-huong"},
  {id: 5, text:"Giỗ tổ Hùng Vương",filename:"gio-to-hung-vuong"},
  {id: 6, text:"Tết Đoan Ngọ",filename:"tet-doan-ngo"},
];
export const TRANSPORTATION_1: Word[] = [
  {id: 0, text:"Phương Tiện Di Chuyển",filename:"transportation-title"},
  {id: 1, text:"xe hơi",filename:"car"},
  {id: 2, text:"xe buýt",filename:"bus"},
  {id: 3, text:"xe tải",filename:"truck"},
  {id: 4, text:"xe đạp",filename:"bicycle"},
  {id: 5, text:"xe máy",filename:"motocycle"},
  {id: 6, text:"máy bay",filename:"plane"},
  {id: 7, text:"xe lửa",filename:"train"},
  {id: 8, text:"tàu thủy",filename:"ship"},
  {id: 9, text:"trực thăng",filename:"helicopter"},
  {id: 10, text:"thuyền",filename:"boat"},
];
export const HANDICRAFTS: Word[] = [
  {id: 0, text:"Nghề thủ công Việt Nam",filename:"vietnamese-handicrafts-title"},
  {id: 1, text:"Làm nón",filename:"lam-non"},
  {id: 2, text:"Làm mây tre đan",filename:"lam-may-tre-dan"},
  {id: 3, text:"Nghề mộc",filename:"nghe-moc"},
  {id: 4, text:"Làm gốm",filename:"lam-gom"},
  {id: 5, text:"Dệt",filename:"det"},
  {id: 6, text:"Tranh dân gian",filename:"tranh-dan-gian"},
  {id: 7, text:"Dệt chiếu",filename:"det-chieu"},
]
export const WILD_ANIMALS_1: Word[] = [
  {id: 0, text:"Động vật hoang dã",filename:"wild-animals-title"},
  {id: 1, text:"voi",filename:"wild-elephant"},
  {id: 2, text:"hổ",filename:"wild-tiger"},
  {id: 3, text:"cáo",filename:"wild-fox"},
  {id: 4, text:"rắn",filename:"wild-snake"},
  {id: 5, text:"khỉ",filename:"wild-monkey"},
  {id: 6, text:"gấu",filename:"wild-bear"},
  {id: 7, text:"sư tử",filename:"wild-lion"},
  {id: 8, text:"cá sấu",filename:"wild-crocodile"},
  {id: 9, text:"khỉ đột",filename:"wild-gorilla"},
  {id: 10, text:"hươu cao cổ",filename:"wild-giraffe"},
];
export const WILD_ANIMALS_2: Word[] = [
  {id: 0, text:"Động vật hoang dã",filename:"wild-animals-title"},
  {id: 1, text:"dơi",filename:"wild-bat"},
  {id: 2, text:"nai",filename:"wild-deer"},
  {id: 3, text:"báo",filename:"wild-leopard"},
  {id: 4, text:"chó sói",filename:"wild-wolf"},
  {id: 5, text:"gấu bắc cực",filename:"wild-polar-bear"},
  {id: 6, text:"chuột túi",filename:"wild-kangaroo"},
  {id: 7, text:"lạc đà",filename:"wild-camel"},
  {id: 8, text:"gấu trúc",filename:"wild-panda"},
  {id: 9, text:"ngựa vằn",filename:"wild-zebra"},
  {id: 10, text:"tê giác",filename:"wild-rhino"}
];
