/**
 * Created by tovan on 2/20/2017.
 */
import {Word} from '../models/word';
//id 0 là tiêu đề và nội dung chính
//id 0 rất quan trọng sau này sử dụng nó để lấy ra độ dài của từ chung từ đó cắt từ cho phù hợp
//id 1 trở đi là nội dung từng câu
//text là nội dung text sẽ hiển thị lên màn hình, sẽ dùng hàm riêng để cắt text
//file name là tên file dùng option để lấy rõ địa chỉ file
export const WORDS_BEGINNING_WITH_a: Word[] = [
  {id:0,text:"a",filename:"pho-start-a-title"},
  {id:1,text:"a...",filename:"pho-start-a-title"},
  {id:2,text:"an",filename:"pho-start-a-an"},
  {id:3,text:"anh",filename:"pho-start-a-anh"},
  {id:4,text:"ao",filename:"pho-start-a-ao"},
  {id:5,text:"ai",filename:"pho-start-a-ai"},
  {id:6,text:"am",filename:"pho-start-a-am"}
];
export const WORDS_BEGINNING_WITH_a2: Word[] = [
  {id:0,text:"â",filename:"pho-start-a2-title"},
  {id:1,text:"â...",filename:"pho-start-a2-title"},
  {id:2,text:"ân",filename:"pho-start-a2-an2"},
  {id:3,text:"âm",filename:"pho-start-a2-am2"},
  {id:4,text:"âu",filename:"pho-start-a2-au2"},
  {id:5,text:"âng",filename:"pho-start-a2-ang2"}
];

export const WORDS_BEGINNING_WITH_e: Word[] = [
  {id:0,text:"e",filename:"pho-start-e-title"},
  {id:1,text:"e...",filename:"pho-start-e-title"},
  {id:2,text:"em",filename:"pho-start-e-em"},
  {id:3,text:"eo",filename:"pho-start-e-eo"},
  {id:4,text:"en",filename:"pho-start-e-en"},
  {id:5,text:"e",filename:"pho-start-e-e"}
];

export const WORDS_BEGINNING_WITH_e3: Word[] = [
  {id:0,text:"ê",filename:"pho-start-e3-title"},
  {id:1,text:"ê...",filename:"pho-start-e3-title"},
  {id:2,text:"êm",filename:"pho-start-e3-em3"},
  {id:3,text:"ên",filename:"pho-start-e3-en3"},
  {id:4,text:"ênh",filename:"pho-start-e3-enh3"}
];

export const WORDS_BEGINNING_WITH_i: Word[] = [
  {id:0,text:"i",filename:"pho-start-i-title"},
  {id:1,text:"i...",filename:"pho-start-i-title"},
  {id:2,text:"in",filename:"pho-start-i-in"},
  {id:3,text:"inh",filename:"pho-start-i-inh"},
  {id:4,text:"iên",filename:"pho-start-i-ien3"},
  {id:5,text:"ia",filename:"pho-start-i-ia"},
  {id:6,text:"im",filename:"pho-start-i-im"}
];

export const WORDS_BEGINNING_WITH_o: Word[] = [
  {id:0,text:"o",filename:"pho-start-o-title"},
  {id:1,text:"o...",filename:"pho-start-o-title"},
  {id:2,text:"on",filename:"pho-start-o-on"},
  {id:3,text:"ong",filename:"pho-start-o-ong"},
  {id:4,text:"oe",filename:"pho-start-o-oe"},
  {id:5,text:"oa",filename:"pho-start-o-oa"},
  {id:6,text:"oan",filename:"pho-start-o-oan"},
  {id:7,text:"om",filename:"pho-start-o-om"},
  {id:8,text:"oi",filename:"pho-start-o-oi"}
];

export const WORDS_BEGINNING_WITH_o4: Word[] = [
  {id: 0,text:"ôn",filename:"bk-hn-pho-start-o4-on4"},
  {id: 1,text:"ôn",filename:"bk-hn-pho-start-o4-on4"},
  {id: 2,text:"ôm",filename:"bk-hn-pho-start-o4-om4"},
  {id: 3,text:"ôi",filename:"bk-hn-pho-start-o4-oi4"},
  {id: 4,text:"ông",filename:"bk-hn-pho-start-o4-ong4"}
];
export const WORDS_BEGINNING_WITH_o6: Word[] = [
  {id: 0,text:"ơ...",filename:"bk-hn-pho-start-o6-title"},
  {id: 1,text:"ơ...",filename:"bk-hn-pho-start-o6-title"},
  {id: 2,text:"ơi",filename:"bk-hn-pho-start-o6-oi6"},
  {id: 3,text:"ơn",filename:"bk-hn-pho-start-o6-on6"},
  {id: 4,text:"ơm",filename:"bk-hn-pho-start-o6-om6"},
];
export const WORDS_BEGINNING_WITH_u: Word[] = [
  {id: 0,text:"u...",filename:"bk-hn-pho-start-u-title"},
  {id: 1,text:"u...",filename:"bk-hn-pho-start-u-title"},
  {id: 2,text:"uông",filename:"bk-hn-pho-start-u-uong4"},
  {id: 3,text:"ung",filename:"bk-hn-pho-start-u-ung"},
  {id: 4,text:"ua",filename:"bk-hn-pho-start-u-ua"},
  {id: 5,text:"um",filename:"bk-hn-pho-start-u-um"},
  {id: 6,text:"uôm",filename:"bk-hn-pho-start-u-uom4"},
];
export const WORDS_BEGINNING_WITH_u5: Word[] = [
  {id: 0,text:"ư",filename:"bk-hn-pho-start-u5-title"},
  {id: 1,text:"ư...",filename:"bk-hn-pho-start-u5-title"},
  {id: 2,text:"ương",filename:"bk-hn-pho-start-u5-uong56"},
  {id: 3,text:"ưng",filename:"bk-hn-pho-start-u5-ung5"},
  {id: 4,text:"ươn",filename:"bk-hn-pho-start-u5-uon56"},
  {id: 5,text:"ươm",filename:"bk-hn-pho-start-u5-uom56"},
  {id: 6,text:"ưu",filename:"bk-hn-pho-start-u5-uu5"},
  {id: 7,text:"ươm",filename:"bk-hn-pho-start-u5-uom56"},
];
export const WORDS_BEGINNING_WITH_y: Word[] = [
  {id: 0,text:"y",filename:"bk-hn-pho-start-y-title"},
  {id: 1,text:"y...",filename:"bk-hn-pho-start-y-title"},
  {id: 2,text:"yêu",filename:"bk-hn-pho-start-y-yeu3"},
  {id: 3,text:"yên",filename:"bk-hn-pho-start-y-yen3"},
  {id: 4,text:"yêm",filename:"bk-hn-pho-start-y-yem3"},
];
export const WORDS_BEGINNING_WITH_b: Word[] = [
  {id: 0,text:"b",filename:"bk-hn-pho-start-b-title"},
  {id: 1,text:"b...",filename:"bk-hn-pho-start-b-title"},
  {id: 2,text:"ba",filename:"bk-hn-pho-start-b-ba"},
  {id: 3,text:"bác",filename:"bk-hn-pho-start-b-bacs"},
  {id: 4,text:"bé",filename:"bk-hn-pho-start-b-bes"},
  {id: 5,text:"bê",filename:"bk-hn-pho-start-b-be3"},
  {id: 6,text:"bi",filename:"bk-hn-pho-start-b-bi"},
  {id: 7,text:"bô",filename:"bk-hn-pho-start-b-bo4"},
  {id: 8,text:"bò",filename:"bk-hn-pho-start-b-bof"},
  {id: 9,text:"bún",filename:"bk-hn-pho-start-b-buns"},
  {id: 10,text:"bự",filename:"bk-hn-pho-start-b-bu"},
  {id: 11,text:"bế",filename:"bk-hn-pho-start-b-be3s"},
  {id: 12,text:"bàn",filename:"bk-hn-pho-start-b-banf"},
  {id: 13,text:"bình",filename:"bk-hn-pho-start-b-binhf"},
];
export const WORDS_BEGINNING_WITH_c: Word[] = [
  {id: 0,text:"c",filename:"bk-hn-pho-start-c-title"},
  {id: 1,text:"c...",filename:"bk-hn-pho-start-c-title"},
  {id: 2,text:"cá",filename:"bk-hn-pho-start-c-cas"},
  {id: 3,text:"cắt",filename:"bk-hn-pho-start-c-cat1s"},
  {id: 4,text:"cáo",filename:"bk-hn-pho-start-c-caos"},
  {id: 5,text:"cô",filename:"bk-hn-pho-start-c-co4"},
  {id: 6,text:"con",filename:"bk-hn-pho-start-c-con"},
  {id: 7,text:"công",filename:"bk-hn-pho-start-c-cong4"},
  {id: 8,text:"cò",filename:"bk-hn-pho-start-c-cof"},
  {id: 9,text:"cú",filename:"bk-hn-pho-start-c-cus"},
  {id: 10,text:"cún",filename:"bk-hn-pho-start-c-cuns"},
  {id: 11,text:"cùng",filename:"bk-hn-pho-start-c-cungf"},
  {id: 12,text:"cung",filename:"bk-hn-pho-start-c-cung"},
  {id: 13,text:"can",filename:"bk-hn-pho-start-c-can"},
];
export const WORDS_BEGINNING_WITH_d: Word[] = [
  {id: 0, text:"d",filename:"bk-hn-pho-start-d-title"},
  {id: 1, text:"d...",filename:"bk-hn-pho-start-d-title"},
  {id: 2, text:"da",filename:"bk-hn-pho-start-d-da"},
  {id: 3, text:"dành",filename:"bk-hn-pho-start-d-danhf"},
  {id: 4, text:"dần",filename:"bk-hn-pho-start-d-dan2f"},
  {id: 5, text:"dặn",filename:"bk-hn-pho-start-d-dan1j"},
  {id: 6, text:"dai",filename:"bk-hn-pho-start-d-dai"},
  {id: 7, text:"dê",filename:"bk-hn-pho-start-d-de3"},
  {id: 8, text:"dọa",filename:"bk-hn-pho-start-d-doaj"},
  {id: 9, text:"dựng",filename:"bk-hn-pho-start-d-dung5j"},
  {id: 10, text:"dấu",filename:"bk-hn-pho-start-d-dau2s"},
  {id: 11, text:"dính",filename:"bk-hn-pho-start-d-dinhs"},
  {id: 12, text:"do",filename:"bk-hn-pho-start-d-do"},
  {id: 13, text:"dâu",filename:"bk-hn-pho-start-d-dau2"},
];

export const WORDS_BEGINNING_WITH_d7: Word[] = [
  {id: 0, text:"đ",filename:"bk-hn-pho-start-d7-title"},
  {id: 1, text:"đ...",filename:"bk-hn-pho-start-d7-title"},
  {id: 2, text:"đa",filename:"bk-hn-pho-start-d7-title"},
  {id: 3, text:"đá",filename:"bk-hn-pho-start-d7-da7s"},
  {id: 4, text:"đằng",filename:"bk-hn-pho-start-d7-dang71f"},
  {id: 5, text:"đón",filename:"bk-hn-pho-start-d7-don7s"},
  {id: 6, text:"đô",filename:"bk-hn-pho-start-d7-do74"},
  {id: 7, text:"đang",filename:"bk-hn-pho-start-d7-dang7"},
  {id: 8, text:"đông",filename:"bk-hn-pho-start-d7-dong74"},
  {id: 9, text:"đứt",filename:"bk-hn-pho-start-d7-dut75s"},
  {id: 10, text:"đùa",filename:"bk-hn-pho-start-d7-dua7f"},
  {id: 11, text:"đụng",filename:"bk-hn-pho-start-d7-dung7j"},
  {id: 12, text:"đen",filename:"bk-hn-pho-start-d7-den7"},
  {id: 13, text:"đun",filename:"bk-hn-pho-start-d7-dun7"},
  {id: 14, text:"đi",filename:"bk-hn-pho-start-d7-di7"},
  {id: 15, text:"đỏ",filename:"bk-hn-pho-start-d7-do7r"},
  {id: 16, text:"đâu",filename:"bk-hn-pho-start-d7-dau72"},
  {id: 17, text:"đê",filename:"bk-hn-pho-start-d7-de73"},
  {id: 18, text:"đưa",filename:"bk-hn-pho-start-d7-dua75"},
  {id: 19, text:"đau",filename:"bk-hn-pho-start-d7-dau7"},
  {id: 20, text:"đắt",filename:"bk-hn-pho-start-d7-dat17s"},
];
export const WORDS_BEGINNING_WITH_g: Word[] = [
  {id: 0, text:"g",filename:"bk-hn-pho-start-g-title"},
  {id: 1, text:"g...",filename:"bk-hn-pho-start-g-title"},
  {id: 2, text:"gai",filename:"bk-hn-pho-start-g-gai"},
  {id: 3, text:"gần",filename:"bk-hn-pho-start-g-gan2f"},
  {id: 4, text:"gáo",filename:"bk-hn-start-g-gaos"},
  {id: 5, text:"gạch",filename:"bk-hn-start-g-gachj"},
  {id: 6, text:"găm",filename:"bk-hn-start-g-gam1"},
  {id: 7, text:"gõ",filename:"bk-hn-start-g-gox"},
  {id: 8, text:"gói",filename:"bk-hn-start-g-gois"},
  {id: 9, text:"gối",filename:"bk-hn-start-g-goi4s"},
  {id: 10, text:"gồng",filename:"bk-hn-start-g-gong4f"},
  {id: 11, text:"gừng",filename:"bk-hn-start-g-gung5f"},
  {id: 12, text:"gan",filename:"bk-hn-pho-start-g-gan"},
  {id: 13, text:"gang",filename:"bk-hn-pho-start-g-gang"},
  {id: 14, text:"gu",filename:"bk-hn-pho-start-g-gu"},
];
export const WORDS_BEGINNING_WITH_h: Word[] = [
  {id: 0, text:"h",filename:"bk-hn-pho-start-h-title"},
  {id: 1, text:"h...",filename:"bk-hn-pho-start-h-title"},
  {id: 2, text:"ha",filename:"bk-hn-pho-start-h-ha"},
  {id: 3, text:"hai",filename:"bk-hn-pho-start-h-hai"},
  {id: 4, text:"hãy",filename:"bk-hn-pho-start-h-hayx"},
  {id: 5, text:"hấp",filename:"bk-hn-pho-start-h-hap2s"},
  {id: 6, text:"hẹ",filename:"bk-hn-pho-start-h-hej"},
  {id: 7, text:"hến",filename:"bk-hn-pho-start-h-hen3s"},
  {id: 8, text:"hong",filename:"bk-hn-pho-start-h-hong"},
  {id: 9, text:"hôn",filename:"bk-hn-pho-start-h-hon4"},
  {id: 10, text:"hơn",filename:"bk-hn-pho-start-h-hon6"},
  {id: 11, text:"húng",filename:"bk-hn-pho-start-h-hungs"},
  {id: 12, text:"hát",filename:"bk-hn-pho-start-h-hats"},
  {id: 13, text:"họ",filename:"bk-hn-pho-start-h-hoj"},
  {id: 14, text:"hết",filename:"bk-hn-pho-start-h-het3s"},
  {id: 15, text:"hóng",filename:"bk-hn-pho-start-h-hongs"},
  {id: 16, text:"hả",filename:"bk-hn-pho-start-h-har"},
  {id: 17, text:"hé",filename:"bk-hn-pho-start-h-hes"},
];
export const WORDS_BEGINNING_WITH_k: Word[] = [
  {id: 0, text:"k",filename:"bk-hn-pho-start-k-title"},
  {id: 1, text:"k...",filename:"bk-hn-pho-start-k-title"},
  {id: 2, text:"kẻ",filename:"bk-hn-pho-start-k-ker"},
  {id: 3, text:"keng",filename:"bk-hn-pho-start-k-keng"},
  {id: 4, text:"kéo",filename:"bk-hn-pho-start-k-keos"},
  {id: 5, text:"kẹo",filename:"bk-hn-pho-start-k-keoj"},
  {id: 6, text:"kênh",filename:"bk-hn-pho-start-k-kenh3"},
  {id: 7, text:"kiệu",filename:"bk-hn-pho-start-k-kieu3j"},
  {id: 8, text:"kiến",filename:"bk-hn-pho-start-k-kien3s"},
  {id: 9, text:"kiêng",filename:"bk-hn-pho-start-k-kieng"},
  {id: 10, text:"kiếp",filename:"bk-hn-pho-start-k-kiep3s"},
  {id: 11, text:"kên",filename:"bk-hn-pho-start-k-ken3"},
  {id: 12, text:"kiến",filename:"bk-hn-pho-start-k-kien3s"},
  {id: 13, text:"kín",filename:"bk-hn-pho-start-k-kins"},
  {id: 14, text:"kim",filename:"bk-hn-pho-start-k-kim"},
];
export const WORDS_BEGINNING_WITH_l: Word[] = [
  {id: 0, text:"l",filename:"bk-hn-pho-start-l-title"},
  {id: 1, text:"l...",filename:"bk-hn-pho-start-l-title"},
  {id: 2, text:"la",filename:"bk-hn-pho-start-l-la"},
  {id: 3, text:"lá",filename:"bk-hn-start-l-las"},
  {id: 4, text:"lang",filename:"bk-hn-pho-start-l-lang"},
  {id: 5, text:"lạng",filename:"bk-hn-pho-start-l-langj"},
  {id: 6, text:"lách",filename:"bk-hn-pho-start-l-lachs"},
  {id: 7, text:"lắc",filename:"bk-hn-pho-start-l-lac1s"},
  {id: 8, text:"lê",filename:"bk-hn-pho-start-l-le3"},
  {id: 9, text:"ly",filename:"bk-hn-pho-start-l-ly"},
  {id: 10, text:"linh",filename:"bk-hn-pho-start-l-linh"},
  {id: 11, text:"lu",filename:"bk-hn-pho-start-l-lu"},
  {id: 12, text:"lo",filename:"bk-hn-pho-start-l-lo"},
  {id: 13, text:"ló",filename:"bk-hn-pho-start-l-los"},
  {id: 14, text:"la",filename:"bk-hn-pho-start-l-la"},
  {id: 15, text:"len",filename:"bk-hn-pho-start-l-len"},
  {id: 16, text:"lan",filename:"bk-hn-pho-start-l-lan"},
];
export const WORDS_BEGINNING_WITH_m: Word[] = [
  {id: 0, text:"m",filename:"bk-hn-pho-start-m-title"},
  {id: 1, text:"m...",filename:"bk-hn-pho-start-m-title"},
  {id: 2, text:"mẹ",filename:"bk-hn-pho-start-m-mej"},
  {id: 3, text:"mình",filename:"bk-hn-pho-start-m-minhf"},
  {id: 4, text:"măm",filename:"bk-hn-pho-start-m-mam1"},
  {id: 5, text:"men",filename:"bk-hn-pho-start-m-men"},
  {id: 6, text:"mê",filename:"bk-hn-pho-start-m-me3"},
  {id: 7, text:"mụ",filename:"bk-hn-pho-start-m-muj"},
  {id: 8, text:"mừng",filename:"bk-hn-pho-start-m-mung5f"},
  {id: 9, text:"mong",filename:"bk-hn-pho-start-m-mong"},
  {id: 10, text:"móng",filename:"bk-hn-pho-start-m-mongs"},
  {id: 11, text:"mền",filename:"bk-hn-pho-start-m-men3f"},
  {id: 12, text:"màn",filename:"bk-hn-pho-start-m-manf"},
  {id: 13, text:"mo",filename:"bk-hn-pho-start-m-mo"},
];
export const WORDS_BEGINNING_WITH_n: Word[] = [
  {id: 0, text:"n",filename:"bk-hn-pho-start-n-title"},
  {id: 1, text:"n...",filename:"bk-hn-pho-start-n-title"},
  {id: 2, text:"na",filename:"bk-hn-pho-start-n-na"},
  {id: 3, text:"ná",filename:"bk-hn-pho-start-n-nas"},
  {id: 4, text:"nâng",filename:"bk-hn-pho-start-n-nang2"},
  {id: 5, text:"nè",filename:"bk-hn-pho-start-n-nef"},
  {id: 6, text:"nó",filename:"bk-hn-pho-start-n-nos"},
  {id: 7, text:"nong",filename:"bk-hn-pho-start-n-nong"},
  {id: 8, text:"nưa",filename:"bk-hn-pho-start-n-nua5"},
  {id: 9, text:"niễng",filename:"bk-hn-pho-start-n-nieng3x"},
  {id: 10, text:"núng",filename:"bk-hn-pho-start-n-nungs"},
  {id: 11, text:"nứt",filename:"bk-hn-pho-start-n-nut5s"},
  {id: 12, text:"nứa",filename:"bk-hn-pho-start-n-nua5s"},
  {id: 13, text:"no",filename:"bk-hn-pho-start-n-no"},
  {id: 14, text:"nơ",filename:"bk-hn-pho-start-n-no6"},
  {id: 15, text:"nan",filename:"bk-hn-pho-start-n-nan"},
  {id: 16, text:"nên",filename:"bk-hn-pho-start-n-nen3"},
  {id: 17, text:"nín",filename:"bk-hn-pho-start-n-nins"},
  {id: 18, text:"ném",filename:"bk-hn-pho-start-n-nems"},
  {id: 19, text:"nóng",filename:"bk-hn-pho-start-n-nongs"},
];
export const WORDS_BEGINNING_WITH_ph: Word[] = [
  {id: 0, text:"ph",filename:"bk-hn-pho-start-ph-title"},
  {id: 1, text:"ph...",filename:"bk-hn-pho-start-ph-title"},
  {id: 2, text:"pha",filename:"bk-hn-pho-start-ph-pha"},
  {id: 3, text:"phá",filename:"bk-hn-pho-start-ph-phas"},
  {id: 4, text:"phinh",filename:"bk-hn-pho-start-ph-phinh"},
  {id: 5, text:"phóng",filename:"bk-hn-pho-start-ph-phongs"},
  {id: 6, text:"phố",filename:"bk-hn-pho-start-ph-pho4s"},
  {id: 7, text:"phụ",filename:"bk-hn-pho-start-ph-phuj"},
  {id: 8, text:"phở",filename:"bk-hn-pho-start-ph-pho6r"},
  {id: 9, text:"phê",filename:"bk-hn-pho-start-ph-phe3"},
  {id: 10, text:"phư",filename:"bk-hn-pho-start-ph-phu5"},
  {id: 11, text:"phụ",filename:"bk-hn-pho-start-ph-phuj"},
  {id: 12, text:"phi",filename:"bk-hn-pho-start-ph-phi"},
  {id: 13, text:"phe",filename:"bk-hn-pho-start-ph-phe"},
  {id: 14, text:"pha",filename:"bk-hn-pho-start-ph-pha"},
  {id: 15, text:"phin",filename:"bk-hn-pho-start-ph-phin"},
  {id: 16, text:"phen",filename:"bk-hn-pho-start-ph-phen"},
  {id: 17, text:"phà",filename:"bk-hn-pho-start-ph-phaf"},
  {id: 18, text:"phú",filename:"bk-hn-pho-start-ph-phus"},
];
export const WORDS_BEGINNING_WITH_gi: Word[] = [
  {id: 0, text:"gi",filename:"bk-hn-pho-start-gi-title"},
  {id: 1, text:"gi...",filename:"bk-hn-pho-start-gi-title"},
  {id: 2, text:"gia",filename:"bk-hn-pho-start-gi-gia"},
  {id: 3, text:"giá",filename:"bk-hn-pho-start-gi-gias"},
  {id: 4, text:"già",filename:"bk-hn-pho-start-gi-giaf"},
  {id: 5, text:"giật",filename:"bk-hn-pho-start-gi-giat2j"},
  {id: 6, text:"gieo",filename:"bk-hn-pho-start-gi-gieo"},
  {id: 7, text:"giông",filename:"bk-hn-pho-start-gi-giong4"},
  {id: 8, text:"giống",filename:"bk-hn-pho-start-gi-giong4s"},
  {id: 9, text:"giữ",filename:"bk-hn-pho-start-gi-giu5x"},
  {id: 10, text:"giời",filename:"bk-hn-pho-start-gi-gioi6f"},
  {id: 11, text:"giang",filename:"bk-hn-pho-start-gi-giang"},
  {id: 12, text:"giếng",filename:"bk-hn-pho-start-gi-gieng3s"},
  {id: 13, text:"giơ",filename:"bk-hn-pho-start-gi-gio6"},
  {id: 14, text:"giăng",filename:"bk-hn-pho-start-gi-giang1"},
  {id: 15, text:"giả",filename:"bk-hn-pho-start-gi-giar"},
];
export const WORDS_BEGINNING_WITH_r: Word[] = [
  {id: 0, text:"r",filename:"bk-hn-pho-start-r-title"},
  {id: 1, text:"r...",filename:"bk-hn-pho-start-r-title"},
  {id: 2, text:"ra",filename:"bk-hn-pho-start-r-ra"},
  {id: 3, text:"rá",filename:"bk-hn-pho-start-r-ras"},
  {id: 4, text:"rê",filename:"bk-hn-pho-start-r-re3"},
  {id: 5, text:"ren",filename:"bk-hn-pho-start-r-ren"},
  {id: 6, text:"rổ",filename:"bk-hn-pho-start-r-ro4r"},
  {id: 7, text:"rộng",filename:"bk-hn-pho-start-r-rong4j"},
  {id: 8, text:"rau",filename:"bk-hn-pho-start-r-rau"},
  {id: 9, text:"rác",filename:"bk-hn-pho-start-r-racs"},
  {id: 10, text:"rung",filename:"bk-hn-pho-start-r-rung"},
  {id: 11, text:"rụng",filename:"bk-hn-pho-start-r-rungj"},
  {id: 12, text:"rẽ",filename:"bk-hn-pho-start-r-rex"},
];
export const WORDS_BEGINNING_WITH_s: Word[] = [
  {id: 0, text:"s",filename:"bk-hn-pho-start-s-title"},
  {id: 1, text:"s...",filename:"bk-hn-pho-start-s-title"},
  {id: 2, text:"sa",filename:"bk-hn-pho-start-s-sa"},
  {id: 3, text:"sắn",filename:"bk-hn-pho-start-s-san1s"},
  {id: 4, text:"sang",filename:"bk-hn-pho-start-s-sang"},
  {id: 5, text:"sáng",filename:"bk-hn-pho-start-s-sangs"},
  {id: 6, text:"sen",filename:"bk-hn-pho-start-s-sen"},
  {id: 7, text:"sên",filename:"bk-hn-pho-start-s-sen3"},
  {id: 8, text:"su",filename:"bk-hn-pho-start-s-su"},
  {id: 9, text:"sữa",filename:"bk-hn-pho-start-s-sua5x"},
  {id: 10, text:"sướng",filename:"bk-hn-pho-start-s-suong56s"},
  {id: 11, text:"son",filename:"bk-hn-pho-start-s-son"},
  {id: 12, text:"sau",filename:"bk-hn-pho-start-s-sau"},
  {id: 13, text:"sợ",filename:"bk-hn-pho-start-s-so6j"},
  {id: 14, text:"sẽ",filename:"bk-hn-pho-start-s-sex"},
  {id: 15, text:"song",filename:"bk-hn-pho-start-s-song"},
  {id: 16, text:"sống",filename:"bk-hn-pho-start-s-song4s"},
  {id: 17, text:"sứa",filename:"bk-hn-pho-start-s-sua5s"},
  {id: 18, text:"sinh",filename:"bk-hn-pho-start-s-sinh"},
  {id: 19, text:"sấu",filename:"bk-hn-pho-start-s-sau2s"},
];
export const WORDS_BEGINNING_WITH_t: Word[] = [
  {id: 0, text:"t",filename:"bk-hn-pho-start-t-title"},
  {id: 1, text:"t...",filename:"bk-hn-pho-start-t-title"},
  {id: 2, text:"ta",filename:"bk-hn-pho-start-t-ta"},
  {id: 3, text:"tá",filename:"bk-hn-pho-start-t-tas"},
  {id: 4, text:"tăm",filename:"bk-hn-pho-start-t-tam1"},
  {id: 5, text:"tân",filename:"bk-hn-pho-start-t-tan2"},
  {id: 6, text:"tên",filename:"bk-hn-pho-start-t-ten3"},
  {id: 7, text:"tí",filename:"bk-hn-pho-start-t-tis"},
  {id: 8, text:"tính",filename:"bk-hn-pho-start-t-tinhs"},
  {id: 9, text:"toán",filename:"bk-hn-pho-start-t-toans"},
  {id: 10, text:"tổng",filename:"bk-hn-pho-start-t-tong4r"},
  {id: 11, text:"tiên",filename:"bk-hn-pho-start-t-tien3"},
  {id: 12, text:"to",filename:"bk-hn-pho-start-t-to"},
  {id: 13, text:"tin",filename:"bk-hn-pho-start-t-tin"},
  {id: 14, text:"tem",filename:"bk-hn-pho-start-t-tem"},
  {id: 15, text:"tốn",filename:"bk-hn-pho-start-t-ton4s"},
];
export const WORDS_BEGINNING_WITH_v: Word[] = [
  {id: 0, text:"v",filename:"bk-hn-pho-start-v-title"},
  {id: 1, text:"v...",filename:"bk-hn-pho-start-v-title"},
  {id: 2, text:"va",filename:"bk-hn-pho-start-v-va"},
  {id: 3, text:"vá",filename:"bk-hn-pho-start-v-vas"},
  {id: 4, text:"vâng",filename:"bk-hn-pho-start-v-vang2"},
  {id: 5, text:"vắng",filename:"bk-hn-pho-start-v-vang1s"},
  {id: 6, text:"vo",filename:"bk-hn-pho-start-v-vo"},
  {id: 7, text:"vồ",filename:"bk-hn-pho-start-v-vo4f"},
  {id: 8, text:"vớ",filename:"bk-hn-pho-start-v-vo6s"},
  {id: 9, text:"về",filename:"bk-hn-pho-start-v-ve3f"},
  {id: 10, text:"vịnh",filename:"bk-hn-pho-start-v-vinhj"},
  {id: 11, text:"vàng",filename:"bk-hn-pho-start-v-vangf"},
  {id: 12, text:"ve",filename:"bk-hn-pho-start-v-ve"},
  {id: 13, text:"vào",filename:"bk-hn-pho-start-v-vaof"},
  {id: 14, text:"vịn",filename:"bk-hn-pho-start-v-vinj"},
  {id: 15, text:"vang",filename:"bk-hn-pho-start-v-vang"},
  {id: 16, text:"ven",filename:"bk-hn-pho-start-v-ven"},
];
export const WORDS_BEGINNING_WITH_x: Word[] = [
  {id: 0, text:"x",filename:"bk-hn-pho-start-x-title"},
  {id: 1, text:"x...",filename:"bk-hn-pho-start-x-title"},
  {id: 2, text:"xa",filename:"bk-hn-pho-start-x-xa"},
  {id: 3, text:"xăm",filename:"bk-hn-pho-start-x-xam1"},
  {id: 4, text:"xấc",filename:"bk-hn-pho-start-x-xac2s"},
  {id: 5, text:"xem",filename:"bk-hn-pho-start-x-xem"},
  {id: 6, text:"xôi",filename:"bk-hn-pho-start-x-xoi4"},
  {id: 7, text:"xiềng",filename:"bk-hn-pho-start-x-xieng3f"},
  {id: 8, text:"xong",filename:"bk-hn-pho-start-x-xong"},
  {id: 9, text:"xóm",filename:"bk-hn-pho-start-x-xoms"},
  {id: 10, text:"xơi",filename:"bk-hn-pho-start-x-xoi6"},
  {id: 11, text:"xui",filename:"bk-hn-pho-start-x-xui"},
  {id: 12, text:"xông",filename:"bk-hn-pho-start-x-xong4"},
  {id: 13, text:"xô",filename:"bk-hn-pho-start-x-xo4"},
  {id: 14, text:"xé",filename:"bk-hn-pho-start-x-xes"},
  {id: 15, text:"xó",filename:"bk-hn-pho-start-x-xos"},
  {id: 16, text:"xăng",filename:"bk-hn-pho-start-x-xang1"}
];
export const WORDS_BEGINNING_WITH_ch: Word[] = [
  {id: 0, text:"ch",filename:"bk-hn-pho-start-ch-title"},
  {id: 1, text:"ch...",filename:"bk-hn-pho-start-ch-title"},
  {id: 2, text:"cha",filename:"bk-hn-pho-start-ch-cha"},
  {id: 3, text:"chả",filename:"bk-hn-pho-start-ch-char"},
  {id: 4, text:"chó",filename:"bk-hn-pho-start-ch-chos"},
  {id: 5, text:"chim",filename:"bk-hn-pho-start-ch-chim"},
  {id: 6, text:"chiều",filename:"bk-hn-pho-start-ch-chieu3f"},
  {id: 7, text:"chờ",filename:"bk-hn-pho-start-ch-cho6f"},
  {id: 8, text:"chú",filename:"bk-hn-pho-start-ch-chus"},
  {id: 9, text:"chung",filename:"bk-hn-pho-start-ch-chung"},
  {id: 10, text:"chân",filename:"bk-hn-pho-start-ch-chan2"},
  {id: 11, text:"chính",filename:"bk-hn-pho-start-ch-chinhs"},
  {id: 12, text:"chó",filename:"bk-hn-pho-start-ch-chos"},
  {id: 13, text:"chín",filename:"bk-hn-pho-start-ch-chins"},
  {id: 14, text:"che",filename:"bk-hn-pho-start-ch-che"},
  {id: 15, text:"chê",filename:"bk-hn-pho-start-ch-che3"},
  {id: 16, text:"chị",filename:"bk-hn-pho-start-ch-chij"},
];
export const WORDS_BEGINNING_WITH_kh: Word[] = [
  {id: 0, text:"kh",filename:"bk-hn-pho-start-kh-title"},
  {id: 1, text:"kh...",filename:"bk-hn-pho-start-kh-title"},
  {id: 2, text:"kha",filename:"bk-hn-pho-start-kh-kha"},
  {id: 3, text:"khăn",filename:"bk-hn-pho-start-kh-khan1"},
  {id: 4, text:"không",filename:"bk-hn-pho-start-kh-khong4"},
  {id: 5, text:"khiêng",filename:"bk-hn-pho-start-kh-khieng3"},
  {id: 6, text:"khang",filename:"bk-hn-pho-start-kh-khang"},
  {id: 7, text:"khất",filename:"bk-hn-pho-start-kh-khat2s"},
  {id: 8, text:"kheo",filename:"bk-hn-pho-start-kh-kheo"},
  {id: 9, text:"khô",filename:"bk-hn-pho-start-kh-kho4"},
  {id: 10, text:"khương",filename:"bk-hn-pho-start-kh-khuong56"},
  {id: 11, text:"khá",filename:"bk-hn-pho-start-kh-khas"},
  {id: 12, text:"kho",filename:"bk-hn-pho-start-kh-kho"},
  {id: 13, text:"khéo",filename:"bk-hn-pho-start-kh-kheos"},
  {id: 14, text:"khí",filename:"bk-hn-pho-start-kh-khis"},
  {id: 15, text:"khỏe",filename:"bk-hn-pho-start-kh-khoer"},
  {id: 16, text:"khi",filename:"bk-hn-pho-start-kh-khi"},
  {id: 17, text:"khẽ",filename:"bk-hn-pho-start-kh-khex"},
];
export const WORDS_BEGINNING_WITH_ng: Word[] = [
  {id: 0, text:"ng",filename:"bk-hn-pho-start-ng-title"},
  {id: 1, text:"ng...",filename:"bk-hn-pho-start-ng-title"},
  {id: 2, text:"nga",filename:"bk-hn-pho-start-ng-nga"},
  {id: 3, text:"ngác",filename:"bk-hn-pho-start-ng-ngacs"},
  {id: 4, text:"ngu",filename:"bk-hn-pho-start-ng-ngu"},
  {id: 5, text:"ngơ",filename:"bk-hn-pho-start-ng-ngo6"},
  {id: 6, text:"ngang",filename:"bk-hn-pho-start-ng-ngang"},
  {id: 7, text:"ngóng",filename:"bk-hn-pho-start-ng-ngongs"},
  {id: 8, text:"ngăm",filename:"bk-hn-pho-start-ng-ngam1"},
  {id: 9, text:"ngấm",filename:"bk-hn-pho-start-ng-ngam2s"},
  {id: 10, text:"ngầm",filename:"bk-hn-pho-start-ng-ngam2f"},
  {id: 11, text:"ngan",filename:"bk-hn-pho-start-ng-ngan"},
  {id: 12, text:"ngã",filename:"bk-hn-pho-start-ng-ngax"},
  {id: 13, text:"ngả",filename:"bk-hn-pho-start-ng-ngar"},
  {id: 14, text:"ngủ",filename:"bk-hn-pho-start-ng-ngur"},
  {id: 15, text:"ngâm",filename:"bk-hn-pho-start-ng-ngam2"},
  {id: 16, text:"nghi",filename:"bk-hn-pho-start-ngh-nghi"},
];
export const WORDS_BEGINNING_WITH_ngh: Word[] = [
  {id: 0, text:"ngh",filename:"bk-hn-pho-start-ngh-title"},
  {id: 1, text:"ngh...",filename:"bk-hn-pho-start-ngh-title"},
  {id: 2, text:"nghe",filename:"bk-hn-pho-start-ngh-nghe"},
  {id: 3, text:"nghé",filename:"bk-hn-pho-start-ngh-nghes"},
  {id: 4, text:"nghê",filename:"bk-hn-pho-start-ngh-nghe3"},
  {id: 5, text:"nghênh",filename:"bk-hn-pho-start-ngh-nghenh3"},
  {id: 6, text:"nghiêng",filename:"bk-hn-pho-start-ngh-nghieng3"},
  {id: 7, text:"nghiệp",filename:"bk-hn-pho-start-ngh-nghiep3j"},
  {id: 8, text:"nghiền",filename:"bk-hn-pho-start-ngh-nghien3f"},
  {id: 9, text:"nghểnh",filename:"bk-hn-pho-start-ngh-nghenh3r"},
  {id: 10, text:"nghen",filename:"bk-hn-pho-start-ngh-nghen"},
  {id: 11, text:"nghén",filename:"bk-hn-pho-start-ngh-nghens"},
  {id: 12, text:"nghề",filename:"bk-hn-pho-start-ngh-nghe3f"},
  {id: 13, text:"nghê",filename:"bk-hn-pho-start-ngh-nghe3"},
  {id: 14, text:"nghỉ",filename:"bk-hn-pho-start-ngh-nghir"},
  {id: 15, text:"nghi",filename:"bk-hn-pho-start-ngh-nghi"},
];
export const WORDS_BEGINNING_WITH_nh: Word[] = [
  {id: 0, text:"nh",filename:"bk-hn-pho-start-nh-title"},
  {id: 1, text:"nh...",filename:"bk-hn-pho-start-nh-title"},
  {id: 2, text:"nha",filename:"bk-hn-pho-start-nh-nha"},
  {id: 3, text:"nhân",filename:"bk-hn-pho-start-nh-nhan2"},
  {id: 4, text:"nhé",filename:"bk-hn-pho-start-nh-nhes"},
  {id: 5, text:"nhện",filename:"bk-hn-pho-start-nh-nhen3j"},
  {id: 6, text:"như",filename:"bk-hn-pho-start-nh-nhu5"},
  {id: 7, text:"nhưng",filename:"bk-hn-pho-start-nh-nhung5"},
  {id: 8, text:"nhô",filename:"bk-hn-pho-start-nh-nho4"},
  {id: 9, text:"nhộng",filename:"bk-hn-pho-start-nh-nhong4j"},
  {id: 10, text:"nhàn",filename:"bk-hn-pho-start-nh-nhanf"},
  {id: 11, text:"nhìn",filename:"bk-hn-pho-start-nh-nhinf"},
  {id: 12, text:"nhổ",filename:"bk-hn-pho-start-nh-nho4r"},
  {id: 13, text:"nhỉ",filename:"bk-hn-pho-start-nh-nhir"},
];
export const WORDS_BEGINNING_WITH_th: Word[] = [
  {id: 0, text:"th",filename:"bk-hn-pho-start-th-title"},
  {id: 1, text:"th...",filename:"bk-hn-pho-start-th-title"},
  {id: 2, text:"tha",filename:"bk-hn-pho-start-th-tha"},
  {id: 3, text:"than",filename:"bk-hn-pho-start-th-than"},
  {id: 4, text:"thang",filename:"bk-hn-pho-start-th-thang"},
  {id: 5, text:"thân",filename:"bk-hn-pho-start-th-than2"},
  {id: 6, text:"thắt",filename:"bk-hn-pho-start-th-that1s"},
  {id: 7, text:"thêm",filename:"bk-hn-pho-start-th-them3"},
  {id: 8, text:"thênh",filename:"bk-hn-pho-start-th-thenh3"},
  {id: 9, text:"thùng",filename:"bk-hn-pho-start-th-thungf"},
  {id: 10, text:"thụ",filename:"bk-hn-pho-start-th-thuj"},
  {id: 11, text:"thơ",filename:"bk-hn-pho-start-th-tho6"},
  {id: 12, text:"thế",filename:"bk-hn-pho-start-th-the3s"},
  {id: 13, text:"thi",filename:"bk-hn-pho-start-th-thi"},
  {id: 14, text:"thu",filename:"bk-hn-pho-start-th-thu"},
  {id: 15, text:"thư",filename:"bk-hn-pho-start-th-thu5"},
  {id: 16, text:"thả",filename:"bk-hn-pho-start-th-thar"},
];
export const WORDS_BEGINNING_WITH_tr: Word[] = [
  {id: 0, text:"tr",filename:"bk-hn-pho-start-tr-title"},
  {id: 1, text:"tr...",filename:"bk-hn-pho-start-tr-title"},
  {id: 2, text:"tra",filename:"bk-hn-pho-start-tr-tra"},
  {id: 3, text:"tre",filename:"bk-hn-pho-start-tr-tre"},
  {id: 4, text:"trúc",filename:"bk-hn-pho-start-tr-trucs"},
  {id: 5, text:"trên",filename:"bk-hn-pho-start-tr-tren3"},
  {id: 6, text:"trong",filename:"bk-hn-pho-start-tr-trong"},
  {id: 7, text:"trăng",filename:"bk-hn-pho-start-tr-trang1"},
  {id: 8, text:"trống",filename:"bk-hn-pho-start-tr-trong4s"},
  {id: 9, text:"triền",filename:"bk-hn-pho-start-tr-trien3f"},
  {id: 10, text:"trần",filename:"bk-hn-pho-start-tr-tran2f"},
  {id: 11, text:"trơn",filename:"bk-hn-pho-start-tr-tron6"},
  {id: 12, text:"trẻ",filename:"bk-hn-pho-start-tr-trer"},
  {id: 13, text:"trả",filename:"bk-hn-pho-start-tr-trar"},
  {id: 14, text:"tròn",filename:"bk-hn-pho-start-tr-tronf"},
  {id: 15, text:"tràn",filename:"bk-hn-pho-start-tr-tranf"},
];
export const WORDS_BEGINNING_WITH_q: Word[] = [
  {id: 0, text:"q",filename:"bk-hn-pho-start-q-title"},
  {id: 1, text:"q...",filename:"bk-hn-pho-start-q-title"},
  {id: 2, text:"qua",filename:"bk-hn-pho-start-q-qua"},
  {id: 3, text:"quạ",filename:"bk-hn-pho-start-q-quaj"},
  {id: 4, text:"quần",filename:"bk-hn-pho-start-q-quan2f"},
  {id: 5, text:"quen",filename:"bk-hn-pho-start-q-quen"},
  {id: 6, text:"quên",filename:"bk-hn-pho-start-q-quen3"},
  {id: 7, text:"quân",filename:"bk-hn-pho-start-q-quan2"},
  {id: 8, text:"quay",filename:"bk-hn-pho-start-q-quay"},
  {id: 9, text:"quẹo",filename:"bk-hn-pho-start-q-queoj"},
  {id: 10, text:"quang",filename:"bk-hn-pho-start-q-quang"},
  {id: 11, text:"quác",filename:"bk-hn-pho-start-q-quacs"},
  {id: 12, text:"quê",filename:"bk-hn-pho-start-qu-que3"},
  {id: 13, text:"quế",filename:"bk-hn-pho-start-qu-que3s"},
  {id: 14, text:"quả",filename:"bk-hn-pho-start-qu-quar"},
  {id: 15, text:"quá",filename:"bk-hn-pho-start-qu-quas"},
];




