/**
 * Created by tovan on 2/20/2017.
 */
import {Word} from '../models/word';
export const SIGHT_WORDS_1: Word[] = [
  {id:1,text:"ạ",filename:"sight-words-aj"},
  {id:2,text:"ai",filename:"sight-words-ai"},
  {id:3,text:"ăn",filename:"sight-words-an1"},
  {id:4,text:"anh",filename:"sight-words-anh"},
  {id:5,text:"áo",filename:"sight-words-aos"},
  {id:6,text:"ấy",filename:"sight-words-ay2s"},
  {id:7,text:"ấm",filename:"sight-words-am2s"},
  {id:8,text:"ba",filename:"sight-words-ba"},
  {id:9,text:"bà",filename:"sight-words-baf"},
  {id:10,text:"bay",filename:"sight-words-bay"}
];
export const SIGHT_WORDS_2: Word[] = [
  {id:1,text:"bố",filename:"sight-words-bo4s"},
  {id:2,text:"bốn",filename:"sight-words-bon4s"},
  {id:3,text:"bạn",filename:"sight-words-banj"},
  {id:4,text:"bị",filename:"sight-words-bij"},
  {id:5,text:"bé",filename:"sight-words-bes"},
  {id:6,text:"bơi",filename:"sight-words-boi6"},
  {id:7,text:"bò",filename:"sight-words-bof"},
  {id:8,text:"biết",filename:"sight-words-biet3s"},
  {id:9,text:"buổi",filename:"sight-words-buoi4r"},
  {id:10,text:"biển",filename:"sight-words-bien3r"}
];
export const SIGHT_WORDS_3: Word[] = [
  {id:1,text:"cá",filename:"sight-words-cas"},
  {id:2,text:"cà",filename:"sight-words-caf"},
  {id:3,text:"cái",filename:"sight-words-cais"},
  {id:4,text:"con",filename:"sight-words-con"},
  {id:5,text:"có",filename:"sight-words-cos"},
  {id:6,text:"cô",filename:"sight-words-co4"},
  {id:7,text:"cỏ",filename:"sight-words-cor"},
  {id:8,text:"cam",filename:"sight-words-cam"},
  {id:9,text:"cua",filename:"sight-words-cua"},
  {id:10,text:"cũng",filename:"sight-words-cungx"},
  {id:11,text:"cây",filename:"sight-words-cay2"}
];
export const SIGHT_WORDS_4: Word[] = [
  {id:1,text:"của",filename:"sight-words-cuar"},
  {id:2,text:"cắt",filename:"sight-words-cat1s"},
  {id:3,text:"cũ",filename:"sight-words-cux"},
  {id:4,text:"chờ",filename:"sight-words-cho6f"},
  {id:5,text:"chơi",filename:"sight-words-choi6"},
  {id:6,text:"chị",filename:"sight-words-chij"},
  {id:7,text:"cho",filename:"sight-words-cho"},
  {id:8,text:"chó",filename:"sight-words-chos"},
  {id:9,text:"chưa",filename:"sight-words-chua5"},
  {id:10,text:"chuối",filename:"sight-words-chuoi4s"}
];
export const SIGHT_WORDS_5: Word[] = [
  {id: 0, text:"chạy",filename:"bk-hn-sight-words-chayj"},
  {id: 1, text:"chân",filename:"bk-hn-sight-words-chan2"},
  {id: 2, text:"chậm",filename:"bk-hn-sight-words-cham2j"},
  {id: 3, text:"chim",filename:"bk-hn-sight-words-chim"},
  {id: 4, text:"chuột",filename:"bk-hn-sight-words-chuot4j"},
  {id: 5, text:"chú",filename:"bk-hn-sight-words-chus"},
  {id: 6, text:"dạ",filename:"bk-hn-sight-words-daj"},
  {id: 7, text:"dây",filename:"bk-hn-sight-words-day2"},
  {id: 8, text:"dạy",filename:"bk-hn-sight-words-dayj"},
];
export const SIGHT_WORDS_6: Word[] = [
  {id: 0, text:"dặn",filename:"bk-hn-sight-words-dan1j"},
  {id: 1, text:"dọn",filename:"bk-hn-sight-words-donj"},
  {id: 2, text:"dài",filename:"bk-hn-sight-words-daif"},
  {id: 3, text:"dừng",filename:"bk-hn-sight-words-dung5f"},
  {id: 4, text:"dưới",filename:"bk-hn-sight-words-duoi56s"},
  {id: 5, text:"đi",filename:"bk-hn-sight-words-di7"},
  {id: 6, text:"đau",filename:"bk-hn-sight-words-dau7"},
  {id: 7, text:"đây",filename:"bk-hn-sight-words-day72"},
  {id: 8, text:"đâu",filename:"bk-hn-sight-words-dau72"},
  {id: 9, text:"đồi",filename:"bk-hn-sight-words-doi74f"},
  {id: 10, text:"đưa",filename:"bk-hn-sight-words-dua75"},
  {id: 11, text:"đừng",filename:"bk-hn-sight-words-dung75f"},
  {id: 12, text:"đấy",filename:"bk-hn-sight-words-day72s"},
];
export const SIGHT_WORDS_7: Word[] = [
  {id: 0, text:"đã",filename:"bk-hn-sight-words-da7x"},
  {id: 1, text:"đen",filename:"bk-hn-sight-words-den7"},
  {id: 2, text:"đường",filename:"bk-hn-sight-words-duong756f"},
  {id: 3, text:"đóng",filename:"bk-hn-sight-words-dong7s"},
  {id: 4, text:"đang",filename:"bk-hn-sight-words-dang7"},
  {id: 5, text:"đứng",filename:"bk-hn-sight-words-dung75s"},
  {id: 6, text:"được",filename:"bk-hn-sight-words-duoc756j"},
  {id: 7, text:"đất",filename:"bk-hn-sight-words-dat72s"},
  {id: 8, text:"đẹp",filename:"bk-hn-sight-words-dep7j"},
  {id: 9, text:"em",filename:"bk-hn-sight-words-em"},
  {id: 10, text:"gái",filename:"bk-hn-sight-words-gais"},
  {id: 11, text:"gà",filename:"bk-hn-sight-words-gaf"},
  {id: 12, text:"gần",filename:"bk-hn-sight-words-gan2f"},
];
export const SIGHT_WORDS_8: Word[] = [
  {id: 0, text:"gọi",filename:"bk-hn-sight-words-goij"},
  {id: 1, text:"giỏi",filename:"bk-hn-sight-words-gioir"},
  {id: 2, text:"giúp",filename:"bk-hn-sight-words-giups"},
  {id: 3, text:"giống",filename:"bk-hn-sight-words-giong4s"},
  {id: 4, text:"hai",filename:"bk-hn-sight-words-hai"},
  {id: 5, text:"hay",filename:"bk-hn-sight-words-hay"},
  {id: 6, text:"hoa",filename:"bk-hn-sight-words-hoa"},
  {id: 7, text:"hè",filename:"bk-hn-sight-words-hef"},
  {id: 8, text:"hơn",filename:"bk-hn-sight-words-hon6"},
  {id: 9, text:"hổ",filename:"bk-hn-sight-words-ho4r"},
  {id: 10, text:"học",filename:"bk-hn-sight-words-hocj"},
  {id: 11, text:"lợn",filename:"bk-hn-sight-words-lon6j"},
];
export const SIGHT_WORDS_9: Word[] = [
  {id: 0, text:"ít",filename:"bk-hn-sight-words-its"},
  {id: 1, text:"khi",filename:"bk-hn-sight-words-khi"},
  {id: 2, text:"không",filename:"bk-hn-sight-words-khong4"},
  {id: 3, text:"kia",filename:"bk-hn-sight-words-kia"},
  {id: 4, text:"kìa",filename:"bk-hn-sight-words-kiaf"},
  {id: 5, text:"khó",filename:"bk-hn-sight-words-khos"},
  {id: 6, text:"khóc",filename:"bk-hn-sight-words-khocs"},
  {id: 7, text:"khác",filename:"bk-hn-sight-words-khacs"},
  {id: 8, text:"lạnh",filename:"bk-hn-sight-words-lanhj"},
  {id: 9, text:"làm",filename:"bk-hn-sight-words-lamf"},
  {id: 10, text:"lấy",filename:"bk-hn-sight-words-lay2s"},
  {id: 11, text:"là ",filename:"bk-hn-sight-words-laf"},
];
export const SIGHT_WORDS_10: Word[] = [
  {id: 0, text:"lá",filename:"bk-hn-sight-words-las"},
  {id: 1, text:"lớn",filename:"bk-hn-sight-words-lon6s"},
  {id: 2, text:"lửa",filename:"bk-hn-sight-words-lua5r"},
  {id: 3, text:"lên",filename:"bk-hn-sight-words-len3"},
  {id: 4, text:"lại",filename:"bk-hn-sight-words-laij"},
  {id: 5, text:"mới",filename:"bk-hn-sight-words-moi6s"},
  {id: 6, text:"mẹ",filename:"bk-hn-sight-words-mej"},
  {id: 7, text:"mèo",filename:"bk-hn-sight-words-meof"},
  {id: 8, text:"mở",filename:"bk-hn-sight-words-mo6r"},
  {id: 9, text:"mua",filename:"bk-hn-sight-words-mua"},
  {id: 10, text:"mang",filename:"bk-hn-sight-words-mang"},
];
export const SIGHT_WORDS_11: Word[] = [
  {id: 0, text:"múa",filename:"bk-hn-sight-words-muas"},
  {id: 1, text:"mai",filename:"bk-hn-sight-words-mai"},
  {id: 2, text:"mùa",filename:"bk-hn-sight-words-muaf"},
  {id: 3, text:"một",filename:"bk-hn-sight-words-mot4j"},
  {id: 4, text:"mà",filename:"bk-hn-sight-words-maf"},
  {id: 5, text:"mình",filename:"bk-hn-sight-words-minhf"},
  {id: 6, text:"màu",filename:"bk-hn-sight-words-mauf"},
  {id: 7, text:"mặt",filename:"bk-hn-sight-words-mat1j"},
  {id: 8, text:"ngắn",filename:"bk-hn-sight-words-ngan1s"},
  {id: 9, text:"ngồi",filename:"bk-hn-sight-words-ngoi4f"},
  {id: 10, text:"ngủ",filename:"bk-hn-sight-words-ngur"},
];
export const SIGHT_WORDS_12: Word[] = [
  {id: 0, text:"ngựa",filename:"bk-hn-sight-words-ngua5j"},
  {id: 1, text:"ngày",filename:"bk-hn-sight-words-ngayf"},
  {id: 2, text:"người",filename:"bk-hn-sight-words-nguoi56f"},
  {id: 3, text:"ngoài",filename:"bk-hn-sight-words-ngoaif"},
  {id: 4, text:"nghĩ",filename:"bk-hn-sight-words-nghix"},
  {id: 5, text:"nào",filename:"bk-hn-sight-words-naof"},
  {id: 6, text:"nâu",filename:"bk-hn-sight-words-nau2"},
  {id: 7, text:"nóng",filename:"bk-hn-sight-words-nongs"},
  {id: 8, text:"nằm",filename:"bk-hn-sight-words-nam1f"},
  {id: 9, text:"núi",filename:"bk-hn-sight-words-nuis"},
  {id: 10, text:"nặng",filename:"bk-hn-sight-words-nang1j"},
];
export const SIGHT_WORDS_13: Word[] = [
  {id: 0, text:"năm",filename:"bk-hn-sight-words-nam1"},
  {id: 1, text:"này",filename:"bk-hn-sight-words-nayf"},
  {id: 2, text:"nói",filename:"bk-hn-sight-words-nois"},
  {id: 3, text:"nước",filename:"bk-hn-sight-words-nuoc56s"},
  {id: 4, text:"nữa",filename:"bk-hn-sight-words-nua5x"},
  {id: 5, text:"nhẹ",filename:"bk-hn-sight-words-nhej"},
  {id: 6, text:"nhanh",filename:"bk-hn-sight-words-nhanh"},
  {id: 7, text:"nhìn",filename:"bk-hn-sight-words-nhinf"},
  {id: 8, text:"nhiều",filename:"bk-hn-sight-words-nhieu3f"},
  {id: 9, text:"nhé",filename:"bk-hn-sight-words-nhes"},
  {id: 10, text:"nhà",filename:"bk-hn-sight-words-nhaf"},
];
export const SIGHT_WORDS_14: Word[] = [
  {id: 0, text:"nhất",filename:"bk-hn-sight-words-nhat2s"},
  {id: 1, text:"như",filename:"bk-hn-sight-words-nhu5"},
  {id: 2, text:"nhưng",filename:"bk-hn-sight-words-nhung5"},
  {id: 3, text:"ở",filename:"bk-hn-sight-words-o6r"},
  {id: 4, text:"ông",filename:"bk-hn-sight-words-ong4"},
  {id: 5, text:"phố",filename:"bk-hn-sight-words-pho4s"},
  {id: 6, text:"quê",filename:"bk-hn-sight-words-que3"},
  {id: 7, text:"qua",filename:"bk-hn-sight-words-qua"},
  {id: 8, text:"quả",filename:"bk-hn-sight-words-quar"},
  {id: 9, text:"quá",filename:"bk-hn-sight-words-quas"},
  {id: 10, text:"ra",filename:"bk-hn-sight-words-ra"},
];
export const SIGHT_WORDS_15: Word[] = [
  {id: 0, text:"rau",filename:"bk-hn-sight-words-rau"},
  {id: 1, text:"rất",filename:"bk-hn-sight-words-rat2s"},
  {id: 2, text:"rồi",filename:"bk-hn-sight-words-roi4f"},
  {id: 3, text:"sẽ",filename:"bk-hn-sight-words-sex"},
  {id: 4, text:"sóng",filename:"bk-hn-sight-words-songs"},
  {id: 5, text:"sáng",filename:"bk-hn-sight-words-sangs"},
  {id: 6, text:"sau",filename:"bk-hn-sight-words-sau"},
  {id: 7, text:"sao",filename:"bk-hn-sight-words-sao"},
  {id: 8, text:"to",filename:"bk-hn-sight-words-to"},
  {id: 9, text:"tay",filename:"bk-hn-sight-words-tay"},
  {id: 10, text:"tới",filename:"bk-hn-sight-words-toi6s"},
  {id: 11, text:"tuổi",filename:"bk-hn-sight-words-tuoi4r"},
];
export const SIGHT_WORDS_16: Word[] = [
  {id: 0, text:"tối",filename:"bk-hn-sight-words-toi4s"},
  {id: 1, text:"tự",filename:"bk-hn-sight-words-tu5j"},
  {id: 2, text:"tôi",filename:"bk-hn-sight-words-toi4 "},
  {id: 3, text:"tốt",filename:"bk-hn-sight-words-tot4s"},
  {id: 4, text:"từ",filename:"bk-hn-sight-words-tu5f"},
  {id: 5, text:"tìm",filename:"bk-hn-sight-words-timf"},
  {id: 6, text:"tên",filename:"bk-hn-sight-words-ten3"},
  {id: 7, text:"tớ",filename:"bk-hn-sight-words-to6s"},
  {id: 8, text:"tiền",filename:"bk-hn-sight-words-tien3f"},
  {id: 9, text:"trong",filename:"bk-hn-sight-words-trong"},
  {id: 10, text:"trưa",filename:"bk-hn-sight-words-trua5"},
  {id: 11, text:"trăng",filename:"bk-hn-sight-words-trang1"},
];
export const SIGHT_WORDS_17: Word[] = [
  {id: 0, text:"trai",filename:"bk-hn-sight-words-trai"},
  {id: 1, text:"trước",filename:"bk-hn-sight-words-truoc56s"},
  {id: 2, text:"trắng",filename:"bk-hn-sight-words-trang1s"},
  {id: 3, text:"trên",filename:"bk-hn-sight-words-tren3"},
  {id: 4, text:"thương",filename:"bk-hn-sight-words-thuong56"},
  {id: 5, text:"thỏ",filename:"bk-hn-sight-words-thor"},
  {id: 6, text:"thư ",filename:"bk-hn-sight-words-thu5"},
  {id: 7, text:"thì ",filename:"bk-hn-sight-words-thif"},
  {id: 8, text:"thợ ",filename:"bk-hn-sight-words-tho6j"},
  {id: 9, text:"thế",filename:"bk-hn-sight-words-the3s"},
  {id: 10, text:"thích",filename:"bk-hn-sight-words-thichs"},
  {id: 11, text:"ướt",filename:"bk-hn-sight-words-uot56s"},
];
export const SIGHT_WORDS_18: Word[] = [
  {id: 0, text:"yêu",filename:"bk-hn-sight-words-yeu3"},
  {id: 1, text:"vẽ",filename:"bk-hn-sight-words-vex"},
  {id: 2, text:"viết",filename:"bk-hn-sight-words-viet3s"},
  {id: 3, text:"và",filename:"bk-hn-sight-words-vaf"},
  {id: 4, text:"vai",filename:"bk-hn-sight-words-vai"},
  {id: 5, text:"với",filename:"bk-hn-sight-words-voi6s"},
  {id: 6, text:"vui",filename:"bk-hn-sight-words-vui"},
  {id: 7, text:"về",filename:"bk-hn-sight-words-ve3f"},
  {id: 8, text:"vâng",filename:"bk-hn-sight-words-vang2"},
  {id: 9, text:"vàng",filename:"bk-hn-sight-words-vangf"},
  {id: 10, text:"vào",filename:"bk-hn-sight-words-vaof"},
];
export const SIGHT_WORDS_19: Word[] = [
  {id: 0, text:"xuống",filename:"bk-hn-sight-words-xuong4s"},
  {id: 1, text:"xong",filename:"bk-hn-sight-words-xong"},
  {id: 2, text:"xa",filename:"bk-hn-sight-words-xa"},
  {id: 3, text:"xe",filename:"bk-hn-sight-words-xe"},
  {id: 4, text:"xin",filename:"bk-hn-sight-words-xin"},
  {id: 5, text:"xanh",filename:"bk-hn-sight-words-xanh"},
  {id: 6, text:"cảm ơn",filename:"bk-hn-sight-words-camon"},
  {id: 7, text:"xin lỗi",filename:"bk-hn-sight-words-xinloi"},
  {id: 8, text:"có thể",filename:"bk-hn-sight-words-cothe"}];
