/**
 * Created by tovan on 2/20/2017.
 */
import {Word} from '../models/word';
//id 0 là tiêu đề và nội dung chính
//id 0 rất quan trọng sau này sử dụng nó để lấy ra độ dài của từ chung từ đó cắt từ cho phù hợp
//id 1 trở đi là nội dung từng câu
//text là nội dung text sẽ hiển thị lên màn hình, sẽ dùng hàm riêng để cắt text
//file name là tên file dùng option để lấy rõ địa chỉ file
export const WORDS_ENDING_WITH_ai: Word[] = [
  {id:0,text:"ai",filename:"pho-end-ai-title"},
  {id:1,text:"...ai",filename:"pho-end-ai-title"},
  {id:2,text:"bai",filename:"pho-end-ai-bai"},
  {id:3,text:"cai",filename:"pho-end-ai-cai"},
  {id:4,text:"chai",filename:"pho-end-ai-chai"},
  {id:5,text:"dai",filename:"pho-end-ai-dai"},
  {id:6,text:"hai",filename:"pho-end-ai-hai"},
  {id:7,text:"đai",filename:"pho-end-ai-dai7"},
  {id:8,text:"lai",filename:"pho-end-ai-lai"},
  {id:9,text:"mai",filename:"pho-end-ai-mai"},
  {id:10,text:"sai",filename:"pho-end-ai-sai"},
  {id:11,text:"vai",filename:"pho-end-ai-vai"},
  {id:12,text:"nhai",filename:"pho-end-ai-nhai"},
  {id:13,text:"phai",filename:"pho-end-ai-phai"},
];
export const WORDS_ENDING_WITH_ais: Word[] = [
  {id:0,text:"ái",filename:"pho-end-ais-title"},
  {id:1,text:"...ái",filename:"pho-end-ais-title"},
  {id:2,text:"thái",filename:"pho-end-ais-thais"},
  {id:3,text:"quái",filename:"pho-end-ais-quais"},
  {id:4,text:"phái",filename:"pho-end-ais-phais"},
  {id:5,text:"tái",filename:"pho-end-ais-tais"},
  {id:6,text:"vái",filename:"pho-end-ais-vais"},
  {id:7,text:"hái",filename:"pho-end-ais-hais"},
  {id:8,text:"cái",filename:"pho-end-ais-cais"},
  {id:9,text:"trái",filename:"pho-end-ais-trais"},
  {id:10,text:"gái",filename:"pho-end-ais-gais"},
  {id:11,text:"hái",filename:"pho-end-ais-hais"},
  {id:12,text:"nhái",filename:"pho-end-ais-nhais"},
];
export const WORDS_ENDING_WITH_aof: Word[] = [
  {id: 0, text:"ào",filename:"bk-hn-pho-end-aof-title"},
  {id: 1, text:"...ào",filename:"bk-hn-pho-end-aof-title"},
  {id: 2, text:"cào",filename:"bk-hn-pho-end-aof-caof"},
  {id: 3, text:"chào",filename:"bk-hn-pho-end-aof-chaof"},
  {id: 4, text:"phào",filename:"bk-hn-pho-end-aof-phaof"},
  {id: 5, text:"lào",filename:"bk-hn-pho-end-aof-laof"},
  {id: 6, text:"nào",filename:"bk-hn-pho-end-aof-naof"},
  {id: 7, text:"vào",filename:"bk-hn-pho-end-aof-vaof"},
  {id: 8, text:"xào",filename:"bk-hn-pho-end-aof-xaof"},
  {id: 9, text:"trào",filename:"bk-hn-pho-end-aof-traof"},
  {id: 10, text:"mào",filename:"bk-hn-pho-end-aof-maof"},
  {id: 11, text:"đào",filename:"bk-hn-pho-end-aof-dao7f"},
  {id: 12, text:"rào",filename:"bk-hn-pho-end-aof-raof"},

];
export const WORDS_ENDING_WITH_aor: Word[] = [
  {id: 0, text:"ảo",filename:"bk-hn-pho-end-aor-title"},
  {id: 1, text:"...ảo",filename:"bk-hn-pho-end-aor-title"},
  {id: 2, text:"bảo",filename:"bk-hn-pho-end-aor-baor"},
  {id: 3, text:"thảo",filename:"bk-hn-pho-end-aor-thaor"},
  {id: 4, text:"tảo",filename:"bk-hn-pho-end-aor-taor"},
  {id: 5, text:"chảo",filename:"bk-hn-pho-end-aor-chaor"},
  {id: 6, text:"đảo",filename:"bk-hn-pho-end-aor-dao7r"},
  {id: 7, text:"sảo",filename:"bk-hn-pho-end-aor-saor"},
  {id: 8, text:"khảo",filename:"bk-hn-pho-end-aor-khaor"}
];
export const WORDS_ENDING_WITH_au: Word[] = [
  {id: 0, text:"au",filename:"bk-hn-pho-end-au-title"},
  {id: 1, text:"...au",filename:"bk-hn-pho-end-au-title"},
  {id: 2, text:"cau",filename:"bk-hn-pho-end-au-cau"},
  {id: 3, text:"mau",filename:"bk-hn-pho-end-au-mau"},
  {id: 4, text:"đau",filename:"bk-hn-pho-end-au-dau7"},
  {id: 5, text:"rau",filename:"bk-hn-pho-end-au-rau"},
  {id: 6, text:"sau",filename:"bk-hn-pho-end-au-sau"},
  {id: 7, text:"thau",filename:"bk-hn-pho-end-au-thau"},
];
export const WORDS_ENDING_WITH_aus: Word[] = [
  {id: 0, text:"áu",filename:"bk-hn-pho-end-aus-title"},
  {id: 1, text:"...áu",filename:"bk-hn-pho-end-aus-title"},
  {id: 2, text:"cáu",filename:"bk-hn-pho-end-aus-caus"},
  {id: 3, text:"đáu",filename:"bk-hn-pho-end-aus-dau7s"},
  {id: 4, text:"háu",filename:"bk-hn-pho-end-aus-haus"},
  {id: 5, text:"láu",filename:"bk-hn-pho-end-aus-laus"},
  {id: 6, text:"máu",filename:"bk-hn-pho-end-aus-maus"},
  {id: 7, text:"cháu",filename:"bk-hn-pho-end-aus-chaus"},
  {id: 8, text:"sáu",filename:"bk-hn-pho-end-aus-saus"},
];
export const WORDS_ENDING_WITH_ayx: Word[] = [
  {id: 0, text:"ãy",filename:"bk-hn-pho-end-ayx-title"},
  {id: 1, text:"...ãy",filename:"bk-hn-pho-end-ayx-title"},
  {id: 2, text:"gãy",filename:"bk-hn-pho-end-ayx-gayx"},
  {id: 3, text:"hãy",filename:"bk-hn-pho-end-ayx-hayx"},
  {id: 4, text:"lãy",filename:"bk-hn-pho-end-ayx-layx"},
  {id: 5, text:"nãy",filename:"bk-hn-pho-end-ayx-nayx"},
  {id: 6, text:"giãy",filename:"bk-hn-pho-end-ayx-giayx"},
  {id: 7, text:"dãy",filename:"bk-hn-pho-end-ayx-dayx"},
];
export const WORDS_ENDING_WITH_ayj: Word[] = [
  {id: 0, text:"ạy",filename:"bk-hn-pho-end-ayj-title"},
  {id: 1, text:"...ạy",filename:"bk-hn-pho-end-ayj-title"},
  {id: 2, text:"cạy",filename:"bk-hn-pho-end-ayj-cayj"},
  {id: 3, text:"nạy",filename:"bk-hn-pho-end-ayj-nayj"},
  {id: 4, text:"chạy",filename:"bk-hn-pho-end-ayj-chayj"},
  {id: 5, text:"dạy",filename:"bk-hn-pho-end-ayj-dayj"},
  {id: 6, text:"nhạy",filename:"bk-hn-pho-end-ayj-nhayj"}
];
export const WORDS_ENDING_WITH_am: Word[] = [
  {id: 0, text:"am",filename:"bk-hn-pho-end-am-title"},
  {id: 1, text:"...am",filename:"bk-hn-pho-end-am-title"},
  {id: 2, text:"bam",filename:"bk-hn-pho-end-am-bam"},
  {id: 3, text:"cam",filename:"bk-hn-pho-end-am-cam"},
  {id: 4, text:"đam",filename:"bk-hn-pho-end-am-dam7"},
  {id: 5, text:"ram",filename:"bk-hn-pho-end-am-ram"},
  {id: 6, text:"lam",filename:"bk-hn-pho-end-am-lam"},
  {id: 7, text:"ham",filename:"bk-hn-pho-end-am-ham"},
  {id: 8, text:"nam",filename:"bk-hn-pho-end-am-nam"},
  {id: 9, text:"tham",filename:"bk-hn-pho-end-am-tham"},
];
export const WORDS_ENDING_WITH_ams: Word[] = [
  {id: 0, text:"ám",filename:"bk-hn-pho-end-ams-title"},
  {id: 1, text:"...ám",filename:"bk-hn-pho-end-ams-title"},
  {id: 2, text:"bám",filename:"bk-hn-pho-end-ams-bams"},
  {id: 3, text:"nám",filename:"bk-hn-pho-end-ams-nams"},
  {id: 4, text:"khám",filename:"bk-hn-pho-end-ams-khams"},
  {id: 5, text:"rám",filename:"bk-hn-pho-end-ams-rams"},
  {id: 6, text:"cám",filename:"bk-hn-pho-end-ams-cams"},
  {id: 7, text:"xám",filename:"bk-hn-pho-end-ams-xams"},
  {id: 8, text:"nhám",filename:"bk-hn-pho-end-ams-nhams"},
  {id: 9, text:"dám",filename:"bk-hn-pho-end-ams-dams"},
  {id: 10, text:"đám",filename:"bk-hn-pho-end-ams-dam7s"},
];
export const WORDS_ENDING_WITH_angf: Word[] = [
  {id: 0, text:"àng",filename:"bk-hn-pho-end-angf-title"},
  {id: 1, text:"...àng",filename:"bk-hn-pho-end-angf-title"},
  {id: 2, text:"càng",filename:"bk-hn-pho-end-angf-cangf"},
  {id: 3, text:"nàng",filename:"bk-hn-pho-end-angf-nangf"},
  {id: 4, text:"vàng",filename:"bk-hn-pho-end-angf-vangf"},
  {id: 5, text:"ràng",filename:"bk-hn-pho-end-angf-rangf"},
  {id: 6, text:"đàng",filename:"bk-hn-pho-end-angf-dang7f"},
  {id: 7, text:"chàng",filename:"bk-hn-pho-end-angf-changf"},
  {id: 8, text:"quàng",filename:"bk-hn-pho-end-angf-quangf"},
  {id: 9, text:"hàng",filename:"bk-hn-pho-end-angf-hangf"},
  {id: 10, text:"làng",filename:"bk-hn-pho-end-angf-langf"},
  {id: 11, text:"màng",filename:"bk-hn-pho-end-angf-mangf"},
  {id: 12, text:"bàng",filename:"bk-hn-pho-end-angf-bangf"},
];
export const WORDS_ENDING_WITH_angr: Word[] = [
  {id: 0, text:"ảng",filename:"bk-hn-pho-end-angr-title"},
  {id: 1, text:"...ảng",filename:"bk-hn-pho-end-angr-title"},
  {id: 2, text:"bảng",filename:"bk-hn-pho-end-angr-bangr"},
  {id: 3, text:"cảng",filename:"bk-hn-pho-end-angr-cangr"},
  {id: 4, text:"thảng",filename:"bk-hn-pho-end-angr-thangr"},
  {id: 5, text:"tảng",filename:"bk-hn-pho-end-angr-tangr"},
  {id: 6, text:"quảng",filename:"bk-hn-pho-end-angr-quangr"},
  {id: 7, text:"giảng",filename:"bk-hn-pho-end-angr-giangr"},
];
export const WORDS_ENDING_WITH_aps: Word[] = [
  {id: 0, text:"áp",filename:"bk-hn-pho-end-aps-title"},
  {id: 1, text:"...áp",filename:"bk-hn-pho-end-aps-title"},
  {id: 2, text:"cáp",filename:"bk-hn-pho-end-aps-caps"},
  {id: 3, text:"táp",filename:"bk-hn-pho-end-aps-taps"},
  {id: 4, text:"tháp",filename:"bk-hn-pho-end-aps-thaps"},
  {id: 5, text:"sáp",filename:"bk-hn-pho-end-aps-saps"},
  {id: 6, text:"láp",filename:"bk-hn-pho-end-aps-laps"},
  {id: 7, text:"giáp",filename:"bk-hn-pho-end-aps-giaps"},
  {id: 8, text:"pháp",filename:"bk-hn-pho-end-aps-phaps"},
  {id: 9, text:"nháp",filename:"bk-hn-pho-end-aps-nhaps"},
];
export const WORDS_ENDING_WITH_apj: Word[] = [
  {id: 0, text:"ạp",filename:"bk-hn-pho-end-apj-title"},
  {id: 1, text:"...ạp",filename:"bk-hn-pho-end-apj-title"},
  {id: 2, text:"cạp",filename:"bk-hn-pho-end-apj-capj"},
  {id: 3, text:"nạp",filename:"bk-hn-pho-end-apj-napj"},
  {id: 4, text:"thạp",filename:"bk-hn-pho-end-apj-thapj"},
  {id: 5, text:"sạp",filename:"bk-hn-pho-end-apj-sapj"},
  {id: 6, text:"hạp",filename:"bk-hn-pho-end-apj-hapj"},
  {id: 7, text:"tạp",filename:"bk-hn-pho-end-apj-tapj"},
  {id: 8, text:"đạp",filename:"bk-hn-pho-end-apj-dap7j"},
];
export const WORDS_ENDING_WITH_ats: Word[] = [
  {id: 0, text:"át",filename:"bk-hn-pho-end-ats-title"},
  {id: 1, text:"...át",filename:"bk-hn-pho-end-ats-title"},
  {id: 2, text:"cát",filename:"bk-hn-pho-end-ats-cats"},
  {id: 3, text:"mát",filename:"bk-hn-pho-end-ats-mats"},
  {id: 4, text:"hát",filename:"bk-hn-pho-end-ats-hats"},
  {id: 5, text:"hát",filename:"bk-hn-pho-end-ats-hats"},
  {id: 6, text:"lát",filename:"bk-hn-pho-end-ats-lats"},
  {id: 7, text:"tát",filename:"bk-hn-pho-end-ats-tats"},
  {id: 8, text:"bát",filename:"bk-hn-pho-end-ats-bats"},
  {id: 9, text:"nát",filename:"bk-hn-pho-end-ats-nats"},
  {id: 10, text:"quát",filename:"bk-hn-pho-end-ats-quats"},
  {id: 11, text:"nhát",filename:"bk-hn-pho-end-ats-nhats"},
  {id: 12, text:"chát",filename:"bk-hn-pho-end-ats-chats"},
  {id: 13, text:"khát",filename:"bk-hn-pho-end-ats-khats"},
];
export const WORDS_ENDING_WITH_atj: Word[] = [
  {id: 0, text:"ạt",filename:"bk-hn-pho-end-atj-title"},
  {id: 1, text:"...ạt",filename:"bk-hn-pho-end-atj-title"},
  {id: 2, text:"bạt",filename:"bk-hn-pho-end-atj-batj"},
  {id: 3, text:"hạt",filename:"bk-hn-pho-end-atj-hatj"},
  {id: 4, text:"nhạt",filename:"bk-hn-pho-end-atj-nhatj"},
  {id: 5, text:"phạt",filename:"bk-hn-pho-end-atj-phatj"},
  {id: 6, text:"đạt",filename:"bk-hn-pho-end-atj-dat7j"},
  {id: 7, text:"dạt",filename:"bk-hn-pho-end-atj-datj"},
];
export const WORDS_ENDING_WITH_ac1s: Word[] = [
  {id: 0, text:"ắc",filename:"bk-hn-pho-end-ac1s-title"},
  {id: 1, text:"...ắc",filename:"bk-hn-pho-end-ac1s-title"},
  {id: 2, text:"bắc",filename:"bk-hn-pho-end-ac1s-bac1s"},
  {id: 3, text:"chắc",filename:"bk-hn-pho-end-ac1s-chac1s"},
  {id: 4, text:"thắc",filename:"bk-hn-pho-end-ac1s-thac1s"},
  {id: 5, text:"sắc",filename:"bk-hn-pho-end-ac1s-sac1s"},
  {id: 6, text:"rắc",filename:"bk-hn-pho-end-ac1s-rac1s"},
  {id: 7, text:"nhắc",filename:"bk-hn-pho-end-ac1s-nhac1s"},
  {id: 8, text:"tắc",filename:"bk-hn-pho-end-ac1s-tac1s"},
  {id: 9, text:"mắc",filename:"bk-hn-pho-end-ac1s-mac1s"},
];
export const WORDS_ENDING_WITH_ac1j: Word[] = [
  {id: 0, text:"ặc",filename:"bk-hn-pho-end-ac1j-title"},
  {id: 1, text:"...ặc",filename:"bk-hn-pho-end-ac1j-title"},
  {id: 2, text:"đặc",filename:"bk-hn-pho-end-ac1j-dac71j"},
  {id: 3, text:"mặc",filename:"bk-hn-pho-end-ac1j-mac1j"},
  {id: 4, text:"ngặc",filename:"bk-hn-pho-end-ac1j-ngac1j"},
  {id: 5, text:"sặc",filename:"bk-hn-pho-end-ac1j-sac1j"},
  {id: 6, text:"tặc",filename:"bk-hn-pho-end-ac1j-tac1j"},
]
export const WORDS_ENDING_WITH_ang1: Word[] = [
  {id: 0, text:"ăng",filename:"bk-hn-pho-end-ang1-title"},
  {id: 1, text:"...ăng",filename:"bk-hn-pho-end-ang1-title"},
  {id: 2, text:"băng",filename:"bk-hn-pho-end-ang1-bang1"},
  {id: 3, text:"căng",filename:"bk-hn-pho-end-ang1-cang1"},
  {id: 4, text:"đăng",filename:"bk-hn-pho-end-ang1-dang71"},
  {id: 5, text:"răng",filename:"bk-hn-pho-end-ang1-rang1"},
  {id: 6, text:"trăng",filename:"bk-hn-pho-end-ang1-trang1"},
  {id: 7, text:"văng",filename:"bk-hn-pho-end-ang1-vang1"},
  {id: 8, text:"hăng",filename:"bk-hn-pho-end-ang1-hang1"},
];
export const WORDS_ENDING_WITH_ang1s: Word[] = [
  {id: 0, text:"ắng",filename:"bk-hn-pho-end-ang1s-title"},
  {id: 1, text:"...ắng",filename:"bk-hn-pho-end-ang1s-title"},
  {id: 2, text:"nắng",filename:"bk-hn-pho-end-ang1s-nang1s"},
  {id: 3, text:"lắng",filename:"bk-hn-pho-end-ang1s-lang1s"},
  {id: 4, text:"thắng",filename:"bk-hn-pho-end-ang1s-thang1s"},
  {id: 5, text:"trắng",filename:"bk-hn-pho-end-ang1s-trang1s"},
  {id: 6, text:"mắng",filename:"bk-hn-pho-end-ang1s-mang1s"},
  {id: 7, text:"đắng",filename:"bk-hn-pho-end-ang1s-dang71s"},
];
export const WORDS_ENDING_WITH_ap1j: Word[] = [
  {id: 0, text:"ặp",filename:"bk-hn-pho-end-ap1j-title"},
  {id: 1, text:"...ặp",filename:"bk-hn-pho-end-ap1j-title"},
  {id: 2, text:"cặp",filename:"bk-hn-pho-end-ap1j-cap1j"},
  {id: 3, text:"lặp",filename:"bk-hn-pho-end-ap1j-lap1j"},
  {id: 4, text:"gặp",filename:"bk-hn-pho-end-ap1j-gap1j"},
  {id: 5, text:"chặp",filename:"bk-hn-pho-end-ap1j-chap1j"},
  {id: 6, text:"quặp",filename:"bk-hn-pho-end-ap1j-quap1j"},
]
export const WORDS_ENDING_WITH_at1s: Word[] = [
  {id: 0, text:"ắt",filename:"bk-hn-pho-end-at1s-title"},
  {id: 1, text:"...ắt",filename:"bk-hn-pho-end-at1s-title"},
  {id: 2, text:"mắt",filename:"bk-hn-pho-end-at1s-mat1s"},
  {id: 3, text:"tắt",filename:"bk-hn-pho-end-at1s-tat1s"},
  {id: 4, text:"lắt",filename:"bk-hn-pho-end-at1s-lat1s"},
  {id: 5, text:"cắt",filename:"bk-hn-pho-end-at1s-cat1s"},
  {id: 6, text:"bắt",filename:"bk-hn-pho-end-at1s-bat1s"},
  {id: 7, text:"gắt",filename:"bk-hn-pho-end-at1s-gat1s"},
  {id: 8, text:"đắt",filename:"bk-hn-pho-end-at1s-dat71s"},
  {id: 9, text:"dắt",filename:"bk-hn-pho-end-at1s-dat1s"},
];
export const WORDS_ENDING_WITH_at1j: Word[] = [
  {id: 0, text:"ặt",filename:"bk-hn-pho-end-at1j-title"},
  {id: 1, text:"...ặt",filename:"bk-hn-pho-end-at1j-title"},
  {id: 2, text:"mặt",filename:"bk-hn-pho-end-at1j-mat1j"},
  {id: 3, text:"rặt",filename:"bk-hn-pho-end-at1j-rat1j"},
  {id: 4, text:"quặt",filename:"bk-hn-pho-end-at1j-quat1j"},
  {id: 5, text:"vặt",filename:"bk-hn-pho-end-at1j-vat1j"},
  {id: 6, text:"đặt",filename:"bk-hn-pho-end-at1j-dat71j"},
  {id: 7, text:"chặt",filename:"bk-hn-pho-end-at1j-chat1j"},
  {id: 8, text:"nhặt",filename:"bk-hn-pho-end-at1j-nhat1j"},
  {id: 9, text:"giặt",filename:"bk-hn-pho-end-at1j-giat1j"},
]
export const WORDS_ENDING_WITH_au2: Word[] = [
  {id: 0, text:"âu",filename:"bk-hn-pho-end-au2-title"},
  {id: 1, text:"...âu",filename:"bk-hn-pho-end-au2-title"},
  {id: 2, text:"lâu",filename:"bk-hn-pho-end-au2-lau2"},
  {id: 3, text:"nâu",filename:"bk-hn-pho-end-au2-nau2"},
  {id: 4, text:"khâu",filename:"bk-hn-pho-end-au2-khau2"},
  {id: 5, text:"tâu",filename:"bk-hn-pho-end-au2-tau2"},
  {id: 6, text:"râu",filename:"bk-hn-pho-end-au2-rau2"},
  {id: 7, text:"sâu",filename:"bk-hn-pho-end-au2-sau2"},
  {id: 8, text:"câu",filename:"bk-hn-pho-end-au2-cau2"},
  {id: 9, text:"trâu",filename:"bk-hn-pho-end-au2-trau2"},
  {id: 10, text:"dâu",filename:"bk-hn-pho-end-au2-dau2"},
  {id: 11, text:"đâu",filename:"bk-hn-pho-end-au2-dau72"},
];
export const WORDS_ENDING_WITH_au2s: Word[] = [
  {id: 0, text:"ấu",filename:"bk-hn-pho-end-au2s-title"},
  {id: 1, text:"...ấu",filename:"bk-hn-pho-end-au2s-title"},
  {id: 2, text:"nấu",filename:"bk-hn-pho-end-au2s-nau2s"},
  {id: 3, text:"thấu",filename:"bk-hn-pho-end-au2s-thau2s"},
  {id: 4, text:"khấu",filename:"bk-hn-pho-end-au2s-khau2s"},
  {id: 5, text:"trấu",filename:"bk-hn-pho-end-au2s-trau2s"},
  {id: 6, text:"gấu",filename:"bk-hn-pho-end-au2s-gau2s"},
  {id: 7, text:"sấu",filename:"bk-hn-pho-end-au2s-sau2s"},
  {id: 8, text:"ngấu",filename:"bk-hn-pho-end-au2s-ngau2s"},
  {id: 9, text:"xấu",filename:"bk-hn-pho-end-au2s-xau2s"},
  {id: 10, text:"giấu",filename:"bk-hn-pho-end-au2s-giau2s"},
  {id: 12, text:"đấu",filename:"bk-hn-pho-end-au2s-dau72s"},
];
export const WORDS_ENDING_WITH_ay2: Word[] = [
  {id: 0, text:"ây",filename:"bk-hn-pho-end-ay2-title"},
  {id: 1, text:"...ây",filename:"bk-hn-pho-end-ay2-title"},
  {id: 2, text:"cây",filename:"bk-hn-pho-end-ay2-cay2"},
  {id: 3, text:"mây",filename:"bk-hn-pho-end-ay2-may2"},
  {id: 4, text:"ngây",filename:"bk-hn-pho-end-ay2-ngay2"},
  {id: 5, text:"tây",filename:"bk-hn-pho-end-ay2-tay2"},
  {id: 6, text:"hây",filename:"bk-hn-pho-end-ay2-hay2"},
  {id: 7, text:"lây",filename:"bk-hn-pho-end-ay2-lay2"},
  {id: 8, text:"xây",filename:"bk-hn-pho-end-ay2-xay2"},
  {id: 9, text:"quây",filename:"bk-hn-pho-end-ay2-quay2"},
  {id: 10, text:"dây",filename:"bk-hn-pho-end-ay2-day2"},
  {id: 11, text:"đây",filename:"bk-hn-pho-end-ay2-day72"},
  {id: 12, text:"vây",filename:"bk-hn-pho-end-ay2-vay2"},
];
export const WORDS_ENDING_WITH_ay2s: Word[] = [
  {id: 0, text:"y",filename:"bk-hn-pho-end-ay2s-title"},
  {id: 1, text:"...ấy",filename:"bk-hn-pho-end-ay2s-title"},
  {id: 2, text:"cấy",filename:"bk-hn-pho-end-ay2s-cay2s"},
  {id: 3, text:"thấy",filename:"bk-hn-pho-end-ay2s-thay2s"},
  {id: 4, text:"lấy",filename:"bk-hn-pho-end-ay2s-lay2s"},
  {id: 5, text:"đấy",filename:"bk-hn-pho-end-ay2s-day72s"},
  {id: 6, text:"sấy",filename:"bk-hn-pho-end-ay2s-say2s"},
  {id: 7, text:"giấy",filename:"bk-hn-pho-end-ay2s-giay2s"},
  {id: 8, text:"tấy",filename:"bk-hn-pho-end-ay2s-tay2s"},
  {id: 9, text:"ngấy",filename:"bk-hn-pho-end-ay2s-ngay2s"},
];
export const WORDS_ENDING_WITH_am2f: Word[] = [
  {id: 0, text:"ầm",filename:"bk-hn-pho-end-am2f-title"},
  {id: 1, text:"...ầm",filename:"bk-hn-pho-end-am2f-title"},
  {id: 2, text:"cầm",filename:"bk-hn-pho-end-am2f-cam2f"},
  {id: 3, text:"lầm",filename:"bk-hn-pho-end-am2f-lam2f"},
  {id: 4, text:"thầm",filename:"bk-hn-pho-end-am2f-tham2f"},
  {id: 5, text:"trầm",filename:"bk-hn-pho-end-am2f-tram2f"},
  {id: 6, text:"rầm",filename:"bk-hn-pho-end-am2f-ram2f"},
  {id: 7, text:"mầm",filename:"bk-hn-pho-end-am2f-mam2f"},
  {id: 8, text:"hầm",filename:"bk-hn-pho-end-am2f-ham2f"},
  {id: 9, text:"bầm",filename:"bk-hn-pho-end-am2f-bam2f"},
  {id: 10, text:"nhầm",filename:"bk-hn-pho-end-am2f-nham2f"},
  {id: 11, text:"gầm",filename:"bk-hn-pho-end-am2f-gam2f"},
];
export const WORDS_ENDING_WITH_am2r: Word[] = [
  {id: 0, text:"ẩm",filename:"bk-hn-pho-end-am2r-title"},
  {id: 1, text:"...ẩm",filename:"bk-hn-pho-end-am2r-title"},
  {id: 2, text:"bẩm",filename:"bk-hn-pho-end-am2r-bam2r"},
  {id: 3, text:"cẩm",filename:"bk-hn-pho-end-am2r-cam2r"},
  {id: 4, text:"thẩm",filename:"bk-hn-pho-end-am2r-tham2r"},
  {id: 5, text:"lẩm",filename:"bk-hn-pho-end-am2r-lam2r"},
  {id: 6, text:"phẩm",filename:"bk-hn-pho-end-am2r-pham2r"},
  {id: 7, text:"tẩm",filename:"bk-hn-pho-end-am2r-tam2r"},
  {id: 8, text:"nhẩm",filename:"bk-hn-pho-end-am2r-nham2r"},
];
export const WORDS_ENDING_WITH_ap2s: Word[] = [
  {id: 0, text:"ấp",filename:"bk-hn-pho-end-ap2s-title"},
  {id: 1, text:"...ấp",filename:"bk-hn-pho-end-ap2s-title"},
  {id: 2, text:"cấp",filename:"bk-hn-pho-end-ap2s-cap2s"},
  {id: 3, text:"thấp",filename:"bk-hn-pho-end-ap2s-thap2s"},
  {id: 4, text:"hấp",filename:"bk-hn-pho-end-ap2s-hap2s"},
  {id: 5, text:"lấp",filename:"bk-hn-pho-end-ap2s-lap2s"},
  {id: 6, text:"xấp",filename:"bk-hn-pho-end-ap2s-xap2s"},
  {id: 7, text:"vấp",filename:"bk-hn-pho-end-ap2s-vap2s"},
  {id: 8, text:"chấp",filename:"bk-hn-pho-end-ap2s-chap2s"},
  {id: 9, text:"gấp",filename:"bk-hn-pho-end-ap2s-gap2s"},
  {id: 10, text:"nấp",filename:"bk-hn-pho-end-ap2s-nap2s"},
];
export const WORDS_ENDING_WITH_ap2j: Word[] = [
  {id: 0, text:"ập",filename:"bk-hn-pho-end-ap2j-title"},
  {id: 1, text:"...ập",filename:"bk-hn-pho-end-ap2j-title"},
  {id: 2, text:"cập",filename:"bk-hn-pho-end-ap2j-cap2j"},
  {id: 3, text:"chập",filename:"bk-hn-pho-end-ap2j-chap2j"},
  {id: 4, text:"lập",filename:"bk-hn-pho-end-ap2j-lap2j"},
  {id: 5, text:"tập",filename:"bk-hn-pho-end-ap2j-tap2j"},
  {id: 6, text:"dập",filename:"bk-hn-pho-end-ap2j-dap2j"},
  {id: 7, text:"ngập",filename:"bk-hn-pho-end-ap2j-ngap2j"},
  {id: 8, text:"đập",filename:"bk-hn-pho-end-ap2j-dap72j"},
  {id: 9, text:"mập",filename:"bk-hn-pho-end-ap2j-map2j"},
];
export const WORDS_ENDING_WITH_at2s: Word[] = [
  {id: 0, text:"ất",filename:"bk-hn-pho-end-at2s-title"},
  {id: 1, text:"...ất",filename:"bk-hn-pho-end-at2s-title"},
  {id: 2, text:"tất",filename:"bk-hn-pho-end-at2s-tat2s"},
  {id: 3, text:"thất",filename:"bk-hn-pho-end-at2s-that2s"},
  {id: 4, text:"phất",filename:"bk-hn-pho-end-at2s-phat2s"},
  {id: 5, text:"hất",filename:"bk-hn-pho-end-at2s-hat2s"},
  {id: 6, text:"cất",filename:"bk-hn-pho-end-at2s-cat2s"},
  {id: 7, text:"ngất",filename:"bk-hn-pho-end-at2s-ngat2s"},
  {id: 8, text:"chất",filename:"bk-hn-pho-end-at2s-chat2s"},
  {id: 9, text:"rất",filename:"bk-hn-pho-end-at2s-rat2s"},
  {id: 10, text:"đất",filename:"bk-hn-pho-end-at2s-dat72s"},
  {id: 11, text:"mất",filename:"bk-hn-pho-end-at2s-mat2s"},
];
export const WORDS_ENDING_WITH_at2j: Word[] = [
  {id: 0, text:"ật",filename:"bk-hn-pho-end-at2j-title"},
  {id: 1, text:"...ật",filename:"bk-hn-pho-end-at2j-title"},
  {id: 2, text:"lật",filename:"bk-hn-pho-end-at2j-lat2j"},
  {id: 3, text:"thật",filename:"bk-hn-pho-end-at2j-that2j"},
  {id: 4, text:"chật",filename:"bk-hn-pho-end-at2j-chat2j"},
  {id: 5, text:"bật",filename:"bk-hn-pho-end-at2j-bat2j"},
  {id: 6, text:"phật",filename:"bk-hn-pho-end-at2j-phat2j"},
  {id: 7, text:"tật",filename:"bk-hn-pho-end-at2j-tat2j"},
  {id: 8, text:"vật",filename:"bk-hn-pho-end-at2j-vat2j"},
  {id: 9, text:"nhật",filename:"bk-hn-pho-end-at2j-nhat2j"},
  {id: 10, text:"giật",filename:"bk-hn-pho-end-at2j-giat2j"},
  {id: 11, text:"gật",filename:"bk-hn-pho-end-at2j-gat2j"},
  {id: 12, text:"mật",filename:"bk-hn-pho-end-at2j-mat2j"},
];
export const WORDS_ENDING_WITH_eo: Word[] = [
  {id: 0, text:"eo",filename:"bk-hn-pho-end-eo-title"},
  {id: 1, text:"...eo",filename:"bk-hn-pho-end-eo-title"},
  {id: 2, text:"beo",filename:"bk-hn-pho-end-eo-beo"},
  {id: 3, text:"heo",filename:"bk-hn-pho-end-eo-heo"},
  {id: 4, text:"keo",filename:"bk-hn-pho-end-eo-keo"},
  {id: 5, text:"meo",filename:"bk-hn-pho-end-eo-meo"},
  {id: 6, text:"neo",filename:"bk-hn-pho-end-eo-neo"},
  {id: 7, text:"đeo",filename:"bk-hn-pho-end-eo-deo7"},
  {id: 8, text:"reo",filename:"bk-hn-pho-end-eo-reo"},
  {id: 9, text:"nheo",filename:"bk-hn-pho-end-eo-nheo"},
  {id: 10, text:"theo",filename:"bk-hn-pho-end-eo-theo"},
  {id: 11, text:"treo",filename:"bk-hn-pho-end-eo-treo"},
];
export const WORDS_ENDING_WITH_eos: Word[] = [
  {id: 0, text:"éo",filename:"bk-hn-pho-end-eos-title"},
  {id: 1, text:"...éo",filename:"bk-hn-pho-end-eos-title"},
  {id: 2, text:"béo",filename:"bk-hn-pho-end-eos-beos"},
  {id: 3, text:"kéo",filename:"bk-hn-pho-end-eos-keos"},
  {id: 4, text:"véo",filename:"bk-hn-pho-end-eos-veos"},
  {id: 5, text:"léo",filename:"bk-hn-pho-end-eos-leos"},
  {id: 6, text:"nhéo",filename:"bk-hn-pho-end-eos-nheos"},
  {id: 7, text:"héo",filename:"bk-hn-pho-end-eos-heos"},
  {id: 8, text:"méo",filename:"bk-hn-pho-end-eos-meos"},
  {id: 9, text:"chéo",filename:"bk-hn-pho-end-eos-cheos"},
  {id: 10, text:"khéo",filename:"bk-hn-pho-end-eos-kheos"},
];
export const WORDS_ENDING_WITH_em: Word[] = [
  {id: 0, text:"em",filename:"bk-hn-pho-end-em-title"},
  {id: 1, text:"...em",filename:"bk-hn-pho-end-em-title"},
  {id: 2, text:"lem",filename:"bk-hn-pho-end-em-lem"},
  {id: 3, text:"nhem",filename:"bk-hn-pho-end-em-nhem"},
  {id: 4, text:"tem",filename:"bk-hn-pho-end-em-tem"},
  {id: 5, text:"rem",filename:"bk-hn-pho-end-em-rem"},
  {id: 6, text:"xem",filename:"bk-hn-pho-end-em-xem"},
  {id: 7, text:"kem",filename:"bk-hn-pho-end-em-kem"},
  {id: 8, text:"nem",filename:"bk-hn-pho-end-em-nem"},
];
export const WORDS_ENDING_WITH_epj: Word[] = [
  {id: 0, text:"ẹp",filename:"bk-hn-pho-end-epj-title"},
  {id: 1, text:"...ẹp",filename:"bk-hn-pho-end-epj-title"},
  {id: 2, text:"đẹp",filename:"bk-hn-pho-end-epj-dep7j"},
  {id: 3, text:"nẹp",filename:"bk-hn-pho-end-epj-nepj"},
  {id: 4, text:"bẹp",filename:"bk-hn-pho-end-epj-bepj"},
  {id: 5, text:"xẹp",filename:"bk-hn-pho-end-epj-xepj"},
  {id: 6, text:"hẹp",filename:"bk-hn-pho-end-epj-hepj"},
  {id: 7, text:"dẹp",filename:"bk-hn-pho-end-epj-depj"},
  {id: 8, text:"kẹp",filename:"bk-hn-pho-end-epj-kepj"},
];
export const WORDS_ENDING_WITH_eu3: Word[] = [
  {id: 0, text:"êu",filename:"bk-hn-pho-end-eu3-title"},
  {id: 1, text:"...êu",filename:"bk-hn-pho-end-eu3-title"},
  {id: 2, text:"kêu",filename:"bk-hn-pho-end-eu3-keu3"},
  {id: 3, text:"bêu",filename:"bk-hn-pho-end-eu3-beu3"},
  {id: 4, text:"thêu",filename:"bk-hn-pho-end-eu3-theu3"},
  {id: 5, text:"nêu",filename:"bk-hn-pho-end-eu3-neu3"},
  {id: 6, text:"lêu",filename:"bk-hn-pho-end-eu3-leu3"},
  {id: 7, text:"rêu",filename:"bk-hn-pho-end-eu3-reu3"},
  {id: 8, text:"trêu",filename:"bk-hn-pho-end-eu3-treu3"},
  {id: 9, text:"nghêu",filename:"bk-hn-pho-end-eu3-ngheu3"},
];
export const WORDS_ENDING_WITH_eu3f: Word[] = [
  {id: 0, text:"ều",filename:"bk-hn-pho-end-eu3f-title"},
  {id: 1, text:"...ều",filename:"bk-hn-pho-end-eu3f-title"},
  {id: 2, text:"lều",filename:"bk-hn-pho-end-eu3f-leu3f"},
  {id: 3, text:"vều",filename:"bk-hn-pho-end-eu3f-veu3f"},
  {id: 4, text:"đều",filename:"bk-hn-pho-end-eu3f-deu73f"},
  {id: 5, text:"khều",filename:"bk-hn-pho-end-eu3f-kheu3f"},
  {id: 6, text:"kều",filename:"bk-hn-pho-end-eu3f-keu3f"},
  {id: 7, text:"tều",filename:"bk-hn-pho-end-eu3f-teu3f"},
];
export const WORDS_ENDING_WITH_ech3s: Word[] = [
  {id: 0, text:"ếch",filename:"bk-hn-pho-end-ech3s-title"},
  {id: 1, text:"...ếch",filename:"bk-hn-pho-end-ech3s-title"},
  {id: 2, text:"hếch",filename:"bk-hn-pho-end-ech3s-hech3s"},
  {id: 3, text:"thếch",filename:"bk-hn-pho-end-ech3s-thech3s"},
  {id: 4, text:"lếch",filename:"bk-hn-pho-end-ech3s-lech3s"},
  {id: 5, text:"mếch",filename:"bk-hn-pho-end-ech3s-mech3s"},
  {id: 6, text:"ếch",filename:"bk-hn-pho-end-ech3s-ech3s"},
  {id: 7, text:"chếch",filename:"bk-hn-pho-end-ech3s-chech3s"},
]
export const WORDS_ENDING_WITH_ech3j: Word[] = [
  {id: 0, text:"ệch",filename:"bk-hn-pho-end-ech3j-title"},
  {id: 1, text:"...ệch",filename:"bk-hn-pho-end-ech3j-title"},
  {id: 2, text:"bệch",filename:"bk-hn-pho-end-ech3j-bech3j"},
  {id: 3, text:"kệch",filename:"bk-hn-pho-end-ech3j-kech3j"},
  {id: 4, text:"hệch",filename:"bk-hn-pho-end-ech3j-hech3j"},
  {id: 5, text:"xệch",filename:"bk-hn-pho-end-ech3j-xech3j"},
  {id: 6, text:"nghệch",filename:"bk-hn-pho-end-ech3j-nghech3j"},
  {id: 7, text:"chệch",filename:"bk-hn-pho-end-ech3j-chech3j"},
];
export const WORDS_ENDING_WITH_em3: Word[] = [
  {id: 0, text:"êm",filename:"bk-hn-pho-end-em3-title"},
  {id: 1, text:"...êm",filename:"bk-hn-pho-end-em3-title"},
  {id: 2, text:"đêm",filename:"bk-hn-pho-end-em3-dem73"},
  {id: 3, text:"nêm",filename:"bk-hn-pho-end-em3-nem3"},
  {id: 4, text:"thêm",filename:"bk-hn-pho-end-em3-them3"},
  {id: 5, text:"chêm",filename:"bk-hn-pho-end-em3-chem3"},
  {id: 6, text:"lêm",filename:"bk-hn-pho-end-em3-lem3"},
  {id: 7, text:"têm",filename:"bk-hn-pho-end-em3-tem3"},
];
export const WORDS_ENDING_WITH_en3: Word[] = [
  {id: 0, text:"ên",filename:"bk-hn-pho-end-en3-title"},
  {id: 1, text:"...ên",filename:"bk-hn-pho-end-en3-title"},
  {id: 2, text:"bên",filename:"bk-hn-pho-end-en3-ben3"},
  {id: 3, text:"nên",filename:"bk-hn-pho-end-en3-nen3"},
  {id: 4, text:"lên",filename:"bk-hn-pho-end-en3-len3"},
  {id: 5, text:"hên",filename:"bk-hn-pho-end-en3-hen3"},
  {id: 6, text:"sên",filename:"bk-hn-pho-end-en3-sen3"},
  {id: 7, text:"bên",filename:"bk-hn-pho-end-en3-ben3"},
  {id: 8, text:"tên",filename:"bk-hn-pho-end-en3-ten3"},
  {id: 9, text:"trên",filename:"bk-hn-pho-end-en3-tren3"},
];
export const WORDS_ENDING_WITH_en3s: Word[] = [
  {id: 0, text:"ến",filename:"bk-hn-pho-end-en3s-title"},
  {id: 1, text:"...ến",filename:"bk-hn-pho-end-en3s-title"},
  {id: 2, text:"bến",filename:"bk-hn-pho-end-en3s-ben3s"},
  {id: 3, text:"nến",filename:"bk-hn-pho-end-en3s-nen3s"},
  {id: 4, text:"đến",filename:"bk-hn-pho-end-en3s-den73s"},
  {id: 5, text:"hến",filename:"bk-hn-pho-end-en3s-hen3s"},
  {id: 6, text:"sến",filename:"bk-hn-pho-end-en3s-sen3s"},
  {id: 7, text:"mến",filename:"bk-hn-pho-end-en3s-mens"},
];
export const WORDS_ENDING_WITH_et3s: Word[] = [
  {id: 0, text:"ết",filename:"bk-hn-pho-end-et3s-title"},
  {id: 1, text:"...ết",filename:"bk-hn-pho-end-et3s-title"},
  {id: 2, text:"bết",filename:"bk-hn-pho-end-et3s-bet3s"},
  {id: 3, text:"kết",filename:"bk-hn-pho-end-et3s-ket3s"},
  {id: 4, text:"tết",filename:"bk-hn-pho-end-et3s-tet3s"},
  {id: 5, text:"thết",filename:"bk-hn-pho-end-et3s-thet3s"},
  {id: 6, text:"nết",filename:"bk-hn-pho-end-et3s-net3s"},
  {id: 7, text:"hết",filename:"bk-hn-pho-end-et3s-het3s"},
  {id: 8, text:"rết",filename:"bk-hn-pho-end-et3s-ret3s"},
  {id: 9, text:"phết",filename:"bk-hn-pho-end-et3s-phet3s"},
];
export const WORDS_ENDING_WITH_et3j: Word[] = [
  {id: 0, text:"ệt",filename:"bk-hn-pho-end-et3j-title"},
  {id: 1, text:"...ệt",filename:"bk-hn-pho-end-et3j-title"},
  {id: 2, text:"bệt",filename:"bk-hn-pho-end-et3j-bet3j"},
  {id: 3, text:"phệt",filename:"bk-hn-pho-end-et3j-phet3j"},
  {id: 4, text:"hệt",filename:"bk-hn-pho-end-et3j-het3j"},
  {id: 5, text:"mệt",filename:"bk-hn-pho-end-et3j-met3j"},
  {id: 6, text:"vệt",filename:"bk-hn-pho-end-et3j-vet3j"},
  {id: 7, text:"quệt",filename:"bk-hn-pho-end-et3j-quet3j"},
  {id: 8, text:"trệt",filename:"bk-hn-pho-end-et3j-tret3j"},
  {id: 9, text:"nghệt",filename:"bk-hn-pho-end-et3j-nghet3j"},
];
export const WORDS_ENDING_WITH_ia: Word[] = [
  {id: 0, text:"ia ",filename:"bk-hn-pho-end-ia-title"},
  {id: 1, text:"...ia ",filename:"bk-hn-pho-end-ia-title"},
  {id: 2, text:"bia",filename:"bk-hn-pho-end-ia-bia"},
  {id: 3, text:"kia",filename:"bk-hn-pho-end-ia-kia"},
  {id: 4, text:"nia",filename:"bk-hn-pho-end-ia-nia"},
  {id: 5, text:"thia",filename:"bk-hn-pho-end-ia-thia"},
  {id: 6, text:"chia",filename:"bk-hn-pho-end-ia-chia"},
  {id: 7, text:"ria",filename:"bk-hn-pho-end-ia-ria"},
  {id: 8, text:"tia",filename:"bk-hn-pho-end-ia-tia"},
];
export const WORDS_ENDING_WITH_ias: Word[] = [
  {id: 0, text:"ía",filename:"bk-hn-pho-end-ias-title"},
  {id: 1, text:"...ía",filename:"bk-hn-pho-end-ias-title"},
  {id: 2, text:"bía",filename:"bk-hn-pho-end-ias-bias"},
  {id: 3, text:"mía",filename:"bk-hn-pho-end-ias-mias"},
  {id: 4, text:"vía",filename:"bk-hn-pho-end-ias-vias"},
  {id: 5, text:"tía",filename:"bk-hn-pho-end-ias-tias"},
  {id: 6, text:"xía",filename:"bk-hn-pho-end-ias-xias"},
  {id: 7, text:"khía",filename:"bk-hn-pho-end-ias-khias"},
];
export const WORDS_ENDING_WITH_ichs: Word[] = [
  {id: 0, text:"ích",filename:"bk-hn-pho-end-ichs-title"},
  {id: 1, text:"...ích",filename:"bk-hn-pho-end-ichs-title"},
  {id: 2, text:"bích",filename:"bk-hn-pho-end-ichs-bichs"},
  {id: 3, text:"tích",filename:"bk-hn-pho-end-ichs-tichs"},
  {id: 4, text:"ních",filename:"bk-hn-pho-end-ichs-nichs"},
  {id: 5, text:"mích",filename:"bk-hn-pho-end-ichs-michs"},
  {id: 6, text:"thích",filename:"bk-hn-pho-end-ichs-thichs"},
  {id: 7, text:"đích",filename:"bk-hn-pho-end-ichs-dich7s"},
  {id: 8, text:"nhích",filename:"bk-hn-pho-end-ichs-nhichs"},
  {id: 9, text:"chích",filename:"bk-hn-pho-end-ichs-chichs"},
  {id: 10, text:"phích",filename:"bk-hn-pho-end-ichs-phichs"},
];
export const WORDS_ENDING_WITH_ichj: Word[] = [
  {id: 0, text:"ịch",filename:"bk-hn-pho-end-ichj-title"},
  {id: 1, text:"...ịch",filename:"bk-hn-pho-end-ichj-title"},
  {id: 2, text:"lịch",filename:"bk-hn-pho-end-ichj-lichj"},
  {id: 3, text:"hịch",filename:"bk-hn-pho-end-ichj-hichj"},
  {id: 4, text:"tịch",filename:"bk-hn-pho-end-ichj-tichj"},
  {id: 5, text:"thịch",filename:"bk-hn-pho-end-ichj-thichj"},
  {id: 6, text:"phịch",filename:"bk-hn-pho-end-ichj-phichj"},
];
export const WORDS_ENDING_WITH_inhf: Word[] = [
  {id: 0, text:"ình",filename:"bk-hn-pho-end-inhf-title"},
  {id: 1, text:"...ình",filename:"bk-hn-pho-end-inhf-title"},
  {id: 2, text:"bình",filename:"bk-hn-pho-end-inhf-binhf"},
  {id: 3, text:"thình",filename:"bk-hn-pho-end-inhf-thinhf"},
  {id: 4, text:"lình",filename:"bk-hn-pho-end-inhf-linhf"},
  {id: 5, text:"xình",filename:"bk-hn-pho-end-inhf-xinhf"},
  {id: 6, text:"trình",filename:"bk-hn-pho-end-inhf-trinhf"},
  {id: 7, text:"đình",filename:"bk-hn-pho-end-inhf-dinh7f"},
  {id: 8, text:"hình",filename:"bk-hn-pho-end-inhf-hinhf"},
  {id: 9, text:"mình",filename:"bk-hn-pho-end-inhf-minhf"},
  {id: 10, text:"rình",filename:"bk-hn-pho-end-inhf-rinhf"},
  {id: 11, text:"phình",filename:"bk-hn-pho-end-inhf-phinhf"},
];
export const WORDS_ENDING_WITH_inhj: Word[] = [
  {id: 0, text:"ịnh",filename:"bk-hn-pho-end-inhj-title"},
  {id: 1, text:"...ịnh",filename:"bk-hn-pho-end-inhj-title"},
  {id: 2, text:"nịnh",filename:"bk-hn-pho-end-inhj-ninhj"},
  {id: 3, text:"trịnh",filename:"bk-hn-pho-end-inhj-trinhj"},
  {id: 4, text:"tịnh",filename:"bk-hn-pho-end-inhj-tinhj"},
  {id: 5, text:"định",filename:"bk-hn-pho-end-inhj-dinh7j"},
  {id: 6, text:"vịnh",filename:"bk-hn-pho-end-inhj-vinhj"},
]
export const WORDS_ENDING_WITH_its: Word[] = [
  {id: 0, text:"ít",filename:"bk-hn-pho-end-its-title"},
  {id: 1, text:"...ít",filename:"bk-hn-pho-end-its-title"},
  {id: 2, text:"bít",filename:"bk-hn-pho-end-its-bits"},
  {id: 3, text:"nít",filename:"bk-hn-pho-end-its-nits"},
  {id: 4, text:"chít",filename:"bk-hn-pho-end-its-chits"},
  {id: 5, text:"lít",filename:"bk-hn-pho-end-its-lits"},
  {id: 6, text:"mít",filename:"bk-hn-pho-end-its-mits"},
  {id: 7, text:"vít",filename:"bk-hn-pho-end-its-vits"},
  {id: 8, text:"thít",filename:"bk-hn-pho-end-its-thits"},
  {id: 9, text:"khít",filename:"bk-hn-pho-end-its-khits"},
];
export const WORDS_ENDING_WITH_itj: Word[] = [
  {id: 0, text:"ịt",filename:"bk-hn-pho-end-itj-title"},
  {id: 1, text:"...ịt",filename:"bk-hn-pho-end-itj-title"},
  {id: 2, text:"bịt",filename:"bk-hn-pho-end-itj-bitj"},
  {id: 3, text:"rịt",filename:"bk-hn-pho-end-itj-ritj"},
  {id: 4, text:"vịt",filename:"bk-hn-pho-end-itj-vitj"},
  {id: 5, text:"tịt",filename:"bk-hn-pho-end-itj-titj"},
  {id: 6, text:"thịt",filename:"bk-hn-pho-end-itj-thitj"},
  {id: 7, text:"nịt",filename:"bk-hn-pho-end-itj-nitj"},
];
export const WORDS_ENDING_WITH_ieu3: Word[] = [
  {id: 0, text:"iêu",filename:"bk-hn-pho-end-ieu3-title"},
  {id: 1, text:"...iêu",filename:"bk-hn-pho-end-ieu3-title"},
  {id: 2, text:"liêu",filename:"bk-hn-pho-end-ieu3-lieu3"},
  {id: 3, text:"xiêu",filename:"bk-hn-pho-end-ieu3-xieu3"},
  {id: 4, text:"miêu",filename:"bk-hn-pho-end-ieu3-mieu3"},
  {id: 5, text:"phiêu",filename:"bk-hn-pho-end-ieu3-phieu3"},
  {id: 6, text:"thiêu",filename:"bk-hn-pho-end-ieu3-thieu3"},
  {id: 7, text:"siêu",filename:"bk-hn-pho-end-ieu3-sieu3"},
  {id: 8, text:"niêu",filename:"bk-hn-pho-end-ieu3-nieu3"},
  {id: 9, text:"kiêu",filename:"bk-hn-pho-end-ieu3-kieu3"},
  {id: 10, text:"tiêu",filename:"bk-hn-pho-end-ieu3-tieu3"},
];
export const WORDS_ENDING_WITH_ieu3f: Word[] = [
  {id: 0, text:"iều",filename:"bk-hn-pho-end-ieu3f-title"},
  {id: 1, text:"...iều",filename:"bk-hn-pho-end-ieu3f-title"},
  {id: 2, text:"diều",filename:"bk-hn-pho-end-ieu3f-dieu3f"},
  {id: 3, text:"kiều",filename:"bk-hn-pho-end-ieu3f-kieu3f"},
  {id: 4, text:"điều",filename:"bk-hn-pho-end-ieu3f-dieu73f"},
  {id: 5, text:"chiều",filename:"bk-hn-pho-end-ieu3f-chieu3f"},
  {id: 6, text:"tiều",filename:"bk-hn-pho-end-ieu3f-tieu3f"},
  {id: 7, text:"nhiều",filename:"bk-hn-pho-end-ieu3f-nhieu3f"},
  {id: 8, text:"liều",filename:"bk-hn-pho-end-ieu3f-lieu3f"},
];
export const WORDS_ENDING_WITH_ieu3s: Word[] = [
  {id: 0, text:"iếu",filename:"bk-hn-pho-end-ieu3s-title"},
  {id: 1, text:"...iếu",filename:"bk-hn-pho-end-ieu3s-title"},
  {id: 2, text:"biếu",filename:"bk-hn-pho-end-ieu3s-bieu3s"},
  {id: 3, text:"kiếu",filename:"bk-hn-pho-end-ieu3s-kieu3s"},
  {id: 4, text:"hiếu",filename:"bk-hn-pho-end-ieu3s-hieu3s"},
  {id: 5, text:"thiếu",filename:"bk-hn-pho-end-ieu3s-thieu3s"},
  {id: 6, text:"phiếu",filename:"bk-hn-pho-end-ieu3s-phieu3s"},
  {id: 7, text:"điếu",filename:"bk-hn-pho-end-ieu3s-dieu73s"},
  {id: 8, text:"miếu",filename:"bk-hn-pho-end-ieu3s-mieu3s"},
  {id: 9, text:"chiếu",filename:"bk-hn-pho-end-ieu3s-chieu3s"},
  {id: 10, text:"khiếu",filename:"bk-hn-pho-end-ieu3s-khieu3s"},
];
export const WORDS_ENDING_WITH_ieu3r: Word[] = [
  {id: 0, text:"iểu",filename:"bk-hn-pho-end-ieu3r-title"},
  {id: 1, text:"...iểu",filename:"bk-hn-pho-end-ieu3r-title"},
  {id: 2, text:"biểu",filename:"bk-hn-pho-end-ieu3r-bieu3r"},
  {id: 3, text:"hiểu",filename:"bk-hn-pho-end-ieu3r-hieu3r"},
  {id: 4, text:"kiểu",filename:"bk-hn-pho-end-ieu3r-kieu3r"},
  {id: 5, text:"điểu",filename:"bk-hn-pho-end-ieu3r-dieu73r"},
  {id: 6, text:"chiểu",filename:"bk-hn-pho-end-ieu3r-chieu3r"},
];
export const WORDS_ENDING_WITH_iem3: Word[] = [
  {id: 0, text:"iêm",filename:"bk-hn-pho-end-iem3-title"},
  {id: 1, text:"...iêm",filename:"bk-hn-pho-end-iem3-title"},
  {id: 2, text:"niêm",filename:"bk-hn-pho-end-iem3-niem3"},
  {id: 3, text:"liêm",filename:"bk-hn-pho-end-iem3-liem3"},
  {id: 4, text:"diêm",filename:"bk-hn-pho-end-iem3-diem3"},
  {id: 5, text:"nghiêm",filename:"bk-hn-pho-end-iem3-nghiem3"},
  {id: 6, text:"viêm",filename:"bk-hn-pho-end-iem3-viem3"},
  {id: 7, text:"tiêm",filename:"bk-hn-pho-end-iem3-tiem3"},
  {id: 8, text:"kiêm",filename:"bk-hn-pho-end-iem3-kiem3"},
];
export const WORDS_ENDING_WITH_iem3s: Word[] = [
  {id: 0, text:"iếm",filename:"bk-hn-pho-end-iem3s-title"},
  {id: 1, text:"...iếm",filename:"bk-hn-pho-end-iem3s-title"},
  {id: 2, text:"biếm",filename:"bk-hn-pho-end-iem3s-biem3s"},
  {id: 3, text:"chiếm",filename:"bk-hn-pho-end-iem3s-chiem3s"},
  {id: 4, text:"khiếm",filename:"bk-hn-pho-end-iem3s-khiem3s"},
  {id: 5, text:"liếm",filename:"bk-hn-pho-end-iem3s-liem3s"},
  {id: 6, text:"kiếm",filename:"bk-hn-pho-end-iem3s-kiem3s"},
  {id: 7, text:"hiếm",filename:"bk-hn-pho-end-iem3s-hiem3s"},
  {id: 8, text:"chiếm",filename:"bk-hn-pho-end-iem3s-chiem3s"},
]
export const WORDS_ENDING_WITH_iem3f: Word[] = [
  {id: 0, text:"iềm",filename:"bk-hn-pho-end-iem3f-title"},
  {id: 1, text:"...iềm",filename:"bk-hn-pho-end-iem3f-title"},
  {id: 2, text:"niềm",filename:"bk-hn-pho-end-iem3f-niem3f"},
  {id: 3, text:"liềm",filename:"bk-hn-pho-end-iem3f-liem3f"},
  {id: 4, text:"tiềm",filename:"bk-hn-pho-end-iem3f-tiem3f"},
  {id: 5, text:"điềm",filename:"bk-hn-pho-end-iem3f-diem73f"},
  {id: 6, text:"kiềm",filename:"bk-hn-pho-end-iem3f-kiem3f"},
];
export const WORDS_ENDING_WITH_ien3: Word[] = [
  {id: 0, text:"iên",filename:"bk-hn-pho-end-ien3-title"},
  {id: 1, text:"...iên",filename:"bk-hn-pho-end-ien3-title"},
  {id: 2, text:"biên",filename:"bk-hn-pho-end-ien3-bien3"},
  {id: 3, text:"tiên",filename:"bk-hn-pho-end-ien3-tien3"},
  {id: 4, text:"liên",filename:"bk-hn-pho-end-ien3-lien3"},
  {id: 5, text:"phiên",filename:"bk-hn-pho-end-ien3-phien3"},
  {id: 6, text:"xiên",filename:"bk-hn-pho-end-ien3-xien3"},
  {id: 7, text:"khiên",filename:"bk-hn-pho-end-ien3-khien3"},
  {id: 8, text:"hiên",filename:"bk-hn-pho-end-ien3-hien3"},
  {id: 9, text:"viên",filename:"bk-hn-pho-end-ien3-vien3"},
  {id: 10, text:"chiên",filename:"bk-hn-pho-end-ien3-chien3"},
];
export const WORDS_ENDING_WITH_ien3s: Word[] = [
  {id: 0, text:"iến",filename:"bk-hn-pho-end-ien3s-title"},
  {id: 1, text:"...iến",filename:"bk-hn-pho-end-ien3s-title"},
  {id: 2, text:"khiến",filename:"bk-hn-pho-end-ien3s-khien3s"},
  {id: 3, text:"kiến",filename:"bk-hn-pho-end-ien3s-kien3s"},
  {id: 4, text:"tiến",filename:"bk-hn-pho-end-ien3s-tien3s"},
  {id: 5, text:"phiến",filename:"bk-hn-pho-end-ien3s-phien3s"},
  {id: 6, text:"biến",filename:"bk-hn-pho-end-ien3s-bien3s"},
  {id: 7, text:" hiến",filename:"bk-hn-pho-end-ien3s-hien3s"},
  {id: 8, text:"miến",filename:"bk-hn-pho-end-ien3 s-mien3s"},
  {id: 9, text:"nghiến",filename:"bk-hn-pho-end-ien3s-nghien3s"},
  {id: 10, text:"chiến",filename:"bk-hn-pho-end-ien3s-chien3s"},
];
export const WORDS_ENDING_WITH_iep3s: Word[] = [
  {id: 0, text:"iếp",filename:"bk-hn-pho-end-iep3s-title"},
  {id: 1, text:"...iếp",filename:"bk-hn-pho-end-iep3s-title"},
  {id: 2, text:"liếp",filename:"bk-hn-pho-end-iep3s-liep3s"},
  {id: 3, text:"kiếp",filename:"bk-hn-pho-end-iep3s-kiep3s"},
  {id: 4, text:"diếp",filename:"bk-hn-pho-end-iep3s-diep3s"},
  {id: 5, text:"khiếp",filename:"bk-hn-pho-end-iep3s-khiep3s"},
  {id: 6, text:"tiếp",filename:"bk-hn-pho-end-iep3s-tiep3s"},
  {id: 7, text:"thiếp",filename:"bk-hn-pho-end-iep3s-thiep3s"},
];
export const WORDS_ENDING_WITH_iep3j: Word[] = [
  {id: 0, text:"iệp",filename:"bk-hn-pho-end-iep3j-title"},
  {id: 1, text:"...iệp",filename:"bk-hn-pho-end-iep3j-title"},
  {id: 2, text:"tiệp",filename:"bk-hn-pho-end-iep3j-tiep3j"},
  {id: 3, text:"điệp",filename:"bk-hn-pho-end-iep3j-diep73j"},
  {id: 4, text:"nghiệp",filename:"bk-hn-pho-end-iep3j-nghiep3j"},
  {id: 5, text:"diệp",filename:"bk-hn-pho-end-iep3j-diep3j"},
  {id: 6, text:"thiệp",filename:"bk-hn-pho-end-iep3j-thiep3j"},
  {id: 7, text:"hiệp",filename:"bk-hn-pho-end-iep3j-hiep3j"}
];



export const WORDS_ENDING_WITH_iet3s: Word[] = [
  {id: 0, text:"iết",filename:"bk-hn-pho-end-iet3s-title"},
  {id: 1, text:"...iết",filename:"bk-hn-pho-end-iet3s-title"},
  {id: 2, text:"biết",filename:"bk-hn-pho-end-iet3s-biet3s"},
  {id: 3, text:"kiết",filename:"bk-hn-pho-end-iet3s-kiet3s"},
  {id: 4, text:"niết",filename:"bk-hn-pho-end-iet3s-niet3s"},
  {id: 5, text:"triết",filename:"bk-hn-pho-end-iet3s-triet3s"},
  {id: 6, text:"miết",filename:"bk-hn-pho-end-iet3s-miet3s"},
  {id: 7, text:"viết",filename:"bk-hn-pho-end-iet3s-viet3s"},
  {id: 8, text:"siết",filename:"bk-hn-pho-end-iet3s-siet3s"},
];
export const WORDS_ENDING_WITH_iet3j: Word[] = [
  {id: 0, text:"iệt",filename:"bk-hn-pho-end-iet3j-title"},
  {id: 1, text:"...iệt",filename:"bk-hn-pho-end-iet3j-title"},
  {id: 2, text:"biệt",filename:"bk-hn-pho-end-iet3j-biet3j"},
  {id: 3, text:"miệt",filename:"bk-hn-pho-end-iet3j-miet3j"},
  {id: 4, text:"phiệt",filename:"bk-hn-pho-end-iet3j-phiet3j"},
  {id: 5, text:"thiệt",filename:"bk-hn-pho-end-iet3j-thiet3j"},
  {id: 6, text:"việt",filename:"bk-hn-pho-end-iet3j-viet3j"},
  {id: 7, text:"kiệt",filename:"bk-hn-pho-end-iet3j-kiet3j"},
];
export const WORDS_ENDING_WITH_oa: Word[] = [
  {id: 0, text:"oa",filename:"bk-hn-pho-end-oa-title"},
  {id: 1, text:"...oa",filename:"bk-hn-pho-end-oa-title"},
  {id: 2, text:"loa",filename:"bk-hn-pho-end-oa-loa"},
  {id: 3, text:"moa",filename:"bk-hn-pho-end-oa-moa"},
  {id: 4, text:"thoa",filename:"bk-hn-pho-end-oa-thoa"},
  {id: 5, text:"toa",filename:"bk-hn-pho-end-oa-toa"},
  {id: 6, text:"khoa",filename:"bk-hn-pho-end-oa-khoa"},
  {id: 7, text:"hoa",filename:"bk-hn-pho-end-oa-hoa"},
  {id: 8, text:"xoa",filename:"bk-hn-pho-end-oa-xoa"},
];
export const WORDS_ENDING_WITH_oaf: Word[] = [
  {id: 0, text:"òa",filename:"bk-hn-pho-end-oaf-title"},
  {id: 1, text:"...òa",filename:"bk-hn-pho-end-oaf-title"},
  {id: 2, text:"hòa",filename:"bk-hn-pho-end-oaf-hoaf"},
  {id: 3, text:"lòa",filename:"bk-hn-pho-end-oaf-loaf"},
  {id: 4, text:"tòa",filename:"bk-hn-pho-end-oaf-toaf"},
  {id: 5, text:"nhòa",filename:"bk-hn-pho-end-oaf-nhoaf"},
  {id: 6, text:"thòa",filename:"bk-hn-pho-end-oaf-thoaf"},
];
export const WORDS_ENDING_WITH_oif: Word[] = [
  {id: 0, text:"òi",filename:"bk-hn-pho-end-oif-title"},
  {id: 1, text:"...òi",filename:"bk-hn-pho-end-oif-title"},
  {id: 2, text:"còi",filename:"bk-hn-pho-end-oif-coif"},
  {id: 3, text:"ròi",filename:"bk-hn-pho-end-oif-roif"},
  {id: 4, text:"lòi",filename:"bk-hn-pho-end-oif-loif"},
  {id: 5, text:"phòi",filename:"bk-hn-pho-end-oif-phoif"},
  {id: 6, text:"nòi",filename:"bk-hn-pho-end-oif-noif"},
  {id: 7, text:"đòi",filename:"bk-hn-pho-end-oif-doi7f"},
  {id: 8, text:"vòi",filename:"bk-hn-pho-end-oif-voif"},
  {id: 9, text:"ngòi",filename:"bk-hn-pho-end-oif-ngoif"},
  {id: 10, text:"chòi",filename:"bk-hn-pho-end-oif-choif"},
];
export const WORDS_ENDING_WITH_oir: Word[] = [
  {id: 0, text:"ỏi",filename:"bk-hn-pho-end-oir-title"},
  {id: 1, text:"...ỏi",filename:"bk-hn-pho-end-oir-title"},
  {id: 2, text:"hỏi",filename:"bk-hn-pho-end-oir-hoir"},
  {id: 3, text:"mỏi",filename:"bk-hn-pho-end-oir-moir"},
  {id: 4, text:"thỏi",filename:"bk-hn-pho-end-oir-thoir"},
  {id: 5, text:"tỏi",filename:"bk-hn-pho-end-oir-toir"},
  {id: 6, text:"chỏi",filename:"bk-hn-pho-end-oir-choir"},
  {id: 7, text:"khỏi",filename:"bk-hn-pho-end-oir-khoir"},
];
export const WORDS_ENDING_WITH_ocs: Word[] = [
  {id: 0, text:"óc",filename:"bk-hn-pho-end-ocs-title"},
  {id: 1, text:"...óc",filename:"bk-hn-pho-end-ocs-title"},
  {id: 2, text:"bóc",filename:"bk-hn-pho-end-ocs-bocs"},
  {id: 3, text:"nóc",filename:"bk-hn-pho-end-ocs-nocs"},
  {id: 4, text:"tóc",filename:"bk-hn-pho-end-ocs-tocs"},
  {id: 5, text:"thóc",filename:"bk-hn-pho-end-ocs-thocs"},
  {id: 6, text:"lóc",filename:"bk-hn-pho-end-ocs-locs"},
  {id: 7, text:"móc",filename:"bk-hn-pho-end-ocs-mocs"},
  {id: 8, text:"sóc",filename:"bk-hn-pho-end-ocs-socs"},
  {id: 9, text:"nhóc",filename:"bk-hn-pho-end-ocs-nhocs"},
  {id: 10, text:"tróc",filename:"bk-hn-pho-end-ocs-trocs"},
  {id: 11, text:"ngóc",filename:"bk-hn-pho-end-ocs-ngocs"},
  {id: 12, text:"khóc",filename:"bk-hn-pho-end-ocs-khocs"},
];
// export const WORDS_ENDING_WITH_iep3j: Word[] = [
//   {id: 0, text:"...ọc",filename:"bk-hn-vowel-word-end-ocj-title"},
//   {id: 0, text:"bọc",filename:"bk-hn-pho-end-ocj-bocj"},
//   {id: 0, text:"mọc",filename:"bk-hn-pho-end-ocj-mocj"},
//   {id: 0, text:"rọc",filename:"bk-hn-pho-end-ocj-rocj"},
//   {id: 0, text:"trọc",filename:"bk-hn-pho-end-ocj-trocj"},
//   {id: 0, text:"tọc",filename:"bk-hn-pho-end-ocj-tocj"},
//   {id: 0, text:"nhọc",filename:"bk-hn-pho-end-ocj-nhocj"},
//   {id: 0, text:"nọc",filename:"bk-hn-pho-end-ocj-nocj"},
//   {id: 0, text:"chọc",filename:"bk-hn-pho-end-ocj-chocj"},
//   {id: 0, text:"ngọc",filename:"bk-hn-pho-end-ocj-ngocj"},
//   {id: 0, text:"đọc",filename:"bk-hn-pho-end-ocj-doc7j"},
//   {id: 0, text:"cọc",filename:"bk-hn-pho-end-ocj-cocj"},
//   {id: 0, text:"lọc",filename:"bk-hn-pho-end-ocj-locj"},
//   {id: 0, text:"học",filename:"bk-hn-pho-end-ocj-hocj"},
// ];
export const WORDS_ENDING_WITH_ocj: Word[] = [
  {id: 0, text:"ọc",filename:"bk-hn-pho-end-ocj-title"},
  {id: 1, text:"...ọc",filename:"bk-hn-pho-end-ocj-title"},
  {id: 2, text:"cọc",filename:"bk-hn-pho-end-ocj-cocj"},
  {id: 3, text:"đọc",filename:"bk-hn-pho-end-ocj-doc7j"},
  {id: 4, text:"học",filename:"bk-hn-pho-end-ocj-hocj"},
  {id: 5, text:"lọc",filename:"bk-hn-pho-end-ocj-locj"},
  {id: 6, text:"nọc",filename:"bk-hn-pho-end-ocj-nocj"},
  {id: 7, text:"nhọc",filename:"bk-hn-pho-end-ocj-nhocj"},
  {id: 8, text:"ngọc",filename:"bk-hn-pho-end-ocj-ngocj"},
  {id: 9, text:"chọc",filename:"bk-hn-pho-end-ocj-chocj"},
];
export const WORDS_ENDING_WITH_om: Word[] = [
  {id: 0, text:"om",filename:"bk-hn-pho-end-om-title"},
  {id: 1, text:"...om",filename:"bk-hn-pho-end-om-title"},
  {id: 2, text:"bom",filename:"bk-hn-pho-end-om-bom"},
  {id: 3, text:"lom",filename:"bk-hn-pho-end-om-lom"},
  {id: 4, text:"khom",filename:"bk-hn-pho-end-om-khom"},
  {id: 5, text:"com",filename:"bk-hn-pho-end-om-com"},
  {id: 6, text:"tom",filename:"bk-hn-pho-end-om-tom"},
  {id: 7, text:"nom",filename:"bk-hn-pho-end-om-nom"},
];
export const WORDS_ENDING_WITH_oms: Word[] = [
  {id: 0, text:"óm",filename:"bk-hn-pho-end-oms-title"},
  {id: 1, text:"...óm",filename:"bk-hn-pho-end-oms-title"},
  {id: 2, text:"khóm",filename:"bk-hn-pho-end-oms-khoms"},
  {id: 3, text:"xóm",filename:"bk-hn-pho-end-oms-xoms"},
  {id: 4, text:"lóm",filename:"bk-hn-pho-end-oms-loms"},
  {id: 5, text:"đóm",filename:"bk-hn-pho-end-oms-dom7s"},
  {id: 6, text:"tóm",filename:"bk-hn-pho-end-oms-toms"},
  {id: 7, text:"móm",filename:"bk-hn-pho-end-oms-moms"},
];
export const WORDS_ENDING_WITH_onf: Word[] = [
  {id: 0, text:"òn",filename:"bk-hn-pho-end-onf-title"},
  {id: 1, text:"...òn",filename:"bk-hn-pho-end-onf-title"},
  {id: 2, text:"còn",filename:"bk-hn-pho-end-onf-conf"},
  {id: 3, text:"bòn",filename:"bk-hn-pho-end-onf-bonf"},
  {id: 4, text:"hòn",filename:"bk-hn-pho-end-onf-honf"},
  {id: 5, text:"dòn",filename:"bk-hn-pho-end-onf-donf"},
  {id: 6, text:"tròn",filename:"bk-hn-pho-end-onf-tronf"},
  {id: 7, text:"mòn",filename:"bk-hn-pho-end-onf-monf"},
];
export const WORDS_ENDING_WITH_onj: Word[] = [
  {id: 0, text:"ọn",filename:"bk-hn-pho-end-onj-title"},
  {id: 1, text:"...ọn",filename:"bk-hn-pho-end-onj-title"},
  {id: 2, text:"chọn",filename:"bk-hn-pho-end-onj-chonj"},
  {id: 3, text:"lọn",filename:"bk-hn-pho-end-onj-lonj"},
  {id: 4, text:"dọn",filename:"bk-hn-pho-end-onj-donj"},
  {id: 5, text:"bọn",filename:"bk-hn-pho-end-onj-bonj"},
  {id: 6, text:"rọn",filename:"bk-hn-pho-end-onj-ronj"},
  {id: 7, text:"gọn",filename:"bk-hn-pho-end-onj-gonj"},
  {id: 8, text:"nhọn",filename:"bk-hn-pho-end-onj-nhonj"},
  {id: 9, text:"trọn",filename:"bk-hn-pho-end-onj-tronj"},
];
export const WORDS_ENDING_WITH_ong: Word[] = [
  {id: 0, text:"ong",filename:"bk-hn-pho-end-ong-title"},
  {id: 1, text:"...ong",filename:"bk-hn-pho-end-ong-title"},
  {id: 2, text:"bong",filename:"bk-hn-pho-end-ong-bong"},
  {id: 3, text:"long",filename:"bk-hn-pho-end-ong-long"},
  {id: 4, text:"cong",filename:"bk-hn-pho-end-ong-cong"},
  {id: 5, text:"mong",filename:"bk-hn-pho-end-ong-mong"},
  {id: 6, text:"xong",filename:"bk-hn-pho-end-ong-xong"},
  {id: 7, text:"dong",filename:"bk-hn-pho-end-ong-dong"},
  {id: 8, text:"đong",filename:"bk-hn-pho-end-ong-dong7"},
  {id: 9, text:"rong",filename:"bk-hn-pho-end-ong-rong"},
  {id: 10, text:"trong",filename:"bk-hn-pho-end-ong-trong"},
];
export const WORDS_ENDING_WITH_ongs: Word[] = [
  {id: 0, text:"óng",filename:"bk-hn-pho-end-ongs-title"},
  {id: 1, text:"...óng",filename:"bk-hn-pho-end-ongs-title"},
  {id: 2, text:"bóng",filename:"bk-hn-pho-end-ongs-bongs"},
  {id: 3, text:"cóng",filename:"bk-hn-pho-end-ongs-congs"},
  {id: 4, text:"hóng",filename:"bk-hn-pho-end-ongs-hongs"},
  {id: 5, text:"nóng",filename:"bk-hn-pho-end-ongs-nongs"},
  {id: 6, text:"móng",filename:"bk-hn-pho-end-ongs-mongs"},
  {id: 7, text:"đóng",filename:"bk-hn-pho-end-ongs-dong7s"},
  {id: 8, text:"ngóng",filename:"bk-hn-pho-end-ongs-ngongs"},
  {id: 9, text:"phóng",filename:"bk-hn-pho-end-ongs-phongs"},
  {id: 10, text:"chóng",filename:"bk-hn-pho-end-ongs-chongs"},
];
export const WORDS_ENDING_WITH_ops: Word[] = [
  {id: 0, text:"óp",filename:"bk-hn-pho-end-ops-title"},
  {id: 1, text:"...óp",filename:"bk-hn-pho-end-ops-title"},
  {id: 2, text:"bóp",filename:"bk-hn-pho-end-ops-bops"},
  {id: 3, text:"tóp",filename:"bk-hn-pho-end-ops-tops"},
  {id: 4, text:"chóp",filename:"bk-hn-pho-end-ops-chops"},
  {id: 5, text:"móp",filename:"bk-hn-pho-end-ops-mops"},
  {id: 6, text:"cóp",filename:"bk-hn-pho-end-ops-cops"},
  {id: 7, text:"hóp",filename:"bk-hn-pho-end-ops-hops"},
  {id: 8, text:"thóp",filename:"bk-hn-pho-end-ops-thops"},
];
export const WORDS_ENDING_WITH_opj: Word[] = [
  {id: 0, text:"ọp",filename:"bk-hn-pho-end-opj-title"},
  {id: 1, text:"...ọp",filename:"bk-hn-pho-end-opj-title"},
  {id: 2, text:"cọp",filename:"bk-hn-pho-end-opj-copj"},
  {id: 3, text:"họp",filename:"bk-hn-pho-end-opj-hopj"},
  {id: 4, text:"xọp",filename:"bk-hn-pho-end-opj-xopj"},
  {id: 5, text:"gọp",filename:"bk-hn-pho-end-opj-gopj"},
  {id: 6, text:"thọp",filename:"bk-hn-pho-end-opj-thopj"},
];
export const WORDS_ENDING_WITH_ots: Word[] = [
  {id: 0, text:"ót",filename:"bk-hn-pho-end-ots-title"},
  {id: 1, text:"...ót",filename:"bk-hn-pho-end-ots-title"},
  {id: 2, text:"cót",filename:"bk-hn-pho-end-ots-cots"},
  {id: 3, text:"bót",filename:"bk-hn-pho-end-ots-bots"},
  {id: 4, text:"mót",filename:"bk-hn-pho-end-ots-mots"},
  {id: 5, text:"rót",filename:"bk-hn-pho-end-ots-rots"},
  {id: 6, text:"xót",filename:"bk-hn-pho-end-ots-xots"},
  {id: 7, text:"hót",filename:"bk-hn-pho-end-ots-hots"},
  {id: 8, text:"lót",filename:"bk-hn-pho-end-ots-lots"},
  {id: 9, text:"sót",filename:"bk-hn-pho-end-ots-sots"},
  {id: 10, text:"vót",filename:"bk-hn-pho-end-ots-vots"},
  {id: 11, text:"ngót",filename:"bk-hn-pho-end-ots-ngots"},
  {id: 12, text:"trót",filename:"bk-hn-pho-end-ots-trots"},
];
export const WORDS_ENDING_WITH_otj: Word[] = [
  {id: 0, text:"ọt",filename:"bk-hn-pho-end-otj-title"},
  {id: 1, text:"...ọt",filename:"bk-hn-pho-end-otj-title"},
  {id: 2, text:"bọt",filename:"bk-hn-pho-end-otj-botj"},
  {id: 3, text:"thọt",filename:"bk-hn-pho-end-otj-thotj"},
  {id: 4, text:"tọt",filename:"bk-hn-pho-end-otj-totj"},
  {id: 5, text:"chọt",filename:"bk-hn-pho-end-otj-chotj"},
  {id: 6, text:"phọt",filename:"bk-hn-pho-end-otj-photj"},
  {id: 7, text:"mọt",filename:"bk-hn-pho-end-otj-motj"},
  {id: 8, text:"gọt",filename:"bk-hn-pho-end-otj-gotj"},
  {id: 9, text:"lọt",filename:"bk-hn-pho-end-otj-lotj"},
  {id: 10, text:"sọt",filename:"bk-hn-pho-end-otj-sotj"},
  {id: 11, text:"nhọt",filename:"bk-hn-pho-end-otj-nhotj"},
  {id: 12, text:"ngọt",filename:"bk-hn-pho-end-otj-ngotj"},
];
export const WORDS_ENDING_WITH_oang: Word[] = [
  {id: 0, text:"oang",filename:"bk-hn-pho-end-oang-title"},
  {id: 1, text:"...oang",filename:"bk-hn-pho-end-oang-title"},
  {id: 2, text:"loang",filename:"bk-hn-pho-end-oang-loang"},
  {id: 3, text:"khoang",filename:"bk-hn-pho-end-oang-khoang"},
  {id: 4, text:"choang",filename:"bk-hn-pho-end-oang-choang"},
  {id: 5, text:"thoang",filename:"bk-hn-pho-end-oang-thoang"},
  {id: 6, text:"xoang",filename:"bk-hn-pho-end-oang-xoang"},
  {id: 7, text:"hoang",filename:"bk-hn-pho-end-oang-hoang"},
];
export const WORDS_ENDING_WITH_oangs: Word[] = [
  {id: 0, text:"oáng",filename:"bk-hn-pho-end-oangs-title"},
  {id: 1, text:"...oáng",filename:"bk-hn-pho-end-oangs-title"},
  {id: 2, text:"loáng",filename:"bk-hn-pho-end-oangs-loangs"},
  {id: 3, text:"thoáng",filename:"bk-hn-pho-end-oangs-thoangs"},
  {id: 4, text:"choáng",filename:"bk-hn-pho-end-oangs-choangs"},
  {id: 5, text:"khoáng",filename:"bk-hn-pho-end-oangs-khoangs"},
  {id: 6, text:"toáng",filename:"bk-hn-pho-end-oangs-toangs"},
];
export const WORDS_ENDING_WITH_oi4x: Word[] = [
  {id: 0, text:"ỗi",filename:"bk-hn-pho-end-oi4x-title"},
  {id: 1, text:"...ỗi",filename:"bk-hn-pho-end-oi4x-title"},
  {id: 2, text:"mỗi",filename:"bk-hn-pho-end-oi4x-moi4x"},
  {id: 3, text:"lỗi",filename:"bk-hn-pho-end-oi4x-loi4x"},
  {id: 4, text:"rỗi",filename:"bk-hn-pho-end-oi4x-roi4x"},
  {id: 5, text:"dỗi",filename:"bk-hn-pho-end-oi4x-doi4x"},
  {id: 6, text:"nỗi",filename:"bk-hn-pho-end-oi4x-noi4x"},
  {id: 7, text:"cỗi",filename:"bk-hn-pho-end-oi4x-coi4x"},
  {id: 8, text:"trỗi",filename:"bk-hn-pho-end-oi4x-troi4x"},
];
export const WORDS_ENDING_WITH_oi4j: Word[] = [
  {id: 0, text:"ội",filename:"bk-hn-pho-end-oi4j-title"},
  {id: 1, text:"...ội",filename:"bk-hn-pho-end-oi4j-title"},
  {id: 2, text:"bội",filename:"bk-hn-pho-end-oi4j-boi4j"},
  {id: 3, text:"nội",filename:"bk-hn-pho-end-oi4j-noi4j"},
  {id: 4, text:"tội",filename:"bk-hn-pho-end-oi4j-toi4j"},
  {id: 5, text:"vội",filename:"bk-hn-pho-end-oi4j-voi4j"},
  {id: 6, text:"hội",filename:"bk-hn-pho-end-oi4j-hoi4j"},
  {id: 7, text:"cội",filename:"bk-hn-pho-end-oi4j-coi4j"},
  {id: 8, text:"gội",filename:"bk-hn-pho-end-oi4j-goi4j"},
  {id: 9, text:"lội",filename:"bk-hn-pho-end-oi4j-loi4j"},
  {id: 10, text:"trội",filename:"bk-hn-pho-end-oi4j-troi4j"},
];
export const WORDS_ENDING_WITH_oc4s: Word[] = [
  {id: 0, text:"ốc",filename:"bk-hn-pho-end-oc4s-title"},
  {id: 1, text:"...ốc",filename:"bk-hn-pho-end-oc4s-title"},
  {id: 2, text:"cốc",filename:"bk-hn-pho-end-oc4s-coc4s"},
  {id: 3, text:"bốc",filename:"bk-hn-pho-end-oc4s-boc4s"},
  {id: 4, text:"hốc",filename:"bk-hn-pho-end-oc4s-hoc4s"},
  {id: 5, text:"mốc",filename:"bk-hn-pho-end-oc4s-moc4s"},
  {id: 6, text:"dốc",filename:"bk-hn-pho-end-oc4s-doc4s"},
  {id: 7, text:"tốc",filename:"bk-hn-pho-end-oc4s-toc4s"},
  {id: 8, text:"vốc",filename:"bk-hn-pho-end-oc4s-voc4s"},
  {id: 9, text:"xốc",filename:"bk-hn-pho-end-oc4s-xoc4s"},
  {id: 10, text:"ngốc",filename:"bk-hn-pho-end-oc4s-ngoc4s"},
  {id: 11, text:"chốc",filename:"bk-hn-pho-end-oc4s-choc4s"},
];
export const WORDS_ENDING_WITH_oc4j: Word[] = [
  {id: 0, text:"ộc",filename:"bk-hn-pho-end-oc4j-title"},
  {id: 1, text:"...ộc",filename:"bk-hn-pho-end-oc4j-title"},
  {id: 2, text:"lộc",filename:"bk-hn-pho-end-oc4j-loc4j"},
  {id: 3, text:"mộc",filename:"bk-hn-pho-end-oc4j-moc4j"},
  {id: 4, text:"cộc",filename:"bk-hn-pho-end-oc4j-coc4j"},
  {id: 5, text:"tộc",filename:"bk-hn-pho-end-oc4j-toc4j"},
  {id: 6, text:"xộc",filename:"bk-hn-pho-end-oc4j-xoc4j"},
];
export const WORDS_ENDING_WITH_om4r: Word[] = [
  {id: 0, text:"ổm",filename:"bk-hn-pho-end-om4r-title"},
  {id: 1, text:"...ổm",filename:"bk-hn-pho-end-om4r-title"},
  {id: 2, text:"hổm",filename:"bk-hn-pho-end-om4r-hom4r"},
  {id: 3, text:"lổm",filename:"bk-hn-pho-end-om4r-lom4r"},
  {id: 4, text:"nhổm",filename:"bk-hn-pho-end-om4r-nhom4r"},
  {id: 5, text:"xổm",filename:"bk-hn-pho-end-om4r-xom4r"},
  {id: 6, text:"dổm",filename:"bk-hn-pho-end-om4r-dom4r"},
];
export const WORDS_ENDING_WITH_om4j: Word[] = [
  {id: 0, text:"ộm",filename:"bk-hn-pho-end-om4j-title"},
  {id: 1, text:"...ộm",filename:"bk-hn-pho-end-om4j-title"},
  {id: 2, text:"cộm",filename:"bk-hn-pho-end-om4j-com4j"},
  {id: 3, text:"rộm",filename:"bk-hn-pho-end-om4j-rom4j"},
  {id: 4, text:"nộm",filename:"bk-hn-pho-end-om4j-nom4j"},
  {id: 5, text:"độm",filename:"bk-hn-pho-end-om4j-dom74j"},
  {id: 6, text:"trộm",filename:"bk-hn-pho-end-om4j-trom4j"},
];
export const WORDS_ENDING_WITH_ong4: Word[] = [
  {id: 0, text:"ông",filename:"bk-hn-pho-end-ong4-title"},
  {id: 1, text:"...ông",filename:"bk-hn-pho-end-ong4-title"},
  {id: 2, text:"công",filename:"bk-hn-pho-end-ong4-cong4"},
  {id: 3, text:"bông",filename:"bk-hn-pho-end-ong4-bong4"},
  {id: 4, text:"lông",filename:"bk-hn-pho-end-ong4-long4"},
  {id: 5, text:"tông",filename:"bk-hn-pho-end-ong4-tong4"},
  {id: 6, text:"đông",filename:"bk-hn-pho-end-ong4-dong74"},
  {id: 7, text:"nông",filename:"bk-hn-pho-end-ong4-nong4"},
  {id: 8, text:"sông",filename:"bk-hn-pho-end-ong4-song4"},
  {id: 9, text:"xông",filename:"bk-hn-pho-end-ong4-xong4"},
  {id: 10, text:"thông",filename:"bk-hn-pho-end-ong4-thong4"},
  {id: 11, text:"trông",filename:"bk-hn-pho-end-ong4-trong4"},
  {id: 12, text:"không",filename:"bk-hn-pho-end-ong4-khong4"},
];
export const WORDS_ENDING_WITH_ong4s: Word[] = [
  {id: 0, text:"ống",filename:"bk-hn-pho-end-ong4s-title"},
  {id: 1, text:"...ống",filename:"bk-hn-pho-end-ong4s-title"},
  {id: 2, text:"chống",filename:"bk-hn-pho-end-ong4s-chong4s"},
  {id: 3, text:"cống",filename:"bk-hn-pho-end-ong4s-cong4s"},
  {id: 4, text:"khống",filename:"bk-hn-pho-end-ong4s-khong4s"},
  {id: 5, text:"xống",filename:"bk-hn-pho-end-ong4s-xong4s"},
  {id: 6, text:"rống",filename:"bk-hn-pho-end-ong4s-rong4s"},
  {id: 7, text:"bống",filename:"bk-hn-pho-end-ong4s-bong4s"},
  {id: 8, text:"đống",filename:"bk-hn-pho-end-ong4s-dong74s"},
  {id: 9, text:"sống",filename:"bk-hn-pho-end-ong4s-song4s"},
  {id: 10, text:"trống",filename:"bk-hn-pho-end-ong4s-trong4s"},
];
export const WORDS_ENDING_WITH_op4j: Word[] = [
  {id: 0, text:"ộp",filename:"bk-hn-pho-end-op4j-title"},
  {id: 1, text:"...ộp",filename:"bk-hn-pho-end-op4j-title"},
  {id: 2, text:"bộp",filename:"bk-hn-pho-end-op4j-bop4j"},
  {id: 3, text:"chộp",filename:"bk-hn-pho-end-op4j-chop4j"},
  {id: 4, text:"rộp",filename:"bk-hn-pho-end-op4j-rop4j"},
  {id: 5, text:"hộp",filename:"bk-hn-pho-end-op4j-hop4j"},
  {id: 6, text:"dộp",filename:"bk-hn-pho-end-op4j-dop4j"},
];
export const WORDS_ENDING_WITH_op4s: Word[] = [
  {id: 0, text:"ốp",filename:"bk-hn-pho-end-op4s-title"},
  {id: 1, text:"...ốp",filename:"bk-hn-pho-end-op4s-title"},
  {id: 2, text:"cốp",filename:"bk-hn-pho-end-op4s-cop4s"},
  {id: 3, text:"lốp",filename:"bk-hn-pho-end-op4s-lop4s"},
  {id: 4, text:"mốp",filename:"bk-hn-pho-end-op4s-mop4s"},
  {id: 5, text:"xốp",filename:"bk-hn-pho-end-op4s-xop4s"},
  {id: 6, text:"phốp",filename:"bk-hn-pho-end-op4s-phop4s"},
  {id: 7, text:"bốp",filename:"bk-hn-pho-end-op4s-bop4s"},
];
export const WORDS_ENDING_WITH_ot4s: Word[] = [
  {id: 0, text:"ốt",filename:"bk-hn-pho-end-ot4s-title"},
  {id: 1, text:"...ốt",filename:"bk-hn-pho-end-ot4s-title"},
  {id: 2, text:"đốt",filename:"bk-hn-pho-end-ot4s-dot74s"},
  {id: 3, text:"hốt",filename:"bk-hn-pho-end-ot4s-hot4s"},
  {id: 4, text:"thốt",filename:"bk-hn-pho-end-ot4s-thot74s"},
  {id: 5, text:"tốt",filename:"bk-hn-pho-end-ot4s-tot74s"},
  {id: 6, text:"nốt",filename:"bk-hn-pho-end-ot4s-not74s"},
  {id: 7, text:"xốt",filename:"bk-hn-pho-end-ot4s-xot4s"},
  {id: 8, text:"sốt",filename:"bk-hn-pho-end-ot4s-sot4s"},
  {id: 9, text:"lốt",filename:"bk-hn-pho-end-ot4s-lot4s"},
  {id: 10, text:"nhốt",filename:"bk-hn-pho-end-ot4s-nhot4s"},
];
export const WORDS_ENDING_WITH_ot4j: Word[] = [
  {id: 0, text:"ột",filename:"bk-hn-pho-end-ot4j-title"},
  {id: 1, text:"...ột",filename:"bk-hn-pho-end-ot4j-title"},
  {id: 2, text:"cột",filename:"bk-hn-pho-end-ot4j-cot4j"},
  {id: 3, text:"bột",filename:"bk-hn-pho-end-ot4j-bot4j"},
  {id: 4, text:"một",filename:"bk-hn-pho-end-ot4j-mot4j"},
  {id: 5, text:"lột",filename:"bk-hn-pho-end-ot4j-lot4j"},
  {id: 6, text:"gột",filename:"bk-hn-pho-end-ot4j-got4j"},
  {id: 7, text:"hột",filename:"bk-hn-pho-end-ot4j-hot4j"},
  {id: 8, text:"nhột",filename:"bk-hn-pho-end-ot4j-nhot4j"},
];
export const WORDS_ENDING_WITH_oi6: Word[] = [
  {id: 0, text:"ơi",filename:"bk-hn-pho-end-oi6-title"},
  {id: 1, text:"...ơi",filename:"bk-hn-pho-end-oi6-title"},
  {id: 2, text:"bơi",filename:"bk-hn-pho-end-oi6-boi6"},
  {id: 3, text:"nơi",filename:"bk-hn-pho-end-oi6-noi6"},
  {id: 4, text:"chơi",filename:"bk-hn-pho-end-oi6-choi6"},
  {id: 5, text:"thơi",filename:"bk-hn-pho-end-oi6-thoi6"},
  {id: 6, text:"xơi",filename:"bk-hn-pho-end-oi6-xoi6"},
  {id: 7, text:"dơi",filename:"bk-hn-pho-end-oi6-doi6"},
  {id: 8, text:"hơi",filename:"bk-hn-pho-end-oi6-hoi6"},
  {id: 9, text:"rơi",filename:"bk-hn-pho-end-oi6-roi6"},
  {id: 10, text:"tơi",filename:"bk-hn-pho-end-oi6-toi6"},
  {id: 11, text:"vơi",filename:"bk-hn-pho-end-oi6-voi6"},
];
export const WORDS_ENDING_WITH_oi6s: Word[] = [
  {id: 0, text:"ới",filename:"bk-hn-pho-end-oi6s-title"},
  {id: 1, text:"...ới",filename:"bk-hn-pho-end-oi6s-title"},
  {id: 2, text:"mới",filename:"bk-hn-pho-end-oi6s-moi6s"},
  {id: 3, text:"tới",filename:"bk-hn-pho-end-oi6s-toi6s"},
  {id: 4, text:"thới",filename:"bk-hn-pho-end-oi6s-thoi6s"},
  {id: 5, text:"xới",filename:"bk-hn-pho-end-oi6s-xoi6s"},
  {id: 6, text:"bới",filename:"bk-hn-pho-end-oi6s-boi6s"},
  {id: 7, text:"nới",filename:"bk-hn-pho-end-oi6s-noi6s"},
  {id: 8, text:"với",filename:"bk-hn-pho-end-oi6s-voi6s"},
];
export const WORDS_ENDING_WITH_om6: Word[] = [
  {id: 0, text:"ơm",filename:"bk-hn-pho-end-om6-title"},
  {id: 1, text:"...ơm",filename:"bk-hn-pho-end-om6-title"},
  {id: 2, text:"cơm",filename:"bk-hn-pho-end-om6-com6"},
  {id: 3, text:"đơm",filename:"bk-hn-pho-end-om6-dom76"},
  {id: 4, text:"rơm",filename:"bk-hn-pho-end-om6-rom6"},
  {id: 5, text:"thơm",filename:"bk-hn-pho-end-om6-thom6"},
  {id: 6, text:"bơm",filename:"bk-hn-pho-end-om6-bom6"},
  {id: 7, text:"nơm",filename:"bk-hn-pho-end-om6-nom6"},
];
export const WORDS_ENDING_WITH_on6: Word[] = [
  {id: 0, text:"ơn",filename:"bk-hn-pho-end-on6-title"},
  {id: 1, text:"...ơn",filename:"bk-hn-pho-end-on6-title"},
  {id: 2, text:"cơn",filename:"bk-hn-pho-end-on6-con6"},
  {id: 3, text:"mơn",filename:"bk-hn-pho-end-on6-mon6"},
  {id: 4, text:"sơn",filename:"bk-hn-pho-end-on6-son6"},
  {id: 5, text:"đơn",filename:"bk-hn-pho-end-on6-don76"},
  {id: 6, text:"hơn",filename:"bk-hn-pho-end-on6-hon6"},
  {id: 7, text:"trơn",filename:"bk-hn-pho-end-on6-tron6"},
];
export const WORDS_ENDING_WITH_ua5f: Word[] = [
  {id: 0, text:"ừa",filename:"bk-hn-pho-end-ua5f-title"},
  {id: 1, text:"...ừa",filename:"bk-hn-pho-end-ua5f-title"},
  {id: 2, text:"chừa",filename:"bk-hn-pho-end-ua5f-chua5f"},
  {id: 3, text:"dừa",filename:"bk-hn-pho-end-ua5f-dua5f"},
  {id: 4, text:"lừa",filename:"bk-hn-pho-end-ua5f-lua5f"},
  {id: 5, text:"ngừa",filename:"bk-hn-pho-end-ua5f-ngua5f"},
  {id: 6, text:"vừa",filename:"bk-hn-pho-end-ua5f-vua5f"},
  {id: 7, text:"bừa",filename:"bk-hn-pho-end-ua5f-bua5f"},
  {id: 8, text:"thừa",filename:"bk-hn-pho-end-ua5f-thua5f"},
];
export const WORDS_ENDING_WITH_ua5x: Word[] = [
  {id: 0, text:"ữa",filename:"bk-hn-pho-end-ua5x-title"},
  {id: 1, text:"...ữa",filename:"bk-hn-pho-end-ua5x-title"},
  {id: 2, text:"bữa",filename:"bk-hn-pho-end-ua5x-bua5x"},
  {id: 3, text:"chữa",filename:"bk-hn-pho-end-ua5x-chua5x"},
  {id: 4, text:"giữa",filename:"bk-hn-pho-end-ua5x-giua5x"},
  {id: 5, text:"nữa",filename:"bk-hn-pho-end-ua5x-nua5x"},
  {id: 6, text:"sữa",filename:"bk-hn-pho-end-ua5x-sua5x"},
];
export const WORDS_ENDING_WITH_ung5: Word[] = [
  {id: 0, text:"ưng",filename:"bk-hn-pho-end-ung5-title"},
  {id: 1, text:"...ưng",filename:"bk-hn-pho-end-ung5-title"},
  {id: 2, text:"bưng",filename:"bk-hn-pho-end-ung5-bung5"},
  {id: 3, text:"cưng",filename:"bk-hn-pho-end-ung5-cung5"},
  {id: 4, text:"dưng",filename:"bk-hn-pho-end-ung5-dung5"},
  {id: 5, text:"ngưng",filename:"bk-hn-pho-end-ung5-ngung5"},
  {id: 6, text:"rưng",filename:"bk-hn-pho-end-ung5-rung5"},
  {id: 7, text:"lưng",filename:"bk-hn-pho-end-ung5-lung5"},
  {id: 8, text:"sưng",filename:"bk-hn-pho-end-ung5-sung5"},
];
export const WORDS_ENDING_WITH_ung5r: Word[] = [
  {id: 0, text:"ửng",filename:"bk-hn-pho-end-ung5r-title"},
  {id: 1, text:"...ửng",filename:"bk-hn-pho-end-ung5r-title"},
  {id: 2, text:"bửng",filename:"bk-hn-pho-end-ung5r-bung5r"},
  {id: 3, text:"dửng",filename:"bk-hn-pho-end-ung5r-dung5r"},
  {id: 4, text:"lửng",filename:"bk-hn-pho-end-ung5r-lung5r"},
  {id: 5, text:"tửng",filename:"bk-hn-pho-end-ung5r-tung5r"},
  {id: 6, text:"xửng",filename:"bk-hn-pho-end-ung5r-xung5r"},
];
export const WORDS_ENDING_WITH_uoc56s: Word[] = [
  {id: 0, text:"ước",filename:"bk-hn-pho-end-uoc56s-title"},
  {id: 1, text:"...ước",filename:"bk-hn-pho-end-uoc56s-title"},
  {id: 2, text:"bước",filename:"bk-hn-pho-end-uoc56s-buoc56"},
  {id: 3, text:"chước",filename:"bk-hn-pho-end-uoc56s-chuoc56"},
  {id: 4, text:"ngước",filename:"bk-hn-pho-end-uoc56s-nguoc56"},
  {id: 5, text:"phươc",filename:"bk-hn-pho-end-uoc56s-phuoc56"},
  {id: 6, text:"thước",filename:"bk-hn-pho-end-uoc56s-thuoc56"},
  {id: 7, text:"trước",filename:"bk-hn-pho-end-uoc56s-truoc56s"},
  {id: 8, text:"rước",filename:"bk-hn-pho-end-uoc56s-ruoc56s"},
  {id: 9, text:"nước",filename:"bk-hn-pho-end-uoc56s-nuoc56s"},
  {id: 10, text:"xước",filename:"bk-hn-pho-end-uoc56s-xuoc56s"},
  {id: 11, text:"khước",filename:"bk-hn-pho-end-uoc56s-khuoc56s"},
];
export const WORDS_ENDING_WITH_uoc56j: Word[] = [
  {id: 0, text:"ược",filename:"bk-hn-pho-end-uoc56j-title"},
  {id: 1, text:"...ược",filename:"bk-hn-pho-end-uoc56j-title"},
  {id: 2, text:"cược",filename:"bk-hn-pho-end-uoc56j-cuoc56j"},
  {id: 3, text:"đưọc",filename:"bk-hn-pho-end-uoc56j-duoc756j"},
  {id: 4, text:"lược",filename:"bk-hn-pho-end-uoc56j-luoc56j"},
  {id: 5, text:"ngược",filename:"bk-hn-pho-end-uoc56j-nguoc56j"},
  {id: 6, text:"nhược",filename:"bk-hn-pho-end-uoc56j-nhuoc56j"},
];
export const WORDS_ENDING_WITH_uong56s: Word[] = [
  {id: 0, text:"ướng",filename:"bk-hn-pho-end-uong56s-title"},
  {id: 1, text:"...ướng",filename:"bk-hn-pho-end-uong56s-title"},
  {id: 2, text:"bướng",filename:"bk-hn-pho-end-uong56s-buong56s"},
  {id: 3, text:"chướng",filename:"bk-hn-pho-end-uong56s-chuong56s"},
  {id: 4, text:"hướng",filename:"bk-hn-pho-end-uong56s-huong56s"},
  {id: 5, text:"sướng",filename:"bk-hn-pho-end-uong56s-suong56s"},
  {id: 6, text:"tướng",filename:"bk-hn-pho-end-uong56s-tuong56"},
  {id: 7, text:"vướng",filename:"bk-hn-pho-end-uong56s-vuong56s"},
  {id: 8, text:"nướng",filename:"bk-hn-pho-end-uong56s-nuong56s"},
];
export const WORDS_ENDING_WITH_uong56r: Word[] = [
  {id: 0, text:"ưởng",filename:"bk-hn-pho-end-uong56r-title"},
  {id: 1, text:"...ưởng",filename:"bk-hn-pho-end-uong56r-title"},
  {id: 2, text:"chưởng",filename:"bk-hn-pho-end-uong56r-chuong56r"},
  {id: 3, text:"hưởng",filename:"bk-hn-pho-end-uong56r-huong56r"},
  {id: 4, text:"tưởng",filename:"bk-hn-pho-end-uong56r-tuong56r"},
  {id: 5, text:"trưởng",filename:"bk-hn-pho-end-uong56r-truong56r"},
  {id: 6, text:"xưởng",filename:"bk-hn-pho-end-uong56r-xuong56r"},
];
export const WORDS_ENDING_WITH_uong56j: Word[] = [
  {id: 0, text:"ượng",filename:"bk-hn-pho-end-uong56j-title"},
  {id: 1, text:"...ượng",filename:"bk-hn-pho-end-uong56j-title"},
  {id: 2, text:"dượng",filename:"bk-hn-pho-end-uong56j-duong56j"},
  {id: 3, text:"lượng",filename:"bk-hn-pho-end-uong56j-luong56j"},
  {id: 4, text:"ngượng",filename:"bk-hn-pho-end-uong56j-nguong56j"},
  {id: 5, text:"tượng",filename:"bk-hn-pho-end-uong56j-tuong56j"},
  {id: 6, text:"vượng",filename:"bk-hn-pho-end-uong56j-vuong56j"},
  {id: 7, text:"gượng",filename:"bk-hn-pho-end-uong56j-guong56j"},
  {id: 8, text:"nhượng",filename:"bk-hn-pho-end-uong56j-nhuong56j"},
  {id: 9, text:"thượng",filename:"bk-hn-pho-end-uong56j-thuong56j"},
];
export const WORDS_ENDING_WITH_ua: Word[] = [
  {id: 0, text:"ua",filename:"bk-hn-pho-end-ua-title"},
  {id: 1, text:"...ua",filename:"bk-hn-pho-end-ua-title"},
  {id: 2, text:"cua",filename:"bk-hn-pho-end-ua-cua"},
  {id: 3, text:"dua",filename:"bk-hn-pho-end-ua-dua"},
  {id: 4, text:"đua",filename:"bk-hn-pho-end-ua-dua7"},
  {id: 5, text:"khua",filename:"bk-hn-pho-end-ua-khua"},
  {id: 6, text:"mua",filename:"bk-hn-pho-end-ua-mua"},
  {id: 7, text:"tua",filename:"bk-hn-pho-end-ua-tua"},
  {id: 8, text:"vua",filename:"bk-hn-pho-end-ua-vua"},
  {id: 9, text:"thua",filename:"bk-hn-pho-end-ua-thua"},
  {id: 10, text:"chua",filename:"bk-hn-pho-end-ua-chua"},
];
export const WORDS_ENDING_WITH_uar: Word[] = [
  {id: 0, text:"ủa",filename:"bk-hn-pho-end-uar-title"},
  {id: 1, text:"...ủa",filename:"bk-hn-pho-end-uar-title"},
  {id: 2, text:"của",filename:"bk-hn-pho-end-uar-cuar"},
  {id: 3, text:"rủa",filename:"bk-hn-pho-end-uar-ruar"},
  {id: 4, text:"sủa",filename:"bk-hn-pho-end-uar-suar"},
  {id: 5, text:"tủa",filename:"bk-hn-pho-end-uar-tuar"},
];
export const WORDS_ENDING_WITH_uif: Word[] = [
  {id: 0, text:"ùi",filename:"bk-hn-pho-end-uif-title"},
  {id: 1, text:"...ùi",filename:"bk-hn-pho-end-uif-title"},
  {id: 2, text:"dùi",filename:"bk-hn-pho-end-uif-duif"},
  {id: 3, text:"đùi",filename:"bk-hn-pho-end-uif-dui7f"},
  {id: 4, text:"lùi",filename:"bk-hn-pho-end-uif-luif"},
  {id: 5, text:"mùi",filename:"bk-hn-pho-end-uif-muif"},
  {id: 6, text:"nùi",filename:"bk-hn-pho-end-uif-nuif"},
  {id: 7, text:"bùi",filename:"bk-hn-pho-end-uif-buif"},
  {id: 8, text:"gùi",filename:"bk-hn-pho-end-uif-guif"},
  {id: 9, text:"cùi",filename:"bk-hn-pho-end-uif-cuif"},
  {id: 10, text:"sùi",filename:"bk-hn-pho-end-uif-suif"},
  {id: 11, text:"chùi",filename:"bk-hn-pho-end-uif-chuif"},
];
export const WORDS_ENDING_WITH_uis: Word[] = [
  {id: 0, text:"úi",filename:"bk-hn-pho-end-uis-title"},
  {id: 1, text:"...úi",filename:"bk-hn-pho-end-uis-title"},
  {id: 2, text:"cúi",filename:"bk-hn-pho-end-uis-cuis"},
  {id: 3, text:"chúi",filename:"bk-hn-pho-end-uis-chuis"},
  {id: 4, text:"húi",filename:"bk-hn-pho-end-uis-huis"},
  {id: 5, text:"múi",filename:"bk-hn-pho-end-uis-muis"},
  {id: 6, text:"xúi",filename:"bk-hn-pho-end-uis-xuis"},
  {id: 7, text:"túi",filename:"bk-hn-pho-end-uis-tuis"},
  {id: 8, text:"núi",filename:"bk-hn-pho-end-uis-nuis"},
  {id: 9, text:"búi",filename:"bk-hn-pho-end-uis-buis"},
];
export const WORDS_ENDING_WITH_uy: Word[] = [
  {id: 0, text:"uy",filename:"bk-hn-pho-end-uy-title"},
  {id: 1, text:"...uy",filename:"bk-hn-pho-end-uy-title"},
  {id: 2, text:"duy",filename:"bk-hn-pho-end-uy-duy"},
  {id: 3, text:"khuy",filename:"bk-hn-pho-end-uy-khuy"},
  {id: 4, text:"nguy",filename:"bk-hn-pho-end-uy-nguy"},
  {id: 5, text:"suy",filename:"bk-hn-pho-end-uy-suy"},
  {id: 6, text:"tuy",filename:"bk-hn-pho-end-uy-tuy"},
];
export const WORDS_ENDING_WITH_uyj: Word[] = [
  {id: 0, text:"ụy",filename:"bk-hn-pho-end-uyj-title"},
  {id: 1, text:"...ụy",filename:"bk-hn-pho-end-uyj-title"},
  {id: 2, text:"khụy",filename:"bk-hn-pho-end-uyj-khuyj"},
  {id: 3, text:"lụy",filename:"bk-hn-pho-end-uyj-luyj"},
  {id: 4, text:"ngụy",filename:"bk-hn-pho-end-uyj-nguyj"},
  {id: 5, text:"nhụy",filename:"bk-hn-pho-end-uyj-nhuyj"},
  {id: 6, text:"quỵ",filename:"bk-hn-pho-end-uyj-quyj"},
];
export const WORDS_ENDING_WITH_ucs: Word[] = [
  {id: 0, text:"úc",filename:"bk-hn-pho-end-ucs-title"},
  {id: 1, text:"...úc",filename:"bk-hn-pho-end-ucs-title"},
  {id: 2, text:"cúc",filename:"bk-hn-pho-end-ucs-cucs"},
  {id: 3, text:"chúc",filename:"bk-hn-pho-end-ucs-chucs"},
  {id: 4, text:"húc",filename:"bk-hn-pho-end-ucs-hucs"},
  {id: 5, text:"lúc",filename:"bk-hn-pho-end-ucs-lucs"},
  {id: 6, text:"thúc",filename:"bk-hn-pho-end-ucs-thucs"},
  {id: 7, text:"xúc",filename:"bk-hn-pho-end-ucs-xucs"},
  {id: 8, text:"trúc",filename:"bk-hn-pho-end-ucs-trucs"},
  {id: 9, text:"khúc",filename:"bk-hn-pho-end-ucs-khucs"},
  {id: 10, text:"đúc",filename:"bk-hn-pho-end-ucs-duc7s"},
  {id: 11, text:"múc",filename:"bk-hn-pho-end-ucs-mucs"},
  {id: 12, text:"rúc",filename:"bk-hn-pho-end-ucs-rucs"},
];
export const WORDS_ENDING_WITH_ucj: Word[] = [
  {id: 0, text:"ục",filename:"bk-hn-pho-end-ucj-title"},
  {id: 1, text:"...ục",filename:"bk-hn-pho-end-ucj-title"},
  {id: 2, text:"đục",filename:"bk-hn-pho-end-ucj-duc7j"},
  {id: 3, text:"mục",filename:"bk-hn-pho-end-ucj-mucj"},
  {id: 4, text:"tục",filename:"bk-hn-pho-end-ucj-tucj"},
  {id: 5, text:"trục",filename:"bk-hn-pho-end-ucj-trucj"},
  {id: 6, text:"thục",filename:"bk-hn-pho-end-ucj-thucj"},
  {id: 7, text:"gục",filename:"bk-hn-pho-end-ucj-gucj"},
  {id: 8, text:"nhục",filename:"bk-hn-pho-end-ucj-nhucj"},
  {id: 9, text:"phục",filename:"bk-hn-pho-end-ucj-phucj"},
  {id: 10, text:"cục",filename:"bk-hn-pho-end-ucj-cucj"},
  {id: 11, text:"giục",filename:"bk-hn-pho-end-ucj-giucj"},
  {id: 12, text:"lục",filename:"bk-hn-pho-end-ucj-lucj"},
];
export const WORDS_ENDING_WITH_um: Word[] = [
  {id: 0, text:"um",filename:"bk-hn-pho-end-um-title"},
  {id: 1, text:"...um",filename:"bk-hn-pho-end-um-title"},
  {id: 2, text:"chum",filename:"bk-hn-pho-end-um-chum"},
  {id: 3, text:"khum",filename:"bk-hn-pho-end-um-khum"},
  {id: 4, text:"sum",filename:"bk-hn-pho-end-um-sum"},
  {id: 5, text:"tum",filename:"bk-hn-pho-end-um-tum"},
  {id: 6, text:"thum",filename:"bk-hn-pho-end-um-thum"},
  {id: 7, text:"xum",filename:"bk-hn-pho-end-um-xum"},
];
export const WORDS_ENDING_WITH_umf: Word[] = [
  {id: 0, text:"ùm",filename:"bk-hn-pho-end-umf-title"},
  {id: 1, text:"...ùm",filename:"bk-hn-pho-end-umf-title"},
  {id: 2, text:"dùm",filename:"bk-hn-pho-end-umf-dumf"},
  {id: 3, text:"đùm",filename:"bk-hn-pho-end-umf-dum7f"},
  {id: 4, text:"lùm",filename:"bk-hn-pho-end-umf-lumf"},
  {id: 5, text:"rùm",filename:"bk-hn-pho-end-umf-rumf"},
  {id: 6, text:"tùm",filename:"bk-hn-pho-end-umf-tumf"},
];
export const WORDS_ENDING_WITH_ung: Word[] = [
  {id: 0, text:"ung",filename:"bk-hn-pho-end-ung-title"},
  {id: 1, text:"...ung",filename:"bk-hn-pho-end-ung-title"},
  {id: 2, text:"bung",filename:"bk-hn-pho-end-ung-bung"},
  {id: 3, text:"dung",filename:"bk-hn-pho-end-ung-dung"},
  {id: 4, text:"hung",filename:"bk-hn-pho-end-ung-hung"},
  {id: 5, text:"lung",filename:"bk-hn-pho-end-ung-lung"},
  {id: 6, text:"rung",filename:"bk-hn-pho-end-ung-rung"},
  {id: 7, text:"vung",filename:"bk-hn-pho-end-ung-vung"},
  {id: 8, text:"tung",filename:"bk-hn-pho-end-ung-tung"},
  {id: 9, text:"sung",filename:"bk-hn-pho-end-ung-sung"},
  {id: 10, text:"khung",filename:"bk-hn-pho-end-ung-khung"},
];
export const WORDS_ENDING_WITH_ungf: Word[] = [
  {id: 0, text:"ùng",filename:"bk-hn-pho-end-ungf-title"},
  {id: 1, text:"...ùng",filename:"bk-hn-pho-end-ungf-title"},
  {id: 2, text:"cùng",filename:"bk-hn-pho-end-ungf-cungf"},
  {id: 3, text:"dùng",filename:"bk-hn-pho-end-ungf-dungf"},
  {id: 4, text:"tùng",filename:"bk-hn-pho-end-ungf-tungf"},
  {id: 5, text:"thùng",filename:"bk-hn-pho-end-ungf-thungf"},
  {id: 6, text:"sùng",filename:"bk-hn-pho-end-ungf-sungf"},
  {id: 7, text:"vùng",filename:"bk-hn-pho-end-ungf-vungf"},
  {id: 8, text:"trùng",filename:"bk-hn-pho-end-ungf-trungf"},
  {id: 9, text:"mùng",filename:"bk-hn-pho-end-ungf-mungf"},
];
export const WORDS_ENDING_WITH_ungr: Word[] = [
  {id: 0, text:"ủng",filename:"bk-hn-pho-end-ungr-title"},
  {id: 1, text:"...ủng",filename:"bk-hn-pho-end-ungr-title"},
  {id: 2, text:"bủng",filename:"bk-hn-pho-end-ungr-bungr"},
  {id: 3, text:"củng",filename:"bk-hn-pho-end-ungr-cungr"},
  {id: 4, text:"chủng",filename:"bk-hn-pho-end-ungr-chungr"},
  {id: 5, text:"khủng",filename:"bk-hn-pho-end-ungr-khungr"},
  {id: 6, text:"thủng",filename:"bk-hn-pho-end-ungr-thungr"},
];
export const WORDS_ENDING_WITH_ungj: Word[] = [
  {id: 0, text:"ụng",filename:"bk-hn-pho-end-ungj-title"},
  {id: 1, text:"...ụng",filename:"bk-hn-pho-end-ungj-title"},
  {id: 2, text:"cụng",filename:"bk-hn-pho-end-ungj-cungj"},
  {id: 3, text:"dụng",filename:"bk-hn-pho-end-ungj-dungj"},
  {id: 4, text:"đụng",filename:"bk-hn-pho-end-ungj-dung7j"},
  {id: 5, text:"lụng",filename:"bk-hn-pho-end-ungj-lungj"},
  {id: 6, text:"rụng",filename:"bk-hn-pho-end-ungj-rungj"},
  {id: 7, text:"bụng",filename:"bk-hn-pho-end-ungj-bungj"},
  {id: 8, text:"vụng",filename:"bk-hn-pho-end-ungj-vungj"},
  {id: 9, text:"thụng",filename:"bk-hn-pho-end- ungj-thungj"},
  {id: 10, text:"trụng",filename:"bk-hn-pho-end-ungj-trungj"},
];
export const WORDS_ENDING_WITH_ups: Word[] = [
  {id: 0, text:"úp",filename:"bk-hn-pho-end-ups-title"},
  {id: 1, text:"...úp",filename:"bk-hn-pho-end-ups-title"},
  {id: 2, text:"búp",filename:"bk-hn-pho-end-ups-bups"},
  {id: 3, text:"lúp",filename:"bk-hn-pho-end-ups-lups"},
  {id: 4, text:"núp",filename:"bk-hn-pho-end-ups-nups"},
  {id: 5, text:"súp",filename:"bk-hn-pho-end-ups-sups"},
  {id: 6, text:"túp",filename:"bk-hn-pho-end-ups-tups"},
  {id: 7, text:"cúp",filename:"bk-hn-pho-end-ups-cups"},
  {id: 8, text:"giúp",filename:"bk-hn-pho-end-ups-giups"},
  {id: 9, text:"núp",filename:"bk-hn-pho-end-ups-nups"},
  {id: 10, text:"húp",filename:"bk-hn-pho-end-ups-hups"},
];
export const WORDS_ENDING_WITH_upj: Word[] = [
  {id: 0, text:"ụp",filename:"bk-hn-pho-end-upj-title"},
  {id: 1, text:"...ụp",filename:"bk-hn-pho-end-upj-title"},
  {id: 2, text:"bụp",filename:"bk-hn-pho-end-upj-bupj"},
  {id: 3, text:"cụp",filename:"bk-hn-pho-end-upj-cupj"},
  {id: 4, text:"chụp",filename:"bk-hn-pho-end-upj-chupj"},
  {id: 5, text:"sụp",filename:"bk-hn-pho-end-upj-supj"},
  {id: 6, text:"dụp",filename:"bk-hn-pho-end-upj-dupj"},
];
export const WORDS_ENDING_WITH_uts: Word[] = [
  {id: 0, text:"út",filename:"bk-hn-pho-end-uts-title"},
  {id: 1, text:"...út",filename:"bk-hn-pho-end-uts-title"},
  {id: 2, text:"bút",filename:"bk-hn-pho-end-uts-buts"},
  {id: 3, text:"cút",filename:"bk-hn-pho-end-uts-cuts"},
  {id: 4, text:"chút",filename:"bk-hn-pho-end-uts-chuts"},
  {id: 5, text:"sút",filename:"bk-hn-pho-end-uts-suts"},
  {id: 6, text:"ngút",filename:"bk-hn-pho-end-uts-nguts"},
  {id: 7, text:"út",filename:"bk-hn-pho-end-uts-uts"},
  {id: 8, text:"đút",filename:"bk-hn-pho-end-uts-dut7s"},
  {id: 9, text:"hút",filename:"bk-hn-pho-end-uts-huts"},
  {id: 10, text:"mút",filename:"bk-hn-pho-end-uts-muts"},
  {id: 11, text:"nút",filename:"bk-hn-pho-end-uts-nuts"},
  {id: 12, text:"rút",filename:"bk-hn-pho-end-uts-ruts"},
  {id: 13, text:"vút",filename:"bk-hn-pho-end-uts-vuts"},
];
export const WORDS_ENDING_WITH_utj: Word[] = [
  {id: 0, text:"ụt",filename:"bk-hn-pho-end-utj-title"},
  {id: 1, text:"...ụt",filename:"bk-hn-pho-end-utj-title"},
  {id: 2, text:"bụt",filename:"bk-hn-pho-end-utj-butj"},
  {id: 3, text:"cụt",filename:"bk-hn-pho-end-utj-cutj"},
  {id: 4, text:"sụt",filename:"bk-hn-pho-end-utj-sutj"},
  {id: 5, text:"rụt",filename:"bk-hn-pho-end-utj-rutj"},
  {id: 6, text:"thụt",filename:"bk-hn-pho-end-utj-thutj"},
  {id: 7, text:"hụt",filename:"bk-hn-pho-end-utj-hutj"},
  {id: 8, text:"lụt",filename:"bk-hn-pho-end-utj-lutj"},
  {id: 9, text:"tụt",filename:"bk-hn-pho-end-utj-tutj"},
];
export const WORDS_ENDING_WITH_ap1s: Word[] = [
  {id: 0, text:"ắp",filename:"bk-hn-pho-end-ap1s-title"},
  {id: 1, text:"...ắp",filename:"bk-hn-pho-end-ap1s-title"},
  {id: 2, text:"bắp",filename:"bk-hn-pho-end-ap1s-bap1s"},
  {id: 3, text:"cắp",filename:"bk-hn-pho-end-ap1s-cap1s"},
  {id: 4, text:"tắp",filename:"bk-hn-pho-end-ap1s-tap1s"},
  {id: 5, text:"lắp",filename:"bk-hn-pho-end-ap1s-lap1s"},
  {id: 6, text:"rắp",filename:"bk-hn-pho-end-ap1s-rap1s"},
  {id: 7, text:"thắp",filename:"bk-hn-pho-end-ap1s-thap1s"},
  {id: 8, text:"khắp",filename:"bk-hn-pho-end-ap1s-khap1s"},
  {id: 9, text:"săp",filename:"bk-hn-pho-end-ap1s-sap1s"},
  {id: 10, text:"nắp",filename:"bk-hn-pho-end-ap1s-nap1s"},
  {id: 11, text:"gắp",filename:"bk-hn-pho-end-ap1s-gap1s"}];







